In [1]:
%load_ext autoreload
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# General

In [2]:
from ioutils import FileIO
from fileutils import DirInfo, FileInfo
from master import MasterParams
from pandas import Series, DataFrame
from sys import prefix
from listUtils import getFlatList
from musicdb import MusicDBIO
from utils import MusicDBPermDir
mp    = MasterParams(verbose=True)
io    = FileIO()
mdbpd = MusicDBPermDir()

MasterParams()
  ==> DBs:       ['Discogs', 'Spotify', 'LastFM', 'Genius', 'RateYourMusic', 'MetalArchives', 'Deezer', 'AllMusic', 'MusicBrainz', 'AlbumOfTheYear']
  ==> Raw Path:  /Volumes/Piggy/Discog
  ==> Mod Path:  /Volumes/Seagate/Discog
  ==> Sum Path:  /Users/tgadfort/Music/Discog
  ==> MaxModVal: 100
  ==> Project:   pandb
  ==> MusicDB:   musicdb

# DB-Specific

In [3]:
from lib import deezer
mio   = deezer.MusicDBIO(verbose=False)
apiio = deezer.RawAPIData()
db    = mio.db
permDBDir = mdbpd.getDBPermPath("Deezer")
print("Saving Perminant {0} DB Data To {1}".format(db, permDBDir.str))

Deezer API(Key=None)
Saving Perminant Deezer DB Data To /Users/tgadfort/opt/anaconda3/envs/py310/pandb/mdblib/Deezer

# Master Files

In [4]:
from base import MusicDBDir, MusicDBData
permDir = MusicDBDir(permDBDir)
localRelatedData        = MusicDBData(path=permDir, fname="{0}SearchedForLocalRelatedData".format(db.lower()))
localRelated            = MusicDBData(path=permDir, fname="{0}SearchedForLocalRelated".format(db.lower()))
masterRelatedArtistData = mio.data.getRelatedArtistsData()
localArtistsInfoData    = MusicDBData(path=permDir, fname="{0}SearchedForLocalArtistsInfoData".format(db.lower()))
localArtistsInfo        = MusicDBData(path=permDir, fname="{0}SearchedForLocalArtistsInfo".format(db.lower()))
masterArtistsInfoData   = mio.data.getArtistsInfoData()
knownArtists            = mio.data.getSummaryNameData()
errors                  = MusicDBData(path=permDir, fname="{0}SearchedForErrors".format(db.lower()))

In [5]:
##########################################################################################
# Show Summary
##########################################################################################
print("{0} Search Results".format(db))
print("   Local Related Artists:       {0}".format(len(localRelated.get())))
print("   Local Related Artists Data:  {0}".format(len(localRelatedData.get())))
print("   Master Related Artists Data: {0}".format(len(masterRelatedArtistData)))
print("   Local Artists Info:          {0}".format(len(localArtistsInfo.get())))
print("   Local Artists Info Data:     {0}".format(len(localArtistsInfoData.get())))
print("   Master Artists Info Data:    {0}".format(masterArtistsInfoData.shape[0]))
print("   Errors:                      {0}".format(len(errors.get())))
print("   Known Summary IDs:           {0}".format(len(knownArtists)))

Deezer Search Results
   Local Related Artists:       93208
   Local Related Artists Data:  0
   Master Related Artists Data: 62431
   Local Artists Info:          313144
   Local Artists Info Data:     0
   Master Artists Info Data:    313129
   Errors:                      1781
   Known Summary IDs:           1069560

# Download Artist Info Data

In [6]:
mio   = deezer.MusicDBIO(verbose=False)
apiio = deezer.RawAPIData(debug=True)

Deezer API(Key=None)

## Find Artist IDs To Get

In [51]:
artistNames = mio.data.getSummaryNameData()
artistNames.name = "ArtistName"
basicData = DataFrame(artistNames).join(mio.data.getSummaryNumAlbumsData()).sort_values(by="NumAlbums", ascending=False)
localArtistsInfoDict = localArtistsInfo.get()
artistIDsToGet = basicData[~basicData.index.isin(localArtistsInfoDict.keys())]["ArtistName"]

print("{0} Search Results".format(db))
print("   Known Master Basic Data:   {0}".format(len(artistNames)))
print("   Known Artist Info Names:   {0}".format(len(localArtistsInfoDict)))
print("   Artist Names To Get:       {0}".format(len(artistIDsToGet)))

#   Artist Names To Get:       723903
#   Artist Names To Get:       703403

Deezer Search Results
   Known Master Basic Data:   1069560
   Known Artist Info Names:   375619
   Artist Names To Get:       703403

In [ ]:
from timeutils import Timestat, TermTime

ts = Timestat("Getting {0} ArtistIDs".format(db))
#tt = TermTime("tomorrow", "7:00am")
#tt = TermTime("tomorrow", "11:00am")
tt = TermTime("today", "7:00pm")
#tt = TermTime("today", "9:00pm")
maxN = 50000000

n  = 0
searchedForLocalArtistsInfo     = localArtistsInfo.get()
searchedForLocalArtistsInfoData = localArtistsInfoData.get()
searchedForErrors               = errors.get()
for i,(artistID,artistName) in enumerate(artistIDsToGet.iteritems()):
    if searchedForLocalArtistsInfo.get(artistID) is not None:
        continue

    response = apiio.getArtistInfoData(artistName=artistName, artistID=artistID)
    if response is None or len(response) == 0:
        if response is None:
            print("Error ==> {0}".format((artistID,artistName)))
            searchedForErrors[artistID] = artistName
            apiio.sleep(3.5)
        else:
            searchedForLocalArtistsInfo[artistID] = "NoInfo"
            apiio.sleep(1.5)
        continue
    
    searchedForLocalArtistsInfo[artistID]     = artistName
    searchedForLocalArtistsInfoData[artistID] = response
    apiio.sleep(1.5)
    n += 1
        
    if n % 50 == 0:
        apiio.sleep(2.5)
        print("="*150)
        ts.update(n=n)
        print("Saving {0} (New={1}) {2} Searched For Artist (Info) IDs".format(len(searchedForLocalArtistsInfo), len(searchedForLocalArtistsInfoData), db))
        localArtistsInfo.save(data=searchedForLocalArtistsInfo)
        localArtistsInfoData.save(data=searchedForLocalArtistsInfoData)
        if len(searchedForErrors) > 0:
            errors.save(data=searchedForErrors)
        print("="*150)
        apiio.sleep(2.5)
        if tt.isFinished():
            break
    
    if n >= maxN:
        print("Breaking after {0} downloads...".format(maxN))
        break

ts.stop()
print("Saving {0} {1} Searched For Artist (Info) IDs".format(len(searchedForLocalArtistsInfo), db))
localArtistsInfo.save(data=searchedForLocalArtistsInfo)
localArtistsInfoData.save(data=searchedForLocalArtistsInfoData)
if len(searchedForErrors) > 0:
    errors.save(data=searchedForErrors)

Starting Process [Getting Deezer ArtistIDs]    ==> Time Is 2022-03-22 10:21:01
========================= termTime(day=today,time=7:00pm) =========================
   ====> Terminate Time Set To 2022-03-22 19:00:00 <====
   ====> Will Terminate Process 8 Hours and 38 Minutes From Now
Searching For Artist Info For Sinking Creek (1059630)                           	True
Searching For Artist Info For Milky Beatz (9934630)                             	True
Searching For Artist Info For M.H.G. (152063712)                                	True
Searching For Artist Info For Bish Bash (14246021)                              	True
Searching For Artist Info For No Pressure (4746319)                             	True
Searching For Artist Info For Xplicit VibZ (119153102)                          	True
Searching For Artist Info For Pastor de Andorra (348091)                        	True
Searching For Artist Info For DJ Prime Cuts (3832701)                           	True
Searching For Artist Info For V2 Artist (125014202)                             	True
Searching For Artist Info For FIGARO NELES (123468202)                          	True
Searching For Artist Info For Crawling Beauty (131585922)                       	True
Searching For Artist Info For The Academic Symphony Orchestra of the Saint Petersburg Philarmony (7887726)	True
Searching For Artist Info For James Ure and the Fridge Doors (65091422)         	True
Searching For Artist Info For Seck (5215326)                                    	True
Searching For Artist Info For Aimless Endeavor (6960515)                        	True
Searching For Artist Info For Yasmeen (56876702)                                	True
Searching For Artist Info For Monsieur Pompier's Travelling Freakshow (136219022)	True
Searching For Artist Info For Rhea Robertson (4244021)                          	True
Searching For Artist Info For Remedee (5128930)                                 	True
Searching For Artist Info For Andreas Schmidt-Cornelia Kallisch-Deon van der Walt-Machiko Obata-Anne Schwanewilms-Andrew Collis-Chor des Städtischen Musikvereins e. V. Düsseldorf-James Conlon-Andrea Rost-Johannes Dietzel -Windsbacher Knabenchor (1492419)	True
Searching For Artist Info For Deepak Subramaniam (13888521)                     	True
Searching For Artist Info For Neal Scarborough (72615)                          	True
Searching For Artist Info For Tony Fat Hands (145271012)                        	True
Searching For Artist Info For Alienation (5060993)                              	True
Searching For Artist Info For P.K. & A.W. (520303)                              	True
Searching For Artist Info For Tension* (6977593)                                	True
Searching For Artist Info For BAC Beatbox Academy (14512899)                    	True
Searching For Artist Info For Sue Medley & The Back Road Band (5705621)         	True
Searching For Artist Info For 2 Rotten Scoundrels (7658986)                     	True
Searching For Artist Info For Noguchi Satoshi (15085509)                        	True
Searching For Artist Info For Luciana Espiritual (12647015)                     	True
Searching For Artist Info For Buddha Music Sanctuary (7473326)                  	True
Searching For Artist Info For Chan Soman (15003791)                             	True
Searching For Artist Info For Melbourne Shuffle (3842591)                       	True
Searching For Artist Info For Billy Fubar (96865422)                            	True
Searching For Artist Info For Brul?e (7680606)                                  	True
Searching For Artist Info For Ali Chukwumah & His Peace Makers International (1348003)	True
Searching For Artist Info For David R.Edwards (64617092)                        	True
Searching For Artist Info For Chris Williams (85012)                            	True
Searching For Artist Info For Soferino And Ibis Babe' (366895)                  	True
Searching For Artist Info For Sleep Noise Machine (14370499)                    	True
Searching For Artist Info For Vid Marjanovic AKA Estray & Float (9713806)       	True
Searching For Artist Info For Lucid Paradise (7889712)                          	True
Searching For Artist Info For Reza Zakarya (12791701)                           	True
Searching For Artist Info For Queen Chimera (100570822)                         	True
Searching For Artist Info For Maejor Omen (97508512)                            	True
Searching For Artist Info For Chicco Marola (65729792)                          	True
Searching For Artist Info For Kenny MFG (105523892)                             	True
Searching For Artist Info For Santiago Ramalle (1569615)                        	True
Searching For Artist Info For WIND-Da House (5889806)                           	True
======================================================================================================================================================
50/?       : Process [Getting Deezer ArtistIDs] Has Run For 1 Minute and 37 Seconds.
Saving 375669 (New=50) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For The Broken Harts (8751222)                        	True
Searching For Artist Info For The Waistcoats (201191)                           	True
Searching For Artist Info For Chrizz0r (5562909)                                	True
Searching For Artist Info For Silibil Sack (152495782)                          	True
Searching For Artist Info For Emmanuel Pahud-Jacky Terrasson-Ali Jackson-Sean Smith (1563430)	True
Searching For Artist Info For Noelani and The Leo Nahenahe Singers (4352103)    	True
Searching For Artist Info For Crawling Through Tartarus (104196822)             	True
Searching For Artist Info For Alex D'este Hoare (14584891)                      	True
Searching For Artist Info For Cmc Da Guttah (15065615)                          	True
Searching For Artist Info For Alas de Abril (14253615)                          	True
Searching For Artist Info For Jessica Lee Hutchings (129695912)                 	True
Searching For Artist Info For Jurek Jagoda (91755192)                           	True
Searching For Artist Info For Supa Kalm (51522392)                              	True
Searching For Artist Info For Luna meets Trilok and Chiren (2546791)            	True
Searching For Artist Info For Pushpa Pagdhare (1320590)                         	True
Searching For Artist Info For K Jah (4062100)                                   	True
Searching For Artist Info For Elektra Kurtis & Ensemble Elektra (1131595)       	True
Searching For Artist Info For Rodrigo Botter Maio (7209886)                     	True
Searching For Artist Info For The Beavers (1080419)                             	True
Searching For Artist Info For Scott B. Sympathy (132188102)                     	True
Searching For Artist Info For Dillu Taya (91159012)                             	True
Searching For Artist Info For Edouard Bineau (56590)                            	True
Searching For Artist Info For Alicen Geddes Ward (500098)                       	True
Searching For Artist Info For svrin (13870201)                                  	True
Searching For Artist Info For The Oxford Children Choir (313092)                	True
Searching For Artist Info For Uno Svenningsson and Sonja Aldén (280403)        	True
Searching For Artist Info For Solomon Silber (5820730)                          	True
Searching For Artist Info For Beat Smugglers (1050099)                          	True
Searching For Artist Info For DJ Boy Drama (4545101)                            	True
Searching For Artist Info For Dieterich Buxtehude (1603303)                     	True
Searching For Artist Info For Costi (125193722)                                 	True
Searching For Artist Info For Undisclosed Dimensions (13111203)                 	True
Searching For Artist Info For Schola Meridionalis (7969088)                     	True
Searching For Artist Info For Harry Hayes (4194698)                             	True

Searching For Artist Info For Samim Sola (5580126)                              	True
Searching For Artist Info For Meditazione musica zen institute (13355803)       	True
Searching For Artist Info For LaForte (1657410)                                 	True
Searching For Artist Info For Leonard Jones, Stephen Roach & Luke Skaggs (1140706)	True
Searching For Artist Info For Pelican Shuffles (15133315)                       	True
Searching For Artist Info For Passi Falsi (105015)                              	True
Searching For Artist Info For Trevor Watts - Veryan Weston (7981092)            	True
Searching For Artist Info For Céline Scheen (4551826)                          	True
Searching For Artist Info For WAX TESSERACT (109896912)                         	True
Searching For Artist Info For Invalid Sisters (97793602)                        	True
Searching For Artist Info For Dag Daniel (63000122)                             	True
Searching For Artist Info For Pedro Henrique (4901330)                          	True
Searching For Artist Info For The Stereotypes (UK) (13455587)                   	True
Searching For Artist Info For Lil Greenwood (325890)                            	True
Searching For Artist Info For Sir Skye (120315702)                              	True
Searching For Artist Info For Barber & James Trystan (48723091)                 	True
======================================================================================================================================================
100/?      : Process [Getting Deezer ArtistIDs] Has Run For 3 Minutes and 28 Seconds.
Saving 375719 (New=100) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Peter Lang (151930)                               	True
Searching For Artist Info For Kidda (106678282)                                 	True
Searching For Artist Info For Gilbert Grimes (55784622)                         	True
Searching For Artist Info For H. M. Irish Guards (13512615)                     	True
Searching For Artist Info For TENKI YOHO (132263992)                            	True
Searching For Artist Info For Cbalavoz (117003922)                              	True
Searching For Artist Info For Barbara & Ernie (384015)                          	True
Searching For Artist Info For Codeine Reality (13620519)                        	True
Searching For Artist Info For Ildiko Raimondi (1603900)                         	True
Searching For Artist Info For Reptile Airline (145227192)                       	True
Searching For Artist Info For Tuna De La Facul. De Farmacia De Madrid (5181115) 	True
Searching For Artist Info For Bonnie & The Little Boy Blues (1241986)           	True
Searching For Artist Info For DJ GUNDAM (8894300)                               	True
Searching For Artist Info For Hopeful Child (13837901)                          	True
Searching For Artist Info For Eos Music Group (14297009)                        	True
Searching For Artist Info For Dave Spinout (1587801)                            	True
Searching For Artist Info For Aldo Ceccato & Royal Philharmonic Orchestra (13433797)	True
Searching For Artist Info For Nor One (8120403)                                 	True
Searching For Artist Info For Just Danny Jay (107471302)                        	True
Searching For Artist Info For Drop Diver (14393903)                             	True
Searching For Artist Info For Steel Nouveau (4566815)                           	True
Searching For Artist Info For To The Grave UK (101250512)                       	True
Searching For Artist Info For Scherben (54732722)                               	True
Searching For Artist Info For Simon Sixx (13474703)                             	True
Searching For Artist Info For Hamburg Philharmonic State Orchestra (4867697)    	True
Searching For Artist Info For Cranes Tiny (126164402)                           	True
Searching For Artist Info For Perry Porter (6229330)                            	True
Searching For Artist Info For Fly Gang Reezy (112031122)                        	True
Searching For Artist Info For DJ Kleancut (5814209)                             	True
Searching For Artist Info For Sneaker Made (109349512)                          	True
Searching For Artist Info For Dubstar XL (54399192)                             	True
Searching For Artist Info For Hotel Jazz Luxus (106323502)                      	True
Searching For Artist Info For Kishori Xess (153022502)                          	True
Searching For Artist Info For Shruthi Shankar Kumar (103198402)                 	True
Searching For Artist Info For Johnny Coppin (794021)                            	True
Searching For Artist Info For Murat Coskun (3618201)                            	True
Searching For Artist Info For Kyam Letters (100972422)                          	True
Searching For Artist Info For Street Wisdom 545 (102631422)                     	True
Searching For Artist Info For TS PLETER (4872315)                               	True
Searching For Artist Info For Bridgehampton Chamber Music Festival Players (1369530)	True
Searching For Artist Info For vidnaObmana & Sam Rosenthal (4542203)             	True
Searching For Artist Info For W!LDCARD (53580402)                               	True
Searching For Artist Info For Criss BVR (14505415)                              	True
Searching For Artist Info For Antisocial Rock (87699302)                        	True
Searching For Artist Info For Maykson Herald (14721815)                         	True
Searching For Artist Info For Armageddon Monks (4479430)                        	True
Searching For Artist Info For Fantastisk Podd (10485695)                        	True
Searching For Artist Info For Ulrike J. Hofbauer (7901810)                      	True
Searching For Artist Info For Palmy (252119)                                    	True
Searching For Artist Info For Los del Aguila Real (1291621)                     	True
======================================================================================================================================================
150/?      : Process [Getting Deezer ArtistIDs] Has Run For 5 Minutes and 12 Seconds.
Saving 375769 (New=150) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Niko Deejay (347619)                              	True
Searching For Artist Info For Lost Without Life (14771203)                      	True
Searching For Artist Info For Florian Poser Group (134696)                      	True
Searching For Artist Info For Slowly Slowly (9865730)                           	True
Searching For Artist Info For Sergei Rachmaninoff, Philadelphia Orchestra And Leopold Stokowski (372926)	True
Searching For Artist Info For Bernard Herrmann Orchestra (1379721)              	True
Searching For Artist Info For Groves Thesis (114285702)                         	True
Searching For Artist Info For Xray Dress (134540222)                            	True
Searching For Artist Info For Fat Acid Drop (66830292)                          	True
Searching For Artist Info For The Disco Brothers (7790)                         	True
Searching For Artist Info For José Evangelista (2015621)                       	True
Searching For Artist Info For Nature Devotion Soothing Music (97970222)         	True
Searching For Artist Info For Abu Bokor Siddiki (9503626)                       	True
Searching For Artist Info For Patrícia & Adriana (495691)                      	True
Searching For Artist Info For SAVEJ (5635515)                                   	True
Searching For Artist Info For Soul Sinners (1053309)                            	True
Searching For Artist Info For The Former Hasbeens (150295802)                   	True
Searching For Artist Info For Sweet Dreams Baby Brown Noise (101446522)         	True

Searching For Artist Info For Atlantic Rising featuring Sky Sunlight Saxon and Demetrius (6240612)	True
Searching For Artist Info For Beres Hammond & Zap Pow (253190)                  	True
Searching For Artist Info For Joanna Jordan (1323810)                           	True
Searching For Artist Info For Anji Tan (155813602)                              	True
Searching For Artist Info For Ben Bowen (5342515)                               	True
Searching For Artist Info For Samo Salamon Bassless Trio (7262412)              	True
Searching For Artist Info For The Rocktigers (78709222)                         	True
Searching For Artist Info For Lazys THE (4562830)                               	True
Searching For Artist Info For Eye of the Dawn (5182686)                         	True
Searching For Artist Info For Worldwide Epidemic (6310530)                      	True
Searching For Artist Info For Bessi (5360710)                                   	True
Searching For Artist Info For Reset Preset (8823810)                            	True
Searching For Artist Info For NAOITO - dotA (85556122)                          	True
Searching For Artist Info For Envotion feat. Misia Furtak (440197)              	True
Searching For Artist Info For Ricci Paolo (100150792)                           	True
Searching For Artist Info For Ransom Highlyfe (50458322)                        	True
Searching For Artist Info For DJ Makuil (1533293)                               	True
Searching For Artist Info For Meditation Fields (111279122)                     	True
Searching For Artist Info For Del Giudice & Toso (51489992)                     	True
Searching For Artist Info For Ant & Nick Grater (8804500)                       	True
Searching For Artist Info For Lone Dolphin (5407230)                            	True
Searching For Artist Info For Asin Kuroda (5616809)                             	True
Searching For Artist Info For Dapanji (1208919)                                 	True
Searching For Artist Info For J.H. Speenhoff (4494130)                          	True
Searching For Artist Info For Lanes (106799)                                    	True
Searching For Artist Info For AM Radio Hits (53149202)                          	True
Searching For Artist Info For Favio Donoban (109646122)                         	True
Searching For Artist Info For Bats in the Belfry (1050312)                      	True
Searching For Artist Info For Angus Mohr (5208596)                              	True
Searching For Artist Info For Paul Anthony Blanchard (80132622)                 	True
Searching For Artist Info For Signum Void (148361212)                           	True
Searching For Artist Info For Big Boy Mar (5061110)                             	True
======================================================================================================================================================
200/?      : Process [Getting Deezer ArtistIDs] Has Run For 7 Minutes and 21 Seconds.
Saving 375819 (New=200) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For John Edward Croker (6856795)                      	True
Searching For Artist Info For headless giantess (133130092)                     	True
Searching For Artist Info For On:Stop:Off (9755022)                             	True
Searching For Artist Info For Akim Ahmad (12912815)                             	True
Searching For Artist Info For Markus Schulz & Dennis Sheperd (1723301)          	True
Searching For Artist Info For Tomoya Wadnaxx (83014322)                         	True
Searching For Artist Info For La Mêlée (13834419)                             	True
Searching For Artist Info For Noble Sissle & His Orchestra (1057022)            	True
Searching For Artist Info For Uzzi On The Beatz (113272412)                     	True
Searching For Artist Info For SANCTUM INK (57517922)                            	True
Searching For Artist Info For Menace II Society (5264503)                       	True
Searching For Artist Info For KF Sare (52779392)                                	True
Searching For Artist Info For Bedroom Getaway (58210802)                        	True
Searching For Artist Info For Cyril J. Mockridge (5241209)                      	True
Searching For Artist Info For Ligeia's Cadence (9940284)                        	True
Searching For Artist Info For James Fagan (396300)                              	True
Searching For Artist Info For Bedroom Surfer (1213802)                          	True
Searching For Artist Info For Miguel Nogueira (5494426)                         	True
Searching For Artist Info For Bedroom Music Joy (101399802)                     	True
Searching For Artist Info For H.R (5256709)                                     	True
Searching For Artist Info For Goodie Mob Presents The Lumberjacks (4585796)     	True
Searching For Artist Info For Patricia (70790522)                               	True
Searching For Artist Info For Late Nite Snacks (5172287)                        	True
Searching For Artist Info For Trío Sine Nomine (9505096)                       	True
Searching For Artist Info For Fly Montag (103178422)                            	True
Searching For Artist Info For Yoga Music (1062130)                              	True
Searching For Artist Info For Old Sap (10383788)                                	True
Searching For Artist Info For heartbeat learning (153458492)                    	True
Searching For Artist Info For Louis Durey (1260903)                             	True
Searching For Artist Info For Yimmi La Melodia (7413626)                        	True
Searching For Artist Info For India Map (63968612)                              	True
Searching For Artist Info For WSR Redd (156245892)                              	True
Searching For Artist Info For Fanny Solter, Martin Ostertag (196088)            	True
Searching For Artist Info For Inder Sekhon (6690603)                            	True
Searching For Artist Info For DJ Giuseppe Caruso (9002188)                      	True
Searching For Artist Info For 101 Strings Orchestra, Willy Freivogel, Flute,Hans Kalafusz, Violin,Walter Henschel, Viola (4956415)	True
Searching For Artist Info For Brass Ensemble (419895)                           	True
Searching For Artist Info For Dave El Hiphop Junkie & Sean Borne (4595315)      	True
Searching For Artist Info For King Kalm (141439982)                             	True
Searching For Artist Info For CODEX 404 (150419922)                             	True
Searching For Artist Info For Porno Ticket (14656795)                           	True
Searching For Artist Info For Eva Maria Y Su Grupo (10032690)                   	True
Searching For Artist Info For Alex Goot feat. Luke Conard & Chad Sugg (5506815) 	True
Searching For Artist Info For Stxkz (12687915)                                  	True
Searching For Artist Info For Tong & Rogers (499309)                            	True
Searching For Artist Info For Manux (56621722)                                  	True
Searching For Artist Info For Rachel Parkinson's Little Feet Music (13126891)   	True
Searching For Artist Info For Alter Ego (58475022)                              	True
Searching For Artist Info For Epic Fun Club (6829415)                           	True
Searching For Artist Info For Brazen P (8653590)                                	True
======================================================================================================================================================
250/?      : Process [Getting Deezer ArtistIDs] Has Run For 9 Minutes and 4 Seconds.
Saving 375869 (New=250) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Jay Glo (54570492)                                	True
Searching For Artist Info For Anima (120526422)                                 	True

Searching For Artist Info For Ved Vyasa (7363898)                               	True
Searching For Artist Info For TUKAN HA (71799812)                               	True
Searching For Artist Info For Jorge Duran y Exodo (13843109)                    	True
Searching For Artist Info For Amiah (6048298)                                   	True
Searching For Artist Info For Barricades (123001022)                            	True
Searching For Artist Info For Sweet Jazz Popeye (1675530)                       	True
Searching For Artist Info For The Cinema Twin (2137791)                         	True
Searching For Artist Info For Connie Kissinger (4577209)                        	True
Searching For Artist Info For Folk' Avant (12191322)                            	True
Searching For Artist Info For Wild Roses Of Winter (84553792)                   	True
Searching For Artist Info For Parallel Release (5725430)                        	True
Searching For Artist Info For Dag Gabrielsen (112025692)                        	True
Searching For Artist Info For Lesly Gore (11523415)                             	True
Searching For Artist Info For Maribel Soto (10071830)                           	True
Searching For Artist Info For Misha Panfilov (14741115)                         	True
Searching For Artist Info For Cherub Tree (132806322)                           	True
Searching For Artist Info For Robert Warren Stephens (15262603)                 	True
Searching For Artist Info For Participants of 'My Jerusalem' (15016609)         	True
Searching For Artist Info For Nosizwe (4392086)                                 	True
Searching For Artist Info For Neal & the Vipers (15161891)                      	True
Searching For Artist Info For Small Pyramids (1459626)                          	True
Searching For Artist Info For Bennett Holland (4510503)                         	True
Searching For Artist Info For H Justini (4331903)                               	True
Searching For Artist Info For Clarence Parks (1345303)                          	True
Searching For Artist Info For Heir Tsar (127991522)                             	True
Searching For Artist Info For Jonathan & the Dead King (14834909)               	True
Searching For Artist Info For The Beulah Band (5540502)                         	True
Searching For Artist Info For Janna Eva (154264082)                             	True
Searching For Artist Info For Dust & the Dukes (14140619)                       	True
Searching For Artist Info For Kontac & Erase E (1133006)                        	True
Searching For Artist Info For Portland Metro Pipe Band (1025809)                	True
Searching For Artist Info For Cali Project (127993122)                          	True
Searching For Artist Info For Spyra (400515)                                    	True
Searching For Artist Info For Thomas Griesser & Friends (7724988)               	True
Searching For Artist Info For Stockholms Filharmoniska Orkester-Per Olof Gillblad-Ulf Björlin (1506399)	True
Searching For Artist Info For Junky Mailer (145241122)                          	True
Searching For Artist Info For Paavo Järvi-Stockholms Filharmoniska Orkester (1416599)	True
Searching For Artist Info For Koinonia Music (13922715)                         	True
Searching For Artist Info For Frankie Feliciano & Real Thing (91491592)         	True
Searching For Artist Info For Austin Clark (4650315)                            	True
Searching For Artist Info For Frank McComb Quartet (60177802)                   	True
Searching For Artist Info For Dj Exte C (4802996)                               	True
Searching For Artist Info For Muzarco (383522)                                  	True
Searching For Artist Info For Angel de Lux (4373226)                            	True
Searching For Artist Info For Phase O'Matic (81387022)                          	True
Searching For Artist Info For Mr. Matty Moses (77307702)                        	True
Searching For Artist Info For Ho Yip KU (146837912)                             	True
Searching For Artist Info For Sleep Star Ignition (5521215)                     	True
======================================================================================================================================================
300/?      : Process [Getting Deezer ArtistIDs] Has Run For 10 Minutes and 58 Seconds.
Saving 375919 (New=300) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Gone in the Sun (7629190)                         	True
Searching For Artist Info For The Secession (4951488)                           	True
Searching For Artist Info For Talisman P (2302691)                              	True
Searching For Artist Info For Bored Men (5573030)                               	True
Searching For Artist Info For Omi (7896730)                                     	True
Searching For Artist Info For Gasman (335809)                                   	True
Searching For Artist Info For LTJ-Xperience (145330)                            	True
Searching For Artist Info For Lune De Miel (86530)                              	True
Searching For Artist Info For V Twin (151511922)                                	True
Searching For Artist Info For Dame Emma Kirkby-Charles Medlam (1468615)         	True
Searching For Artist Info For Space Cowboy Ali (141919112)                      	True
Searching For Artist Info For Duke & Gonzo (14804603)                           	True
Searching For Artist Info For West and Skyward (125777692)                      	True
Searching For Artist Info For Kali Mutsa & Imaabs (12722887)                    	True
Searching For Artist Info For Taran Sandhu (57720592)                           	True
Searching For Artist Info For Billy The Kicks (102494922)                       	True
Searching For Artist Info For Shizzle (117909112)                               	True
Searching For Artist Info For A.C. Slater (399130)                              	True
Searching For Artist Info For Rikki Ililonga (1456406)                          	True
Searching For Artist Info For Mikael Weermets & Audible feat. Max C (1650584)   	True
Searching For Artist Info For Parish (87003)                                    	True
Searching For Artist Info For Darbuka Siva (8831690)                            	True
Searching For Artist Info For Captain Capa (328100)                             	True
Searching For Artist Info For Calvertron & Qalvr (1220215)                      	True
Searching For Artist Info For Sixten Ehrling, Nicolai Gedda & Stockholm Royal Court Orchestra (75812612)	True
Searching For Artist Info For Carlo Guelfi-London Symphony Orchestra-Antonio Pappano (1482800)	True
Searching For Artist Info For Pardinho & Pardal (1461391)                       	True
Searching For Artist Info For Purple Pam and the Flesh Eaters (9422630)         	True
Searching For Artist Info For Creep Division (167197)                           	True
Searching For Artist Info For Fontaine James (5386615)                          	True
Searching For Artist Info For Tewy (107780482)                                  	True
Searching For Artist Info For Aurora & Bruce BecVar (4459088)                   	True
Searching For Artist Info For David Friedman and Jasper Van't Hof (119490)      	True
Searching For Artist Info For illion (4414791)                                  	True
Searching For Artist Info For Mark Mellow (97740582)                            	True
Searching For Artist Info For Danny Lightyear (13822615)                        	True
Searching For Artist Info For Soshy (271299)                                    	True
Searching For Artist Info For The Rive Project (10727291)                       	True
Searching For Artist Info For Julian Abbott (13291493)                          	True
Searching For Artist Info For Pedro Garcia Y Su Arsenal (8903286)               	True
Searching For Artist Info For Seasons in Wreckage (5367609)                     	True

Searching For Artist Info For Hoàng Kim - Lâm Dũng (88180622)                	True
Searching For Artist Info For Zahir Ensemble (1637503)                          	True
Searching For Artist Info For Jeffrey Tate & English Chamber Orchestra (13434315)	True
Searching For Artist Info For Orchester Friedel Wende (13180015)                	True
Searching For Artist Info For The Pick Up (1175891)                             	True
Searching For Artist Info For Dorso Duro (151186702)                            	True
Searching For Artist Info For Sobasedprimo (132086212)                          	True
Searching For Artist Info For Anima II (107944522)                              	True
Searching For Artist Info For Bo Hill (8039815)                                 	True
======================================================================================================================================================
350/?      : Process [Getting Deezer ArtistIDs] Has Run For 12 Minutes and 49 Seconds.
Saving 375969 (New=350) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Joanna Halszka Sokołowska (8824888)               	True
Searching For Artist Info For Tarmac Jones (50382312)                           	True
Searching For Artist Info For Suspect 44 (1578403)                              	True
Searching For Artist Info For Poke (94548012)                                   	True
Searching For Artist Info For Big Sly (97072382)                                	True
Searching For Artist Info For William Beauvais (1708202)                        	True
Searching For Artist Info For Fme Tavo (15102209)                               	True
Searching For Artist Info For They Say Jump (1207506)                           	True
Searching For Artist Info For Bou Craa (2651791)                                	True
Searching For Artist Info For Tumbleweed Hill (108483792)                       	True
Searching For Artist Info For GTS J San (74929002)                              	True
Searching For Artist Info For The Singers Unlimited with The Pat Williams Orchestra (51502192)	True
Searching For Artist Info For Markus Schulz with Elevation & KhoMha (3894091)   	True
Searching For Artist Info For Johnny Alegre Affinity (1220719)                  	True
Searching For Artist Info For Sudden Waves (15010315)                           	True
Searching For Artist Info For Marcie O'neil (6146606)                           	True
Searching For Artist Info For Tobax & Innersoul (4034209)                       	True
Searching For Artist Info For Arson Wayne (81937022)                            	True
Searching For Artist Info For Lil Jermaine (95707022)                           	True
Searching For Artist Info For Micky Day (4532426)                               	True
Searching For Artist Info For Mark Crawford Williams (1121309)                  	True
Searching For Artist Info For DAE Glo (115018902)                               	True
Searching For Artist Info For John Hassall & The April Rainers (11107090)       	True
Searching For Artist Info For Hive (79566302)                                   	True
Searching For Artist Info For Miguel Calo Y Su Orquesta (1235815)               	True
Searching For Artist Info For Gav Whitehouse (5482309)                          	True
Searching For Artist Info For Seija Härkönen (5269199)                        	True
Searching For Artist Info For Felix Weaver (53189122)                           	True
Searching For Artist Info For Hujan Badai (12637091)                            	True
Searching For Artist Info For Dave Shokh And Holgi Star (2366391)               	True
Searching For Artist Info For LINE X OUT (98514922)                             	True
Searching For Artist Info For Ошибка 707 (67251302)                             	True
Searching For Artist Info For The Metronome All-Stars (77909)                   	True
Searching For Artist Info For Ripple Effect (887715)                            	True
Searching For Artist Info For Yu Bin (8806800)                                  	True
Searching For Artist Info For Septiembre XIX (57872422)                         	True
Searching For Artist Info For Dj John Garcia, Luis Caballero (1214187)          	True
Searching For Artist Info For Psyclones (481609)                                	True
Searching For Artist Info For Edelweiss Quartet (11861909)                      	True
Searching For Artist Info For Cronos Feminist (62274002)                        	True
Searching For Artist Info For Squadron 40 (15269015)                            	True
Searching For Artist Info For Dancehall IG (49215992)                           	True
Searching For Artist Info For Mc Naay (86723902)                                	True
Searching For Artist Info For Marcos Tsessos (5170798)                          	True
Searching For Artist Info For Jed & Hera (4588699)                              	True
Searching For Artist Info For Kevinho MC (15198695)                             	True
Searching For Artist Info For os sons de Löis Lancaster (97013512)             	True
Searching For Artist Info For Decoy Zae (101838012)                             	True
Searching For Artist Info For sk95 (603915)                                     	True
Searching For Artist Info For Raul Mezcolanza and Bob D (1030615)               	True
======================================================================================================================================================
400/?      : Process [Getting Deezer ArtistIDs] Has Run For 14 Minutes and 30 Seconds.
Saving 376019 (New=400) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Brilliant (147909)                                	True
Searching For Artist Info For Cantaores y Orquesta de pulso y pua (G.E.S) (1219203)	True
Searching For Artist Info For Clarence Clemons (83400)                          	True
Searching For Artist Info For Diego Martínez "Mestizo" (9523530)               	True
Searching For Artist Info For Rohaan Bleu (110551722)                           	True
Searching For Artist Info For Tom Erich (4509397)                               	True
Searching For Artist Info For Gabriel & His Trumpet (3172791)                   	True
Searching For Artist Info For Daemon Poetica (139477202)                        	True
Searching For Artist Info For Claud 9 (127702)                                  	True
Searching For Artist Info For Sebastian A. Deadskin (14628515)                  	True
Searching For Artist Info For Amanda Pryce (5393109)                            	True
Searching For Artist Info For Johnny O (117704192)                              	True
Searching For Artist Info For Naw Tula Min (73204322)                           	True
Searching For Artist Info For Dj Jack Russell (61622512)                        	True
Searching For Artist Info For Phil Nico with Benton Bohannon (5813296)          	True
Searching For Artist Info For Flamenco Sketch (14550409)                        	True
Searching For Artist Info For Ammy Joldersma (9184796)                          	True
Searching For Artist Info For Rack Mane (64010122)                              	True
Searching For Artist Info For Rudra Vena (5524590)                              	True
Searching For Artist Info For Daniel Diego (5140219)                            	True
Searching For Artist Info For Fran Ray (7572706)                                	True
Searching For Artist Info For MAHO-Do(Doremi:Chiemi Chiba, Hazuki:Tomoko Akiya, Aiko:Yuki Matsuoka, Ompu:Rumi Shishido, Momoko:Nami Miyahara, Hanachan:Ikue Otani) (112798992)	True
Searching For Artist Info For הצ'רצ'ילים (72124502)                             	True
Searching For Artist Info For BRUV REEK (92916222)                              	True

Searching For Artist Info For Señorita Chu (90538602)                          	True
Searching For Artist Info For Yvonne Fair & The James Brown Band (7800522)      	True
Searching For Artist Info For Richard Maranda (1317799)                         	True
Searching For Artist Info For JNO (4074695)                                     	True
Searching For Artist Info For Molasses Jones (8878798)                          	True
Searching For Artist Info For G2 Rizz (100860712)                               	True
Searching For Artist Info For Jack Benassi (4733230)                            	True
Searching For Artist Info For Dads in the Park (68316602)                       	True
Searching For Artist Info For Gotham Dischi (153320392)                         	True
Searching For Artist Info For Mary Halvorson-Weasel Walter-Peter Evans (9076686)	True
Searching For Artist Info For Scott Dingler Review (6932909)                    	True
Searching For Artist Info For David Panda (1669584)                             	True
Searching For Artist Info For Filiph (58089992)                                 	True
Searching For Artist Info For Kray Twinz (5608703)                              	True
Searching For Artist Info For Fis'Ko (10405112)                                 	True
Searching For Artist Info For Alberto Merino (5894597)                          	True
Searching For Artist Info For Sergej Komov (458803)                             	True
Searching For Artist Info For King-Jay (14893803)                               	True
Searching For Artist Info For Kelly Sweet (15897)                               	True
Searching For Artist Info For The Notion (1109801)                              	True
Searching For Artist Info For New Clear (108557182)                             	True
Searching For Artist Info For Hauvy (69698992)                                  	True
Searching For Artist Info For Out of Hand (8939590)                             	True
Searching For Artist Info For Christmas Jazz (1009386)                          	True
Searching For Artist Info For Saul Rose (417130)                                	True
Searching For Artist Info For Ese Nando & Dj Stigma (13973299)                  	True
======================================================================================================================================================
450/?      : Process [Getting Deezer ArtistIDs] Has Run For 16 Minutes and 19 Seconds.
Saving 376069 (New=450) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Mario Suarez (1041815)                            	True
Searching For Artist Info For Randolph Rose & Margit Anderson (208126)          	True
Searching For Artist Info For Rat Silo (1102030)                                	True
Searching For Artist Info For Adani (5203903)                                   	True
Searching For Artist Info For Three Dirty Souls (129458182)                     	True
Searching For Artist Info For DJ Crown (91830)                                  	True
Searching For Artist Info For Gold Geisha (54209922)                            	True
Searching For Artist Info For Djalma Ferreira e seus Milionários do Ritmo (7681726)	True
Searching For Artist Info For Currende Consort (3718691)                        	True
Searching For Artist Info For Sak Noel & Los Tioz (12651301)                    	True
Searching For Artist Info For Jozif Santana (72980022)                          	True
Searching For Artist Info For Forever Young (139275802)                         	True
Searching For Artist Info For Pr Gervais Mendo Zé (15176119)                   	True
Searching For Artist Info For Jeey Rodriguez (93053322)                         	True
Searching For Artist Info For Seong-Jin Cho, Jacek Kaspszyk, Warsaw Philharmonic Orchestra (53188322)	True
Searching For Artist Info For Skanks The Rap Martyr (8953986)                   	True
Searching For Artist Info For Past Inhale (144942602)                           	True
Searching For Artist Info For Francesco Molinari-Pradelli (454219)              	True
Searching For Artist Info For Sir Antoine (1090503)                             	True
Searching For Artist Info For Räck Mej En Hand Min Vän (126246722)            	True
Searching For Artist Info For Nucleus Torn (1681115)                            	True
Searching For Artist Info For Chris Howland & Leon Blaq (13452709)              	True
Searching For Artist Info For secret webcam Girl (77660112)                     	True
Searching For Artist Info For Bradley Grant (108750792)                         	True
Searching For Artist Info For Bablo T (119556412)                               	True
Searching For Artist Info For Sammy Ward (161830)                               	True
Searching For Artist Info For JR Tycoon (7969286)                               	True
Searching For Artist Info For Wasabi Boiz (7892286)                             	True
Searching For Artist Info For Tim Neumann aka Lunatic (89661002)                	True
Searching For Artist Info For Charles Vald (3197301)                            	True
Searching For Artist Info For Death Decayed (12831715)                          	True
Searching For Artist Info For Tönu Kaljuste, Kaia Urb & Tiit Kogerman (64568922)	True
Searching For Artist Info For Erel (5563609)                                    	True
Searching For Artist Info For Le syndicat du grim (342297)                      	True
Searching For Artist Info For 33 EWE (146750592)                                	True
Searching For Artist Info For Ara Malikian. Jesús Amigo. Extremadura Symphony Orchestra (347106)	True
Searching For Artist Info For Smack (114379922)                                 	True
Searching For Artist Info For Talenti Vulcanici (12140188)                      	True
Searching For Artist Info For Fabiano Maniero, Silvio Celeghin & Silvia Calzavara (126015)	True
Searching For Artist Info For System'e' (1447915)                               	True
Searching For Artist Info For Freshly Ground (14715)                            	True
Searching For Artist Info For Davidson Ospina Presents Henderson (1303598)      	True
Searching For Artist Info For Xander James (4674215)                            	True
Searching For Artist Info For Weevil (4339709)                                  	True
Searching For Artist Info For Seven Knives (14081503)                           	True
Searching For Artist Info For Josephine Philip (4602030)                        	True
Searching For Artist Info For Østkyst Hustlers (457926)                         	True
Searching For Artist Info For Andén 16 (98351512)                              	True
Searching For Artist Info For Parashurama Thimmapura (123693022)                	True
Searching For Artist Info For Janson Grandmother (82705902)                     	True
======================================================================================================================================================
500/?      : Process [Getting Deezer ArtistIDs] Has Run For 18 Minutes and 6 Seconds.
Saving 376119 (New=500) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Amaya Ltd. Síndrome (348530)                     	True
Searching For Artist Info For Paul Anastasio (3053401)                          	True
Searching For Artist Info For Kap Slap (7423212)                                	True
Searching For Artist Info For Jarrus G (Da M.V.P) (812903)                      	True
Searching For Artist Info For Ewe Dre (83181492)                                	True
Searching For Artist Info For La Armónica Invisible (1338309)                  	True
Searching For Artist Info For Anish Cherian (100724522)                         	True
Searching For Artist Info For Ritchie Everett (64282222)                        	True
Searching For Artist Info For Soul Civilian (70343692)                          	True

Searching For Artist Info For Behind This Guilt (114853782)                     	True
Searching For Artist Info For Grace O'Malley Quartet (6222688)                  	True
Searching For Artist Info For Erotic Vagrancy (1465091)                         	True
Searching For Artist Info For Dj Bolo Crack (72048392)                          	True
Searching For Artist Info For Perry Kills (1651492)                             	True
Searching For Artist Info For Hellboozer Union (351106)                         	True
Searching For Artist Info For Phils Boogaloo (1656412)                          	True
Searching For Artist Info For Diseize84 (71618222)                              	True
Searching For Artist Info For B Poz (77413722)                                  	True
Searching For Artist Info For MoHa! (1020615)                                   	True
Searching For Artist Info For Deep Night Beats (7014215)                        	True
Searching For Artist Info For Gabriel Amargant (7407612)                        	True
Searching For Artist Info For Jazz Sigala (1391809)                             	True
Searching For Artist Info For FaZe Rug (78254582)                               	True
Searching For Artist Info For Tagubu (5508297)                                  	True
Searching For Artist Info For Ga Froze (125577902)                              	True
Searching For Artist Info For Tommie Sewón (1707503)                           	True
Searching For Artist Info For Viking Priests (15220015)                         	True
Searching For Artist Info For Richard Vaughan Thomas-Bournemouth Symphony Orchestra-Andrew Litton (1503526)	True
Searching For Artist Info For Blackthorn (113596012)                            	True
Searching For Artist Info For Rudi Terzett Schuricke (1198203)                  	True
Searching For Artist Info For Electric Treasure (6883601)                       	True
Searching For Artist Info For Mert Eylem (10120906)                             	True
Searching For Artist Info For Mighty Cadence (5297586)                          	True
Searching For Artist Info For Furio Rendine (4455209)                           	True
Searching For Artist Info For Toussy Thalassa (6536709)                         	True
Searching For Artist Info For Fat Bald Turk (14999719)                          	True
Searching For Artist Info For Ronnie Earl, Pinetop Perkins, Calvin "Fuzz" Jones", Willie "Big Eyes" Smith (1687522)	True
Searching For Artist Info For C. Keys Stallings (114245092)                     	True
Searching For Artist Info For Alton Frown (13542797)                            	True
Searching For Artist Info For Komputer Kid (92063822)                           	True
Searching For Artist Info For Grim's (124813982)                                	True
Searching For Artist Info For Buckboard Bill Dougal (6254492)                   	True
Searching For Artist Info For The Sea Shall Not Have Them (1405499)             	True
Searching For Artist Info For Pierre-Alex Favriel feat. Ginnie Watson (262093)  	True
Searching For Artist Info For DJ Gazzo OFICIAL (121230982)                      	True
Searching For Artist Info For Mic Bles (4015730)                                	True
Searching For Artist Info For Barry Gibb (15500)                                	True
Searching For Artist Info For Sir David Willcocks, Heather Harper, Robert Tear, Academy Of St. Martin-In-The-Fields & Choir of King's College, Cambridge (53327612)	True
Searching For Artist Info For Spike and Tyla's Hot Knives (10865586)            	True
Searching For Artist Info For Aka Jere (55217822)                               	True
======================================================================================================================================================
550/?      : Process [Getting Deezer ArtistIDs] Has Run For 19 Minutes and 50 Seconds.
Saving 376169 (New=550) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For m!co (15343895)                                   	True
Searching For Artist Info For Reuben Hoch (1114188)                             	True
Searching For Artist Info For Rebecka Karlsson (801091)                         	True
Searching For Artist Info For DEATH BY BONG (15107195)                          	True
Searching For Artist Info For Kostas Milonas (1011303)                          	True
Searching For Artist Info For Catherine Patriasz (4571530)                      	True
Searching For Artist Info For Persona Non Grata & Emmanuel K (4622391)          	True
Searching For Artist Info For island Trap (49010501)                            	True
Searching For Artist Info For Meditation Bol (53645202)                         	True
Searching For Artist Info For Rita Paul & das Cornel-Trio (616593)              	True
Searching For Artist Info For Patrick Grau (853626)                             	True
Searching For Artist Info For C-BooL feat. Ricardo Munoz (6001296)              	True
Searching For Artist Info For Cluj-Napoca Philharmonic Orchestra (4797203)      	True
Searching For Artist Info For Morgan Evans (1564010)                            	True
Searching For Artist Info For Elro (1427386)                                    	True
Searching For Artist Info For Frede Fuego (13472015)                            	True
Searching For Artist Info For Me & Mauve (93344692)                             	True
Searching For Artist Info For Brian T. Kennedy (151410512)                      	True
Searching For Artist Info For Guin El Titanium (132763382)                      	True
Searching For Artist Info For Dave Ness Trio (4845630)                          	True
Searching For Artist Info For Hossein Omoumi (1394890)                          	True
Searching For Artist Info For Meng Jia (11433812)                               	True
Searching For Artist Info For The Everlost (14738115)                           	True
Searching For Artist Info For Sam Ecoff,Eliot Pulse (12559006)                  	True
Searching For Artist Info For Anem Amar (8888492)                               	True
Searching For Artist Info For The Kids From "Fame" (71226)                      	True
Searching For Artist Info For Yung Jefe (10448706)                              	True
Searching For Artist Info For Kojo Trip (54429092)                              	True
Searching For Artist Info For LORDE FARRA (129003792)                           	True
Searching For Artist Info For Celestial Noise (143650822)                       	True
Searching For Artist Info For Artur Rodzinski (1384603)                         	True
Searching For Artist Info For Barry P. Foley (902730)                           	True
Searching For Artist Info For OTR Flipper (116478502)                           	True
Searching For Artist Info For Axxa - Abraxas (62498522)                         	True
Searching For Artist Info For Psykick Holiday (1287130)                         	True
Searching For Artist Info For Thunder Company (4236087)                         	True
Searching For Artist Info For MaríA Isabel (70778422)                          	True
Searching For Artist Info For Fierce Heart (6987203)                            	True
Searching For Artist Info For Garrison Cade (12233086)                          	True
Searching For Artist Info For Ama Deus Ensemble, Valentin Radu & Julianne Baird (5367410)	True
Searching For Artist Info For Regina Liima (66175402)                           	True
Searching For Artist Info For Joe Dean (198196)                                 	True
Searching For Artist Info For Raul Araya (712286)                               	True
Searching For Artist Info For Ville Virtanen (1483515)                          	True
Searching For Artist Info For Renaud Louis-Servais Group (1348619)              	True
Searching For Artist Info For Bill Shanahan (8372182)                           	True
Searching For Artist Info For Scott Toner (4994915)                             	True

Searching For Artist Info For Fiamma Albieri (85957322)                         	True
Searching For Artist Info For Matrix Next Level (12806119)                      	True
Searching For Artist Info For Carl Story and his Rambling Mountaineers (1333884)	True
======================================================================================================================================================
600/?      : Process [Getting Deezer ArtistIDs] Has Run For 21 Minutes and 33 Seconds.
Saving 376219 (New=600) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Jimmy Sax Black (106103992)                       	True
Searching For Artist Info For FLaMi La FiaMma (120662422)                       	True
Searching For Artist Info For Smokey "Bubblin" B (1367530)                      	True
Searching For Artist Info For Zubin (78520422)                                  	True
Searching For Artist Info For Saad Hunny (6736903)                              	True
Searching For Artist Info For Metronome DJ's (80346292)                         	True
Searching For Artist Info For MC ENSITE (115335392)                             	True
Searching For Artist Info For Break The Basics (142146922)                      	True
Searching For Artist Info For Tom Sonntag (10344206)                            	True
Searching For Artist Info For Magda Ianculescu (7070415)                        	True
Searching For Artist Info For John Lake (4750030)                               	True
Searching For Artist Info For Gypsy - Lisa Kirk (192303)                        	True
Searching For Artist Info For Alex Goot feat. Against The Current (5506819)     	True
Searching For Artist Info For Homero Espinosa, Tobirus Mozelle (8976726)        	True
Searching For Artist Info For Lionel Hampton Septet (489430)                    	True
Searching For Artist Info For Da Rook Mc (4914522)                              	True
Searching For Artist Info For Alexandre Scriabine (1617786)                     	True
Searching For Artist Info For Bart B More (361496)                              	True
Searching For Artist Info For Kahta Doe (111004622)                             	True
Searching For Artist Info For Faceless Brazil (51207622)                        	True
Searching For Artist Info For A.Sihe (5317006)                                  	True
Searching For Artist Info For Lilith Nigel (147316992)                          	True
Searching For Artist Info For Prospa ONE (106948302)                            	True
Searching For Artist Info For Terry Raze (5000815)                              	True
Searching For Artist Info For Piano Bar Music Guys (7835384)                    	True
Searching For Artist Info For Den,Noia (125212002)                              	True
Searching For Artist Info For Ka$h Route (1517710)                              	True
Searching For Artist Info For David Wenngren (1682003)                          	True
Searching For Artist Info For Katsuhiko Katagiri (85431222)                     	True
Searching For Artist Info For Fire Up the Coals (11063026)                      	True
Searching For Artist Info For Komodo Fox (61833122)                             	True
Searching For Artist Info For Mark Duel (1055191)                               	True
Searching For Artist Info For Sarius - Voskovy - W.E.N.A. (11961387)            	True
Searching For Artist Info For Berlin Staatskapelle, Heinz Fricke, Siegfried Lorenz (4090788)	True
Searching For Artist Info For Paul Meyers Quartet (1289810)                     	True
Searching For Artist Info For Lofi Beats Bandit (78610222)                      	True
Searching For Artist Info For A'Danté Moris (58357802)                         	True
Searching For Artist Info For Alexia Gardner (4652092)                          	True
Searching For Artist Info For Satin Fangs (124959112)                           	True
Searching For Artist Info For Lavish Aj (100482222)                             	True
Searching For Artist Info For Dougal Lacey (72576612)                           	True
Searching For Artist Info For T Herron The T.I.T.A.N. (145724212)               	True
Searching For Artist Info For The Crystal Project (67545722)                    	True
Searching For Artist Info For Adix Gleb (138469012)                             	True
Searching For Artist Info For gleb filipchenkow (121604712)                     	True
Searching For Artist Info For Lethal Bizzle feat. Ruby Goe (5098386)            	True
Searching For Artist Info For James Pendleton (62655292)                        	True
Searching For Artist Info For Versus Angels (4045793)                           	True
Searching For Artist Info For Freaky B 2.0 (14168815)                           	True
Searching For Artist Info For New Flesh (60195)                                 	True
======================================================================================================================================================
650/?      : Process [Getting Deezer ArtistIDs] Has Run For 23 Minutes and 17 Seconds.
Saving 376269 (New=650) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Pasto Slither (132746802)                         	True
Searching For Artist Info For ECID (390010)                                     	True
Searching For Artist Info For Damian Flyte (82282412)                           	True
Searching For Artist Info For Richie Feelings & Tony Matterhorn (584630)        	True
Searching For Artist Info For Ruan Gloss (6801315)                              	True
Searching For Artist Info For Flint J (5404815)                                 	True
Searching For Artist Info For Paulo Junior (4030115)                            	True
Searching For Artist Info For Hella Fella (61599222)                            	True
Searching For Artist Info For John Wetton (201896)                              	True
Searching For Artist Info For Mental Droid (5499415)                            	True
Searching For Artist Info For The Southern Collective (6445400)                 	True
Searching For Artist Info For Radu Gi (110416812)                               	True
Searching For Artist Info For Bob Delevante Feat. Garry Tallent (2367791)       	True
Searching For Artist Info For Wunder (66288)                                    	True
Searching For Artist Info For Eiddwen Harrhy-City of London Baroque Sinfonia-Simon Standage-Ian Watson-John Heley-Dorothy Linell-Richard Hickox (1471110)	True
Searching For Artist Info For Diego Solan (147599402)                           	True
Searching For Artist Info For The Immolation Scene (149211412)                  	True
Searching For Artist Info For Carlo Bergonzi - Gianandrea Gavazzeni - Orchestra of the Accademia di Santa Cecilia (1559315)	True
Searching For Artist Info For B-Polar (4951691)                                 	True
Searching For Artist Info For Domani Martina (135177722)                        	True
Searching For Artist Info For Richard Thomas Band (12886497)                    	True
Searching For Artist Info For EMIRYBLACK (50134822)                             	True
Searching For Artist Info For Voica (9079422)                                   	True
Searching For Artist Info For Max $avage (93091402)                             	True
Searching For Artist Info For Noggin Nodders (4383115)                          	True
Searching For Artist Info For Insane Shane Mckane & the Trailer Park Hunnies (61194622)	True
Searching For Artist Info For Markus Springer (11679915)                        	True
Searching For Artist Info For Misha Kovar (15173599)                            	True
Searching For Artist Info For When We Collide (1440112)                         	True
Searching For Artist Info For Moberg (6735391)                                  	True

Searching For Artist Info For Strata Florida (5209791)                          	True
Searching For Artist Info For Niagara (14037201)                                	True
Searching For Artist Info For Raph (884887)                                     	True
Searching For Artist Info For Max E. Tawil Z"L (112399922)                      	True
Searching For Artist Info For Ecstasy Project (4504796)                         	True
Searching For Artist Info For The Control Group (152515)                        	True
Searching For Artist Info For Banda Dip (113705712)                             	True
Searching For Artist Info For The Flute Clan (1328606)                          	True
Searching For Artist Info For Sunny Side Up (398695)                            	True
Searching For Artist Info For The Shred, Skate 'n' Surfers (6140410)            	True
Searching For Artist Info For ALBANESE Virginie (135034182)                     	True
Searching For Artist Info For Zeke & Ross (13155409)                            	True
Searching For Artist Info For Virginie Séba (92244782)                         	True
Searching For Artist Info For Motek, Andrew Rose (1366909)                      	True
Searching For Artist Info For Lou Monte (155986)                                	True
Searching For Artist Info For Dee Dee Sharp & Chubby Checker (92912712)         	True
Searching For Artist Info For Deante' Melo (125499912)                          	True
Searching For Artist Info For My Favorite Drug (126502392)                      	True
Searching For Artist Info For Owun Siks Mafia (121737602)                       	True
Searching For Artist Info For El Griz Mx (144916322)                            	True
======================================================================================================================================================
700/?      : Process [Getting Deezer ArtistIDs] Has Run For 25 Minutes and 15 Seconds.
Saving 376319 (New=700) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Bella Ciao (4476203)                              	True
Searching For Artist Info For Amethyst Trio (5404197)                           	True
Searching For Artist Info For Guillaume Lekeu (1638791)                         	True
Searching For Artist Info For Boya Chile, Aki Bergen (1366709)                  	True
Searching For Artist Info For Particle Specialist (132833022)                   	True
Searching For Artist Info For Slovak Sinfonietta Orchestra (3033691)            	True
Searching For Artist Info For Telekinetic Yeti (12104684)                       	True
Searching For Artist Info For John St. John (1085395)                           	True
Searching For Artist Info For Analogue Transit (1813601)                        	True
Searching For Artist Info For Anthony Pini (1438303)                            	True
Searching For Artist Info For Tanus Foe (5117403)                               	True
Searching For Artist Info For Jaybee Singer (8044319)                           	True
Searching For Artist Info For Zzhey (62181622)                                  	True
Searching For Artist Info For Straight White Lines (1085197)                    	True
Searching For Artist Info For Mark Allen Piccolo (13072609)                     	True
Searching For Artist Info For Dareyes De La Sierra (324309)                     	True
Searching For Artist Info For Larsen Factory (6797603)                          	True
Searching For Artist Info For WAZHING TITANS (143993112)                        	True
Searching For Artist Info For Dawod Nazari (116939322)                          	True
Searching For Artist Info For Bhajan Sopori, Enayet Hossain (4949197)           	True
Searching For Artist Info For Klement Ola-Daniels (67832912)                    	True
Searching For Artist Info For Phạm Minh Thành (11721809)                      	True
Searching For Artist Info For Cece Bullard (127445882)                          	True
Searching For Artist Info For El Incendio Más Largo Del Mundo (14769595)       	True
Searching For Artist Info For Royal Opera Orchestra - Florence Austral (1554496)	True
Searching For Artist Info For Oui Go High (87781722)                            	True
Searching For Artist Info For Palastorchester, Gesang: Max Raabe (199909)       	True
Searching For Artist Info For Cop Oslm (75863822)                               	True
Searching For Artist Info For Varo MK (4321887)                                 	True
Searching For Artist Info For Samuel Cattiau (9590796)                          	True
Searching For Artist Info For Roxie Jane (6693491)                              	True
Searching For Artist Info For Trupa Pancronic (92599412)                        	True
Searching For Artist Info For Joshua James and the Runaway Trains (1140292)     	True
Searching For Artist Info For Jace Carrillo (13138309)                          	True
Searching For Artist Info For Apocalypse Warhead (4324815)                      	True
Searching For Artist Info For Jerboah (12045822)                                	True
Searching For Artist Info For Windham Hill Artists (1399501)                    	True
Searching For Artist Info For #1 Hits Now, Chill Out 2016, Sex Music Zone (12065286)	True
Searching For Artist Info For Seiko (95796)                                     	True
Searching For Artist Info For The Schola Cantorum of St. Peter the Apostle (1268906)	True
Searching For Artist Info For DM Rorschach (87186692)                           	True
Searching For Artist Info For Libera-Robert Prizeman-Fiona Pears-John Anderson-Steven Geraghty-Chris Dodd-Ian Tilley-Michael Horncastle-Callum Payne (1483819)	True
Searching For Artist Info For Caleb Awiti (79740612)                            	True
Searching For Artist Info For K. A. Patterson and the Paradise Band (1137386)   	True
Searching For Artist Info For The John Andrews Band (87533102)                  	True
Searching For Artist Info For Kev Price and the City Strikers (3937091)         	True
Searching For Artist Info For Selling Atoms (109995322)                         	True
Searching For Artist Info For Billy Joe Young (1017330)                         	True
Searching For Artist Info For Koerner & Treplec (9942900)                       	True
Searching For Artist Info For Nortenisimo M7 (106684322)                        	True
======================================================================================================================================================
750/?      : Process [Getting Deezer ArtistIDs] Has Run For 27 Minutes and 6 Seconds.
Saving 376369 (New=750) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Phil York (179126)                                	True
Searching For Artist Info For Winnie Page and the Dirt Band (130405322)         	True
Searching For Artist Info For J.Magee and the Crossed Lines (7942812)           	True
Searching For Artist Info For The Light Opera Company (1011212)                 	True
Searching For Artist Info For Lilian & Tonio (4938586)                          	True
Searching For Artist Info For Sepp Gussmann und sein Orchester (200126)         	True
Searching For Artist Info For Cherrie Choi (7200988)                            	True
Searching For Artist Info For Krp Project! (1485215)                            	True
Searching For Artist Info For Mack Zukarita (152782622)                         	True
Searching For Artist Info For DFW Lights (121549222)                            	True
Searching For Artist Info For Dario Baldan Bembo (64630)                        	True
Searching For Artist Info For Sibel Karabaş (9482496)                          	True
Searching For Artist Info For Academy of St. Martin in the Fields and Sir Neville Marriner (4028703)	True

Searching For Artist Info For Sarah Lark & Ramin Karimloo (1161997)             	True
Searching For Artist Info For The Cool Corporation (5319901)                    	True
Searching For Artist Info For Sticks N' Stones Band (142008702)                 	True
Searching For Artist Info For Catherine Russell (152822)                        	True
Searching For Artist Info For Big John Hamilton and Doris Allen (4807330)       	True
Searching For Artist Info For Juan Carlos Heredia (142997022)                   	True
Searching For Artist Info For Rommy LeVent (121309292)                          	True
Searching For Artist Info For Pedro Ruy Blas (662897)                           	True
Searching For Artist Info For N.B.G. (1600386)                                  	True
Searching For Artist Info For Tomcat. (14662415)                                	True
Searching For Artist Info For Sack Boy Trio (53156392)                          	True
Searching For Artist Info For Lapsung (12402386)                                	True
Searching For Artist Info For K-OZ Klikk (51085022)                             	True
Searching For Artist Info For Gopal Rai (4143319)                               	True
Searching For Artist Info For New Even (13462409)                               	True
Searching For Artist Info For On A Mission (163015)                             	True
Searching For Artist Info For Sanni (127806582)                                 	True
Searching For Artist Info For Floral Nature Peace Project (111639422)           	True
Searching For Artist Info For Count Basie & His All American Rhythm Section (173126)	True
Searching For Artist Info For Abstract Vision & Elite Electronic vs Broning (3986191)	True
Searching For Artist Info For Saffron Eyes (111441622)                          	True
Searching For Artist Info For Adam Faith & The Roulettes (1484215)              	True
Searching For Artist Info For Beba Vasić (5219415)                             	True
Searching For Artist Info For Young Eazy (5680019)                              	True
Searching For Artist Info For Wince Coles (5160291)                             	True
Searching For Artist Info For Rolly Kn (106973792)                              	True
Searching For Artist Info For K Dub (6406730)                                   	True
Searching For Artist Info For Black Sheep Dres (5907315)                        	True
Searching For Artist Info For Kera & the Lesbians (6133430)                     	True
Searching For Artist Info For Flybug (1530291)                                  	True
Searching For Artist Info For Ching Bing Jr. (6040230)                          	True
Searching For Artist Info For Mr. Manish (6728919)                              	True
Searching For Artist Info For Rolly Records (141537092)                         	True
Searching For Artist Info For Beth Anderson (131500)                            	True
Searching For Artist Info For PUBLIQuartet (7907100)                            	True
Searching For Artist Info For George Scott Wood (1539803)                       	True
Searching For Artist Info For Marvelous MMW (130421602)                         	True
======================================================================================================================================================
800/?      : Process [Getting Deezer ArtistIDs] Has Run For 28 Minutes and 52 Seconds.
Saving 376419 (New=800) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Sunstryk (268019)                                 	True
Searching For Artist Info For Tampa Music Machine (54875092)                    	True
Searching For Artist Info For The Lat-Teens (3029201)                           	True
Searching For Artist Info For Allison DeSalvo (135271022)                       	True
Searching For Artist Info For Malefic Mantis (138994912)                        	True
Searching For Artist Info For Gitta Alpar - Berliner Symphoniker (1553526)      	True
Searching For Artist Info For Adam Paskowitz (246901)                           	True
Searching For Artist Info For Inverse (485710)                                  	True
Searching For Artist Info For Anas M (78903312)                                 	True
Searching For Artist Info For Ramona & The Red Vipers (77668202)                	True
Searching For Artist Info For DJ JAVI VIRGO (11813915)                          	True
Searching For Artist Info For Erikah Karst (1662015)                            	True
Searching For Artist Info For Teddy Hill & The Southern Soul (1702115)          	True
Searching For Artist Info For Rtr Choirboy (79593502)                           	True
Searching For Artist Info For Dopamine Circuit (13519297)                       	True
Searching For Artist Info For Jonas Park & David Bollmann (7008003)             	True
Searching For Artist Info For Quintette Moraguès (4062922)                     	True
Searching For Artist Info For Petals of Power (149787892)                       	True
Searching For Artist Info For A. M. Rajah (120897)                              	True
Searching For Artist Info For Kiev Camarata, Paul Polivnick (209209)            	True
Searching For Artist Info For Gary Burton & Friends (74599)                     	True
Searching For Artist Info For Enemy Contact (10182900)                          	True
Searching For Artist Info For Bybo & Sin2 (67502022)                            	True
Searching For Artist Info For Polarbear Fur (63300022)                          	True
Searching For Artist Info For Baron Flynt (123869622)                           	True
Searching For Artist Info For Audiofly & SIS (12620815)                         	True
Searching For Artist Info For Hamburg Symphony Orchestra And Alois Springer (300701)	True
Searching For Artist Info For pinkie normal (104499422)                         	True
Searching For Artist Info For Peppe Cirillo (10608715)                          	True
Searching For Artist Info For Pech+Schwefel (124525992)                         	True
Searching For Artist Info For Rainer Kuisma (306392)                            	True
Searching For Artist Info For Rodman Kno (76303702)                             	True
Searching For Artist Info For Timeless Haunt (70480302)                         	True
Searching For Artist Info For Oliver-Dawson's Saxon (93597)                     	True
Searching For Artist Info For Nicole Schweizer (6146400)                        	True
Searching For Artist Info For Franciska Addari (10644809)                       	True
Searching For Artist Info For APOX 'FAIRY TALE' (47143922)                      	True
Searching For Artist Info For Perfectly Damaged (102785222)                     	True
Searching For Artist Info For The Simpleton (157572902)                         	True
Searching For Artist Info For Uranium Scrap (76129022)                          	True
Searching For Artist Info For Red Devil Magic (6405630)                         	True
Searching For Artist Info For SDK Project (1657403)                             	True
Searching For Artist Info For Praise Magnificat Christmas (10239930)            	True
Searching For Artist Info For Median Insight (49515512)                         	True
Searching For Artist Info For Blåsbus 3 tuba (10725491)                        	True
Searching For Artist Info For Syntec (120186)                                   	True
Searching For Artist Info For REVO DJ (56102522)                                	True
Searching For Artist Info For Mel Gibson Safari (1699012)                       	True
Searching For Artist Info For Perikles Papapetropoulos (1306415)                	True
Searching For Artist Info For Gram Wallflower (123269512)                       	True
======================================================================================================================================================
850/?      : Process [Getting Deezer ArtistIDs] Has Run For 30 Minutes and 36 Seconds.
Saving 376469 (New=850) Deezer Searched For Artist (Info) IDs

======================================================================================================================================================
Searching For Artist Info For Kee Lo (1697303)                                  	True
Searching For Artist Info For Marquise De'vaun Wess (86516812)                  	True
Searching For Artist Info For Music for Puppies All-stars (139762822)           	True
Searching For Artist Info For Kier Ramar (113029022)                            	True
Searching For Artist Info For Iwurdplay (12201600)                              	True
Searching For Artist Info For Grupo El Tiempo (12707297)                        	True
Searching For Artist Info For Huron Lines (123655692)                           	True
Searching For Artist Info For Susso Seki Singh (14699193)                       	True
Searching For Artist Info For Criss Asp (65473482)                              	True
Searching For Artist Info For Chito Ordoñez (14003721)                         	True
Searching For Artist Info For La Fiesta du Camping (259909)                     	True
Searching For Artist Info For Mabel Wayne (1260703)                             	True
Searching For Artist Info For Něco Si Přej (51962312)                         	True
Searching For Artist Info For Ferenc (16921)                                    	True
Searching For Artist Info For Batteria MXM (89639512)                           	True
Searching For Artist Info For Vladimir Tsypin (1558087)                         	True
Searching For Artist Info For DJ Frust (3951021)                                	True
Searching For Artist Info For RUBIX (NZ) (5501486)                              	True
Searching For Artist Info For Simone Zanchini Jazz Quartet (50204792)           	True
Searching For Artist Info For TONY ROSS (1625422)                               	True
Searching For Artist Info For Franchising (4838993)                             	True
Searching For Artist Info For Виктор Мержанов (5484485)                         	True
Searching For Artist Info For Bilal Milano (9587716)                            	True
Searching For Artist Info For Mark S Miller (3078121)                           	True
Searching For Artist Info For Cassius Jay & Fallon (14026697)                   	True
Searching For Artist Info For Kat Meets Gerardo Roschini (92991)                	True
Searching For Artist Info For Samuel Ramey-National Philharmonic Orchestra-Peter Matz (3216701)	True
Searching For Artist Info For Piyanist Neco (128883812)                         	True
Searching For Artist Info For DJ Jovine (12586798)                              	True
Searching For Artist Info For BEETHOVEN ACADEMY ORCHESTRA (577921)              	True
Searching For Artist Info For Palisades Drive (10388126)                        	True
Searching For Artist Info For Mauvais-Genre ! (4917616)                         	True
Searching For Artist Info For Monster Taxi and Pepper Mashay (1290306)          	True
Searching For Artist Info For On The Wireless (75522192)                        	True
Searching For Artist Info For Casual Punk, Danny White (14754415)               	True
Searching For Artist Info For Wayne Gardiner Presents Trackmasters (4339721)    	True
Searching For Artist Info For Plux (1623303)                                    	True
Searching For Artist Info For Jérôme Minière (2472391)                       	True
Searching For Artist Info For MC Trey (4589001)                                 	True
Searching For Artist Info For Erwan Keravec (69116)                             	True
Searching For Artist Info For Yellow Scab (62526)                               	True
Searching For Artist Info For Warm Pink Noise (146509192)                       	True
Searching For Artist Info For mowtif (98332422)                                 	True
Searching For Artist Info For Shin`s looping (129879802)                        	True
Searching For Artist Info For LN Balla (155837902)                              	True
Searching For Artist Info For Oscuro P (1417626)                                	True
Searching For Artist Info For Leonora Rega (364922)                             	True
Searching For Artist Info For Bob Adams & Thirsty Boots (4760430)               	True
Searching For Artist Info For Fratelli La Bionda (5513315)                      	True
Searching For Artist Info For Richard The Third (438809)                        	True
======================================================================================================================================================
900/?      : Process [Getting Deezer ArtistIDs] Has Run For 32 Minutes and 41 Seconds.
Saving 376519 (New=900) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Bobby Kimball (Of Toto) (4138700)                 	True
Searching For Artist Info For Ya Boy Ju (2352121)                               	True
Searching For Artist Info For Aspis (13646321)                                  	True
Searching For Artist Info For Strike (88942022)                                 	True
Searching For Artist Info For David Chrissor (359801)                           	True
Searching For Artist Info For Seirious (5594819)                                	True
Searching For Artist Info For Rány Těla (1200195)                             	True
Searching For Artist Info For Life On Uranus (141635392)                        	True
Searching For Artist Info For Frivolous Creatures (140142092)                   	True
Searching For Artist Info For MIKA V (5245915)                                  	True
Searching For Artist Info For Aikon (74890)                                     	True
Searching For Artist Info For Random Movement (259222)                          	True
Searching For Artist Info For Aki Bergen & Pezzner feat. Terry Grant (1769221)  	True
Searching For Artist Info For California Polytechnic State University Wind Ensemble (3400091)	True
Searching For Artist Info For DJ Stan B On The Track (65321222)                 	True
Searching For Artist Info For Thao Trang (5272099)                              	True
Searching For Artist Info For Regents (1645215)                                 	True
Searching For Artist Info For Marc JB vs Jack Jackson (4174506)                 	True
Searching For Artist Info For Ageet Zweistra (4563119)                          	True
Searching For Artist Info For Lisa-May (10725919)                               	True
Searching For Artist Info For One of Vas (64508622)                             	True
Searching For Artist Info For Sidious J (13321699)                              	True
Searching For Artist Info For Chad Sullins Last Call Coalition (9655288)        	True
Searching For Artist Info For Common Hymnal (6140630)                           	True
Searching For Artist Info For B. Slinky Antal (132926522)                       	True
Searching For Artist Info For P.N.D.K (94870102)                                	True
Searching For Artist Info For Los Tremendos Pavo Reales (1364406)               	True
Searching For Artist Info For DJ Grace Kelly (9905730)                          	True
Searching For Artist Info For error.is.human (127532712)                        	True
Searching For Artist Info For Saffron Viii (15372997)                           	True
Searching For Artist Info For Spek and Gizmo (49095321)                         	True
Searching For Artist Info For Tristen Blake (79426922)                          	True
Searching For Artist Info For Headspace The Ace (117323282)                     	True
Searching For Artist Info For Sigh & Explode (2109001)                          	True
Searching For Artist Info For Rubber Tramp (12801721)                           	True
Searching For Artist Info For Richie Banks (14412585)                           	True
Searching For Artist Info For Young Weight (49010421)                           	True

Searching For Artist Info For Hard Resistance (2493591)                         	True
Searching For Artist Info For Mantra para Dormir & Musica Romantica Ensemble (13996019)	True
Searching For Artist Info For Shane D'fury (10522601)                           	True
Searching For Artist Info For The Yellow Balloon (297215)                       	True
Searching For Artist Info For The Kings Of Jazz Featuring Kenny Davern (1329306)	True
Searching For Artist Info For Imperial Monuments (106748822)                    	True
Searching For Artist Info For Wil Caro (131949002)                              	True
Searching For Artist Info For Quantum Glide (125654922)                         	True
Searching For Artist Info For Arnstein Roch Øverland (2209501)                  	True
Searching For Artist Info For Ranji (115379312)                                 	True
Searching For Artist Info For Les Ghastly (147222322)                           	True
Searching For Artist Info For Michel Bergeron (14623403)                        	True
Searching For Artist Info For Cello+Laptop (5121112)                            	True
======================================================================================================================================================
950/?      : Process [Getting Deezer ArtistIDs] Has Run For 34 Minutes and 44 Seconds.
Saving 376569 (New=950) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Garçon normal (139111222)                        	True
Searching For Artist Info For dany mata 14 (137516392)                          	True
Searching For Artist Info For Plunge (520196)                                   	True
Searching For Artist Info For Nita Berger (84522)                               	True
Searching For Artist Info For Delara's Music (128776392)                        	True
Searching For Artist Info For Brahma Bull (5868003)                             	True
Searching For Artist Info For Vagabond Lovers (5455502)                         	True
Searching For Artist Info For Dramatic Changes (61551812)                       	True
Searching For Artist Info For Shaggy Molasses (10087482)                        	True
Searching For Artist Info For Les Indiens Yaquis (139972592)                    	True
Searching For Artist Info For Normalize (477326)                                	True
Searching For Artist Info For PS the Rebels (9321916)                           	True
Searching For Artist Info For Whispering Smith (444016)                         	True
Searching For Artist Info For Larissa Pesch (58879492)                          	True
Searching For Artist Info For Philieano (100719)                                	True
Searching For Artist Info For $hELL $PACE $TATION Quasi Wipeout (156830902)     	True
Searching For Artist Info For Lanna & Larissa (123860592)                       	True
Searching For Artist Info For Sylvia Shemwell (4913521)                         	True
Searching For Artist Info For Chris Garofalo (1162186)                          	True
Searching For Artist Info For Vincent-Marie Bouvot (4072603)                    	True
Searching For Artist Info For Serene Cacophony (59399312)                       	True
Searching For Artist Info For Larissa e Isabela (91239692)                      	True
Searching For Artist Info For Alessandro Stradella (83616)                      	True
Searching For Artist Info For Honeyhander (2336901)                             	True
Searching For Artist Info For Leesa Sklover-Sangeet (1512186)                   	True
Searching For Artist Info For Twenty Gauge (10323284)                           	True
Searching For Artist Info For Walkers In The City (14677003)                    	True
Searching For Artist Info For WIL PlayaOnn (125646202)                          	True
Searching For Artist Info For EBTC Musik (117794292)                            	True
Searching For Artist Info For Kid Indoor (2007001)                              	True
Searching For Artist Info For Daniel Wanrooy and René Havelaar (1943491)       	True
Searching For Artist Info For Electro Potato (10950430)                         	True
Searching For Artist Info For La Zimba (2913891)                                	True
Searching For Artist Info For Music P & Marque Aurel (11906515)                 	True
Searching For Artist Info For Heathen Rites (14068521)                          	True
Searching For Artist Info For Friedrich Wilhelm Zachow (3010591)                	True
Searching For Artist Info For Nomad Navi (108539892)                            	True
Searching For Artist Info For Obsidian Gate (1616515)                           	True
Searching For Artist Info For Micha El (6051392)                                	True
Searching For Artist Info For Ney Dimaculangan (4904592)                        	True
Searching For Artist Info For Los Autenticos pasteles verdes (4181718)          	True
Searching For Artist Info For David Costabile (6923503)                         	True
Searching For Artist Info For Steve Bledsoe (1457309)                           	True
Searching For Artist Info For DEDA & The Time'Machine (11708109)                	True
Searching For Artist Info For Rewire the time machine (13321409)                	True
Searching For Artist Info For Ballers Ona Mission (5010506)                     	True
Searching For Artist Info For Los Gitanillos De Bronce (10394610)               	True
Searching For Artist Info For Mark Potter (4420018)                             	True
Searching For Artist Info For These Guitars Say Sorry (10886930)                	True
Searching For Artist Info For Pedro Delgardo vs Reaky (957200)                  	True
======================================================================================================================================================
1000/?     : Process [Getting Deezer ArtistIDs] Has Run For 36 Minutes and 31 Seconds.
Saving 376619 (New=1000) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Kenan Bishop & Jonesy (11574401)                  	True
Searching For Artist Info For Bandura, Hellfield (13691115)                     	True
Searching For Artist Info For Jwavves (73241222)                                	True
Searching For Artist Info For Hates (1154287)                                   	True
Searching For Artist Info For SUGAR HILLZ GARDENS (147649522)                   	True
Searching For Artist Info For Mont Duamel (95914822)                            	True
Searching For Artist Info For If You're Happy And You Know It (7696900)         	True
Searching For Artist Info For Angel Rocha El Hijo Del Rey (104753722)           	True
Searching For Artist Info For Taino & Ciboney (4719819)                         	True
Searching For Artist Info For Anji Sami (6034310)                               	True
Searching For Artist Info For Vadim Spark (362192)                              	True
Searching For Artist Info For R.J. Mischo (275916)                              	True
Searching For Artist Info For Doreen Selly Oloo (1172809)                       	True
Searching For Artist Info For Jay Johnson's Boppers (198498)                    	True
Searching For Artist Info For Joe Shithead Keithley (1359316)                   	True
Searching For Artist Info For Shellz Madhouse (96356402)                        	True
Searching For Artist Info For p l a s t i c プラスチック (147431402)                 	True
Searching For Artist Info For yung Pipedream (90132822)                         	True
Searching For Artist Info For Karolina Kozak (1625815)                          	True
Searching For Artist Info For Grace (7292)                                      	True
Searching For Artist Info For Orkiestra Symfoniczna Filharmonii Narodowej (5895715)	True

Searching For Artist Info For Mahalaxmi Ayyer (5117985)                         	True
Searching For Artist Info For Shreya Ghosle (4617588)                           	True
Searching For Artist Info For Choir of Queens' College, Cambridge, John Gibbons & Julian Malton (5009392)	True
Searching For Artist Info For JQ Dezi (92531022)                                	True
Searching For Artist Info For Royal Philharmonic Orchestra;Harold Farberman;Gustav Mahler (6681003)	True
Searching For Artist Info For Rebekah Van Tinteren (5686388)                    	True
Searching For Artist Info For Raphael Kortez (92562412)                         	True
Searching For Artist Info For BIG CROW (73122982)                               	True
Searching For Artist Info For The Happy Pill Academy (13992595)                 	True
Searching For Artist Info For Altai Kai (5570810)                               	True
Searching For Artist Info For Kittie Blacc (14722603)                           	True
Searching For Artist Info For Art of Fighters and Noize Suppressor (4854209)    	True
Searching For Artist Info For Steen Kofoed (10875306)                           	True
Searching For Artist Info For El Age Project (3140121)                          	True
Searching For Artist Info For Aïwa Maïga (6524803)                            	True
Searching For Artist Info For Jérémie Baldi (1539206)                         	True
Searching For Artist Info For Olof Dreijer (4420310)                            	True
Searching For Artist Info For Quantum Metal (152693702)                         	True
Searching For Artist Info For Jay Sovereign (67058922)                          	True
Searching For Artist Info For Kumar Gandharva, Vasant Achrekar, Govindrao Patwardhan (4115909)	True
Searching For Artist Info For Megan Kelly (5331609)                             	True
Searching For Artist Info For Ewa Pobłocka, Warsaw Philharmonic Orchestra, Kazimierz Kord (54546512)	True
Searching For Artist Info For Dj-Elven (90953222)                               	True
Searching For Artist Info For Hannu Salama & Hepa Halme (73009212)              	True
Searching For Artist Info For Nef Cayetano (13350803)                           	True
Searching For Artist Info For Martin Reyes (4341991)                            	True
Searching For Artist Info For SEX HARUKO (144865892)                            	True
Searching For Artist Info For Indigo (feat. Mark Ivester, Brian Withycombe, Brad Allison, Donald Marrow, Chuck Deardorf, Brian Steiner, Tom Collier) (4195884)	True
Searching For Artist Info For Lipous (306591)                                   	True
======================================================================================================================================================
1050/?     : Process [Getting Deezer ArtistIDs] Has Run For 38 Minutes and 15 Seconds.
Saving 376669 (New=1050) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For SKB (103053892)                                   	True
Searching For Artist Info For Lloyd George (1690999)                            	True
Searching For Artist Info For Solander & Stuart Stone (89410102)                	True
Searching For Artist Info For Squad E & Enemy (1610387)                         	True
Searching For Artist Info For Bad News from Houston (4408810)                   	True
Searching For Artist Info For Billy Macadamia (116518492)                       	True
Searching For Artist Info For All The People (4221686)                          	True
Searching For Artist Info For James Casimir Nay (103905982)                     	True
Searching For Artist Info For Donna Lynch (5238021)                             	True
Searching For Artist Info For Amnesia Pills (11301522)                          	True
Searching For Artist Info For Juicy Badness (51105882)                          	True
Searching For Artist Info For Eric Alphonso Green (5541282)                     	True
Searching For Artist Info For Kate Buddeke (103650992)                          	True
Searching For Artist Info For Dj Everton Martins (64287722)                     	True
Searching For Artist Info For Cold Steel Revolver (9078492)                     	True
Searching For Artist Info For I'll Stand By You (6222306)                       	True
Searching For Artist Info For Sweet Ascent (5245497)                            	True
Searching For Artist Info For Pelle Miljoona (272588)                           	True
Searching For Artist Info For The Hush with Bob Fox (4288109)                   	True
Searching For Artist Info For the Flying Tourbillon Orchestra (11525687)        	True
Searching For Artist Info For The Absentee Project (57895122)                   	True
Searching For Artist Info For Paul Beard (4750184)                              	True
Searching For Artist Info For Shades & Peters (1744421)                         	True
Searching For Artist Info For Ju Kaia (65447892)                                	True
Searching For Artist Info For run SOFA (13541815)                               	True
Searching For Artist Info For Madona (1232410)                                  	True
Searching For Artist Info For Garrison Keillor (243830)                         	True
Searching For Artist Info For Donald-D (5606209)                                	True
Searching For Artist Info For Nicolás Méndez (4837191)                        	True
Searching For Artist Info For 1st Battalion Queen's Own Cameron Highlanders (4578022)	True
Searching For Artist Info For Technodreamer & SlanG (5433496)                   	True
Searching For Artist Info For United Faith Christian Academy Praise Band (8763290)	True
Searching For Artist Info For FHFH B3 (93988122)                                	True
Searching For Artist Info For Wolfgang Schlüter Quartet (3231491)              	True
Searching For Artist Info For Sir Neville Marriner-Academy of St Martin-in-the-Fields-Kenneth Sillito-Celia Nicklin-Mark Bennett-Philip Pickett-George Malcolm (1477430)	True
Searching For Artist Info For Aqui Em Marte (14233197)                          	True
Searching For Artist Info For Südtiroler Gaudi Express (187695)                	True
Searching For Artist Info For Interstate-5 (79708802)                           	True
Searching For Artist Info For Chris Powell & The Five Blue Flames (1461586)     	True
Searching For Artist Info For Teear Dropz (13562603)                            	True
Searching For Artist Info For Judgement Son (11205292)                          	True
Searching For Artist Info For José Laca (4497115)                              	True
Searching For Artist Info For Michael Carey (491321)                            	True
Searching For Artist Info For Sasori (14009199)                                 	True
Searching For Artist Info For LE CITRON (117771692)                             	True
Searching For Artist Info For Gerald Wirth (4555306)                            	True
Searching For Artist Info For Alison Krauss And Union Station (288322)          	True
Searching For Artist Info For Eradicator (115354102)                            	True
Searching For Artist Info For Cleopatra Beats (111931092)                       	True
Searching For Artist Info For Risky Man (151155502)                             	True
======================================================================================================================================================
1100/?     : Process [Getting Deezer ArtistIDs] Has Run For 39 Minutes and 56 Seconds.
Saving 376719 (New=1100) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Electronic Opium (8607290)                        	True
Searching For Artist Info For 夏天 (Alex Xia) (4302096)                           	True

Searching For Artist Info For Seagull Sensor Drive (123822802)                  	True
Searching For Artist Info For El Super Bimbo (6139610)                          	True
Searching For Artist Info For Rad Relic (64244522)                              	True
Searching For Artist Info For Christiano Can (8655388)                          	True
Searching For Artist Info For Pasquale Feis (4250309)                           	True
Searching For Artist Info For Hannah Georgas (397530)                           	True
Searching For Artist Info For Frank Madden (1639109)                            	True
Searching For Artist Info For Jesse Lamar Williams (71636902)                   	True
Searching For Artist Info For Holy Water Buffalo (896412)                       	True
Searching For Artist Info For Jean-Roch Roy (6851809)                           	True
Searching For Artist Info For Hummingbird & The Mess (8389526)                  	True
Searching For Artist Info For Allen Blairman (4840185)                          	True
Searching For Artist Info For The Blue Gliss (6523819)                          	True
Searching For Artist Info For Paulo Tozzi (6982815)                             	True
Searching For Artist Info For Jeffrey Babko,Sean Hurley (11112888)              	True
Searching For Artist Info For Radioactive Honey (141623222)                     	True
Searching For Artist Info For Young Aviators (1010698)                          	True
Searching For Artist Info For Jang Young Hee (150002612)                        	True
Searching For Artist Info For The Havana Cuban Boys (1058485)                   	True
Searching For Artist Info For Sore Losers (1610987)                             	True
Searching For Artist Info For Alone In The Crowd (8356010)                      	True
Searching For Artist Info For Lisaya vs. Thomas Petersen (173406)               	True
Searching For Artist Info For Douglas Davis (2733021)                           	True
Searching For Artist Info For New Solina (53577102)                             	True
Searching For Artist Info For Kocian Quartet (1535430)                          	True
Searching For Artist Info For Her Silhouette (89504622)                         	True
Searching For Artist Info For Raman Dari (58164502)                             	True
Searching For Artist Info For Mai Hậu (59796312)                              	True
Searching For Artist Info For Bless the Knights (9790616)                       	True
Searching For Artist Info For Clue Monati (119606692)                           	True
Searching For Artist Info For The Chris Phillips (61562822)                     	True
Searching For Artist Info For Earle Dumler (7880410)                            	True
Searching For Artist Info For Leather Tramp (8678092)                           	True
Searching For Artist Info For Alessioego (13543899)                             	True
Searching For Artist Info For Dave Carroll (5023986)                            	True
Searching For Artist Info For Vulgar Pigeons (150903)                           	True
Searching For Artist Info For spherical disrupted (1006915)                     	True
Searching For Artist Info For Solemn SilenSe (81109402)                         	True
Searching For Artist Info For Cecilia Lövdahl Lundgren (13237803)              	True
Searching For Artist Info For J.F.B (137546312)                                 	True
Searching For Artist Info For Benny Amdursky (4134487)                          	True
Searching For Artist Info For Oakland Elementary School Arkestra (47571792)     	True
Searching For Artist Info For Kazmi (4957510)                                   	True
Searching For Artist Info For Of The First Born Sun (5000588)                   	True
Searching For Artist Info For Jeff Perry Music (12336726)                       	True
Searching For Artist Info For Koopa G (100055602)                               	True
Searching For Artist Info For Isaac Sene (48902891)                             	True
Searching For Artist Info For Jem Beats (62913712)                              	True
======================================================================================================================================================
1150/?     : Process [Getting Deezer ArtistIDs] Has Run For 41 Minutes and 38 Seconds.
Saving 376769 (New=1150) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For DJ Swami (102430)                                 	True
Searching For Artist Info For Smooth Operator E $.0.E.! (99099522)              	True
Searching For Artist Info For Sunni Benji (114300002)                           	True
Searching For Artist Info For Jason Chen & Madilyn Bailey (9147510)             	True
Searching For Artist Info For Bms Veli (153070422)                              	True
Searching For Artist Info For Dubvisionist (278386)                             	True
Searching For Artist Info For Bright Visions (52823592)                         	True
Searching For Artist Info For Morning$tar (81232422)                            	True
Searching For Artist Info For Ojos (466800)                                     	True
Searching For Artist Info For Spade Morningstar (96334722)                      	True
Searching For Artist Info For Cheb Haroun (141554212)                           	True
Searching For Artist Info For The Drowning Octopi (11571515)                    	True
Searching For Artist Info For Slobodan Batjarevic (4313300)                     	True
Searching For Artist Info For Tirzah Lemmens (4876684)                          	True
Searching For Artist Info For Dear Rouge (4044610)                              	True
Searching For Artist Info For Jean-Francois Maljean (336903)                    	True
Searching For Artist Info For James C. Murray (89769212)                        	True
Searching For Artist Info For Darren Black (442521)                             	True
Searching For Artist Info For Sebastián Wat (60945792)                         	True
Searching For Artist Info For PCP Pat the Cripple Player (145885322)            	True
Searching For Artist Info For Antonii Carmon (128032622)                        	True
Searching For Artist Info For Osynlig Fetma (67367222)                          	True
Searching For Artist Info For Thom Balistrieri (10352910)                       	True
Searching For Artist Info For Sweed Music (4548991)                             	True
Searching For Artist Info For Ron Grainer And His Orchestra (639230)            	True
Searching For Artist Info For Jay Flow (7105803)                                	True
Searching For Artist Info For Sir David Willcocks, James Clark, Julian Godlee, Osian Ellis & Choir of King's College, Cambridge (53490312)	True
Searching For Artist Info For The Glendaruel Scottish Dance Band (122380222)    	True
Searching For Artist Info For Buddha (113726322)                                	True
Searching For Artist Info For Darryl J Mitchell (136836592)                     	True
Searching For Artist Info For Ryan Peel (1415009)                               	True
Searching For Artist Info For Gus Drax (6629988)                                	True
Searching For Artist Info For D-3 (15227491)                                    	True
Searching For Artist Info For KnewSound (113701422)                             	True
Searching For Artist Info For The Girls' Choir of Southwell Minster (90391022)  	True
Searching For Artist Info For Les Chevaliers Solex (11406492)                   	True
Searching For Artist Info For Shubhkaran Bagga (122939592)                      	True
Searching For Artist Info For Prince CJ Da Poet (83828122)                      	True
Searching For Artist Info For Frenquency (4335601)                              	True
Searching For Artist Info For Phoma (3957101)                                   	True
Searching For Artist Info For Loggy (15242995)                                  	True

Searching For Artist Info For Blue Ruin Trio (6001792)                          	True
Searching For Artist Info For Dinatla Tsa North (254310)                        	True
Searching For Artist Info For Trino Zurita (1428510)                            	True
Searching For Artist Info For Tex Williams & His Western Caravan (258606)       	True
Searching For Artist Info For Kremorteus (56711822)                             	True
Searching For Artist Info For Real Smokesta (9730316)                           	True
Searching For Artist Info For ZYGOMATICUS (52509212)                            	True
Searching For Artist Info For Social Disgrace (14822985)                        	True
Searching For Artist Info For Doa Blessed (75121892)                            	True
======================================================================================================================================================
1200/?     : Process [Getting Deezer ArtistIDs] Has Run For 43 Minutes and 31 Seconds.
Saving 376819 (New=1200) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Claude Meloni-Mirella Freni-Choeurs de l'Opéra National de Paris-Orchestre de l'Opéra National de Paris-Rafael Frühbeck de Burgos (1491210)	True
Searching For Artist Info For Robert K Ellis (10583585)                         	True
Searching For Artist Info For Lil Cerberus (116380222)                          	True
Searching For Artist Info For MARQUELL DA Poet (118361422)                      	True
Searching For Artist Info For Levon (1128588)                                   	True
Searching For Artist Info For Pia Tillmann (10335206)                           	True
Searching For Artist Info For The Hills Mover (8292406)                         	True
Searching For Artist Info For Omega 3 feat. Kim Novak (534610)                  	True
Searching For Artist Info For Meditative Sect (1298290)                         	True
Searching For Artist Info For Adz Brand (51743292)                              	True
Searching For Artist Info For Ziggy T (94959422)                                	True
Searching For Artist Info For Sour Space Candy (81357892)                       	True
Searching For Artist Info For The Tim Sars Band (5765503)                       	True
Searching For Artist Info For Rise In Vein (130072382)                          	True
Searching For Artist Info For Heltir (4110421)                                  	True
Searching For Artist Info For Kike (1319119)                                    	True
Searching For Artist Info For JB D General (90451022)                           	True
Searching For Artist Info For Maurice De Feraudy (4713188)                      	True
Searching For Artist Info For Vâll (74323682)                                  	True
Searching For Artist Info For Emmanuelle Haïm-Le Concert d`Astrée-Christopher Maltman-Pascal Bertin-Paul Agnew-Richard Burkhard (1505326)	True
Searching For Artist Info For Paladin Shield (10044226)                         	True
Searching For Artist Info For EpitomeZero (14062685)                            	True
Searching For Artist Info For Ustad Shahid Parvez Khan & Enayet Hossain (14547699)	True
Searching For Artist Info For Pentti Kaartinen (5263991)                        	True
Searching For Artist Info For November Purple (9927190)                         	True
Searching For Artist Info For Emmanuelle Haïm-Le Concert d`Astrée-Ian Bostridge (1505329)	True
Searching For Artist Info For Jan Sadiq (10682219)                              	True
Searching For Artist Info For Carlone (5978022)                                 	True
Searching For Artist Info For Jehnova (15372229)                                	True
Searching For Artist Info For Ripit (12730285)                                  	True
Searching For Artist Info For Mass in Orbit (9699290)                           	True
Searching For Artist Info For The Trapeze Artists (127086322)                   	True
Searching For Artist Info For Urumi Kanzaki (75782802)                          	True
Searching For Artist Info For Houseboy (5284929)                                	True
Searching For Artist Info For BLOODY SHAME SOUND (151672392)                    	True
Searching For Artist Info For Christopher Daniel Wilson (51316422)              	True
Searching For Artist Info For Asbjørn Holmseth (5840415)                        	True
Searching For Artist Info For Akhil Redhu (69941612)                            	True
Searching For Artist Info For Colder Than Diablo (110061692)                    	True
Searching For Artist Info For Rain Drops for Sleep (9826426)                    	True
Searching For Artist Info For Psycho Alvarez (12230000)                         	True
Searching For Artist Info For La Bruja (360716)                                 	True
Searching For Artist Info For DJ Steve May (10325200)                           	True
Searching For Artist Info For DJ Glaze (12674909)                               	True
Searching For Artist Info For Julian Perez (12166626)                           	True
Searching For Artist Info For Ant Banks (342916)                                	True
Searching For Artist Info For Cloudbreak (5053610)                              	True
Searching For Artist Info For Duncan Sheik (16193)                              	True
Searching For Artist Info For Skip Peck (1655403)                               	True
Searching For Artist Info For Riddim Squad (876218)                             	True
======================================================================================================================================================
1250/?     : Process [Getting Deezer ArtistIDs] Has Run For 45 Minutes and 16 Seconds.
Saving 376869 (New=1250) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Orchestre philarmonique des Pays de la Loire (6365888)	True
Searching For Artist Info For Dootbeats (12523598)                              	True
Searching For Artist Info For Caramel Column (58285322)                         	True
Searching For Artist Info For Luis Feder (137369822)                            	True
Searching For Artist Info For Kaela Francheska (121601402)                      	True
Searching For Artist Info For Jajj Bains (51105112)                             	True
Searching For Artist Info For RCVC (149304812)                                  	True
Searching For Artist Info For Manchester Renaissance Ensemble (14771793)        	True
Searching For Artist Info For Emma Peel (92291)                                 	True
Searching For Artist Info For Rob Dekay (5396390)                               	True
Searching For Artist Info For Alpay Sahingoez (4314190)                         	True
Searching For Artist Info For Ganja Kid (11887209)                              	True
Searching For Artist Info For Rohff - Wallen (1477996)                          	True
Searching For Artist Info For Herald Engrossman (59750522)                      	True
Searching For Artist Info For Dardan Shkreli (127165192)                        	True
Searching For Artist Info For Larry Peters & Etro Hahn (1196599)                	True
Searching For Artist Info For Lawrence Rivers (56402322)                        	True
Searching For Artist Info For Romolo Balzani (1003087)                          	True
Searching For Artist Info For Dj Rayne (7175006)                                	True
Searching For Artist Info For Lian Ensemble (1178297)                           	True
Searching For Artist Info For Hitting Birth (1149519)                           	True
Searching For Artist Info For Flashback Caruso (4021106)                        	True
Searching For Artist Info For ICP (5517921)                                     	True

Searching For Artist Info For Yasufumi Suzuki (5082616)                         	True
Searching For Artist Info For Minotaur Minds (127120922)                        	True
Searching For Artist Info For April Boy Regino (103726)                         	True
Searching For Artist Info For Lev Knipper (1641310)                             	True
Searching For Artist Info For Jeanne Lee And Ran Blake (1528698)                	True
Searching For Artist Info For Marc Ferrer Trio (9732500)                        	True
Searching For Artist Info For Carry On (83844502)                               	True
Searching For Artist Info For Dj Tnn Boy Underfire (152643592)                  	True
Searching For Artist Info For Jeffrey Alexander and the Heavy Lidders (134876022)	True
Searching For Artist Info For Pasha Two Times (137834192)                       	True
Searching For Artist Info For Tempel NO (104479092)                             	True
Searching For Artist Info For Lyia Meta (13982601)                              	True
Searching For Artist Info For The Danish Radio Madrigal Choir (4374997)         	True
Searching For Artist Info For Proconsul (110806)                                	True
Searching For Artist Info For The Chess Allstars (5390902)                      	True
Searching For Artist Info For Patricia Kopatchinskaja (167615)                  	True
Searching For Artist Info For Yvngxchris Archive (156338822)                    	True
Searching For Artist Info For Thalita Evangelista (12360788)                    	True
Searching For Artist Info For La Relève - Le Spectacle (86948492)              	True
Searching For Artist Info For Pneuma Pierre (66493502)                          	True
Searching For Artist Info For Hull (399103)                                     	True
Searching For Artist Info For Geisha Beauty & Musica para Yoga Specialistas (14710393)	True
Searching For Artist Info For Gym Motivation DJ Team (82780412)                 	True
Searching For Artist Info For Henry Adolph, Helena Spitkova & Vienna Radio Symphony Orchestra (14627415)	True
Searching For Artist Info For Miroslav Pyatnikov, the Black See Horns, Mihail Krykalov, Miroslav Pyatnikov, Valeriy Negovora, Taras Kuznetsov, Vitaliy Fesenko, Yaroslav Parokonyev, Natalya Gavrilyuk, Georgiy Sokolov (6814793)	True
Searching For Artist Info For Odara Mello (110911422)                           	True
Searching For Artist Info For Twelve Girls Band (211195)                        	True
======================================================================================================================================================
1300/?     : Process [Getting Deezer ArtistIDs] Has Run For 47 Minutes and 4 Seconds.
Saving 376919 (New=1300) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Audible Karma (4441422)                           	True
Searching For Artist Info For The Madness of Adam (8728902)                     	True
Searching For Artist Info For Pollyanna Bush (1064387)                          	True
Searching For Artist Info For Marco Petralia, Oscar P (1312400)                 	True
Searching For Artist Info For Osanna, David Jackson (1254029)                   	True
Searching For Artist Info For Sandy and Jeanie Darlington (135996122)           	True
Searching For Artist Info For Knotts the Nomad (102151322)                      	True
Searching For Artist Info For Shapeshifter (410615)                             	True
Searching For Artist Info For Arthur Herzog Jr. (1636484)                       	True
Searching For Artist Info For Collegium musicum de strasbourg (80442292)        	True
Searching For Artist Info For Della Jones-Sir John Tomlinson-City of London Baroque Sinfonia-Simon Standage-Ian Watson-John Heley-Dorothy Linell-Richard Hickox (1471126)	True
Searching For Artist Info For Keith Coleman Walker (1136206)                    	True
Searching For Artist Info For Zillertaler Edelweiss Trio (1567185)              	True
Searching For Artist Info For Franci Blaskovic (5636885)                        	True
Searching For Artist Info For The Bachelor Dion (54253502)                      	True
Searching For Artist Info For Luh Phew (82920102)                               	True
Searching For Artist Info For The Party Accident (13251615)                     	True
Searching For Artist Info For Botika (5217806)                                  	True
Searching For Artist Info For Imogen Holst (3392691)                            	True
Searching For Artist Info For H.A.W.K. (465010)                                 	True
Searching For Artist Info For Cobalt (141579022)                                	True
Searching For Artist Info For Tender Aggression (6294106)                       	True
Searching For Artist Info For Rumberes Dels Garrotan (1266129)                  	True
Searching For Artist Info For Royal Philharmonic Orchestra-Daniell Revenaugh (1494818)	True
Searching For Artist Info For White Lies (7791592)                              	True
Searching For Artist Info For Kenji Shimada (13695701)                          	True
Searching For Artist Info For Sir Shina Adewale & His Superstars International (1347415)	True
Searching For Artist Info For Yo Gabba Gabba! (1000585)                         	True
Searching For Artist Info For Kid Weedy (14240693)                              	True
Searching For Artist Info For Bishop Steven Kelsey And The Alpha & Omega Church Fellowship (5005688)	True
Searching For Artist Info For GummiHz, Nikola Gala (1633210)                    	True
Searching For Artist Info For Jesse James and his gang (11955697)               	True
Searching For Artist Info For Nitro & Ginko Pesentan (155830912)                	True
Searching For Artist Info For To All Units (74419492)                           	True
Searching For Artist Info For Lutfiana Dewi (59172192)                          	True
Searching For Artist Info For Musica Relajante de Spa Universo (122128892)      	True
Searching For Artist Info For Cojum Dip (63772322)                              	True
Searching For Artist Info For Fight The Scene Vs Norotek (1162888)              	True
Searching For Artist Info For Sai Madhukar (5067221)                            	True
Searching For Artist Info For Ivo Kolev (5888503)                               	True
Searching For Artist Info For DjBlack CapsulaMusic (108850722)                  	True
Searching For Artist Info For Misora Hibari (4039209)                           	True
Searching For Artist Info For Christopher Deighton (10974510)                   	True
Searching For Artist Info For Rudy and the Ritz (1099729)                       	True
Searching For Artist Info For Wisteria Grove (147679512)                        	True
Searching For Artist Info For Cuco Valoy Y Su Nueva Tribu (360315)              	True
Searching For Artist Info For Chrissi Neubauer (82562092)                       	True
Searching For Artist Info For Circle City Sound (1325601)                       	True
Searching For Artist Info For Alexandra In Grey (4964016)                       	True
Searching For Artist Info For Alpha Team One (63314402)                         	True
======================================================================================================================================================
1350/?     : Process [Getting Deezer ArtistIDs] Has Run For 48 Minutes and 47 Seconds.
Saving 376969 (New=1350) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Kristiina Tanhua - Laiho (5497910)                	True
Searching For Artist Info For Matthew B. Zrebski (68041012)                     	True
Searching For Artist Info For Susy Prezioso (7660492)                           	True
Searching For Artist Info For Laget (51462592)                                  	True

Searching For Artist Info For Noiise (49078191)                                 	True
Searching For Artist Info For JØTA V (100057822)                                	True
Searching For Artist Info For The Relocators (5697292)                          	True
Searching For Artist Info For Harry Romero, Junior Sanchez, Alexander Technique (1203830)	True
Searching For Artist Info For 2 Charlies (13264819)                             	True
Searching For Artist Info For H Diz (10568191)                                  	True
Searching For Artist Info For Stefny (1232688)                                  	True
Searching For Artist Info For Maple Rose (6465521)                              	True
Searching For Artist Info For Mad Mike On the Mic (6822685)                     	True
Searching For Artist Info For Chronicles of a Fourth (92766522)                 	True
Searching For Artist Info For Johnny Paar (4212397)                             	True
Searching For Artist Info For Hidden Fangs (14386987)                           	True
Searching For Artist Info For Ricostarz Aka Anubis (111611202)                  	True
Searching For Artist Info For Calogero Palermo (5139722)                        	True
Searching For Artist Info For Hedi Alami (11476202)                             	True
Searching For Artist Info For La Mangabey Agile (9451916)                       	True
Searching For Artist Info For Snooze in Motion (157316412)                      	True
Searching For Artist Info For Osvaldo Mollo Trío Eléctrico (5413197)          	True
Searching For Artist Info For Scott Bradlee's Postmodern Jukebox feat. Haley Reinhart (7799526)	True
Searching For Artist Info For Lach's Antihoot (5123929)                         	True
Searching For Artist Info For Juan José De Mello (7498522)                     	True
Searching For Artist Info For azer123 (130782392)                               	True
Searching For Artist Info For Cecilia Bonardi-Martín Almada (78181902)         	True
Searching For Artist Info For England Dan Seals and John Ford Coley (11353322)  	True
Searching For Artist Info For Mona Lisa Overdrive (1577929)                     	True
Searching For Artist Info For Nick Pagano (4112209)                             	True
Searching For Artist Info For Katherine Kostoff (116923302)                     	True
Searching For Artist Info For Mastercab (1635526)                               	True
Searching For Artist Info For Patrick K. Crawford (87791922)                    	True
Searching For Artist Info For Chapa Dux (9695390)                               	True
Searching For Artist Info For Roswitha Müller (5913491)                        	True
Searching For Artist Info For Iván Jiménez Muzic (125251422)                  	True
Searching For Artist Info For Mexico City Orchestra (6703485)                   	True
Searching For Artist Info For Grupo Ikarus (6907503)                            	True
Searching For Artist Info For Fireball Cricket (5094706)                        	True
Searching For Artist Info For here's to the atom bomb (13548709)                	True
Searching For Artist Info For Willard Robison and His Orchestra (1323416)       	True
Searching For Artist Info For Jack & James (4987690)                            	True
Searching For Artist Info For Pashmonix (101994202)                             	True
Searching For Artist Info For Bee Moe $lim (6235884)                            	True
Searching For Artist Info For Christian Altenburger (1438319)                   	True
Searching For Artist Info For Joseph Edward Devenney (87473222)                 	True
Searching For Artist Info For Antena Mantis (14818795)                          	True
Searching For Artist Info For Curtiss Lowe & The Reverb Kings (5747815)         	True
Searching For Artist Info For Edi Furra (7260218)                               	True
Searching For Artist Info For Fatma Bou Saha (9941906)                          	True
======================================================================================================================================================
1400/?     : Process [Getting Deezer ArtistIDs] Has Run For 50 Minutes and 31 Seconds.
Saving 377019 (New=1400) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Martin Skills (431091)                            	True
Searching For Artist Info For Da Mastamind (327299)                             	True
Searching For Artist Info For MTJ Beats (114074802)                             	True
Searching For Artist Info For Malcolm Jiyane Tree-O (144279222)                 	True
Searching For Artist Info For DJ Troomark Cosmo (9199006)                       	True
Searching For Artist Info For Miriam Mandipira (9463402)                        	True
Searching For Artist Info For Julius Hemphill Quartet (5322615)                 	True
Searching For Artist Info For BP Zulauf & Isaac S (494122)                      	True
Searching For Artist Info For G.R.E.S Inocentes de Belford Roxo (7577390)       	True
Searching For Artist Info For Kush V (106817492)                                	True
Searching For Artist Info For Greetings Sugar (11142622)                        	True
Searching For Artist Info For Eddie Murray (1525585)                            	True
Searching For Artist Info For Exceeder (6174506)                                	True
Searching For Artist Info For Diegors (7417610)                                 	True
Searching For Artist Info For Next Town Down (12450300)                         	True
Searching For Artist Info For Robert Alan King (4375610)                        	True
Searching For Artist Info For Stitched Up Heart (1583595)                       	True
Searching For Artist Info For ZXX, Paul Anthony (4493591)                       	True
Searching For Artist Info For Scorpion Anw (91105712)                           	True
Searching For Artist Info For Lil Eazy-E (17302)                                	True
Searching For Artist Info For Mathias Grassow (252026)                          	True
Searching For Artist Info For Heinrich Schlusnus - Staatskapelle Berlin (1553106)	True
Searching For Artist Info For Ian Knowles (1465926)                             	True
Searching For Artist Info For Step Response (4992603)                           	True
Searching For Artist Info For Wylie Pete (14385921)                             	True
Searching For Artist Info For Gene Paul McCahill (11696515)                     	True
Searching For Artist Info For Cactus Kein (77883322)                            	True
Searching For Artist Info For Pacific Air (3899921)                             	True
Searching For Artist Info For Emerald Negassi (9192606)                         	True
Searching For Artist Info For Flyo (8554216)                                    	True
Searching For Artist Info For Astra (85780002)                                  	True
Searching For Artist Info For Jackie & Roy (185903)                             	True
Searching For Artist Info For Demeter Erika (4944793)                           	True
Searching For Artist Info For Cor Fuhler, Rhodri Davies, John Butcher, Thomas Lehn (5501390)	True
Searching For Artist Info For Lil Dug (5782891)                                 	True
Searching For Artist Info For Artist Poo X Artist UNK (126653922)               	True
Searching For Artist Info For Ty Wizz (8224822)                                 	True
Searching For Artist Info For Blø:ndi (71229592)                                	True
Searching For Artist Info For Joe Koffee (9007822)                              	True
Searching For Artist Info For Hasham (5652396)                                  	True
Searching For Artist Info For Duster Lizzie (71826192)                          	True
Searching For Artist Info For Bob Kinney (7378812)                              	True
Searching For Artist Info For King Loski Da God (15115829)                      	True
Searching For Artist Info For Arthur Lea (2883921)                              	True

Searching For Artist Info For Nick Awde & Desert Hearts (12773629)              	True
Searching For Artist Info For Dropdead Chaos (90807992)                         	True
Searching For Artist Info For Thomas Craig (10607029)                           	True
Searching For Artist Info For Samuka Climb (50261922)                           	True
Searching For Artist Info For GloBuZ (138136012)                                	True
Searching For Artist Info For [sterrekind],embryo (646110)                      	True
======================================================================================================================================================
1450/?     : Process [Getting Deezer ArtistIDs] Has Run For 52 Minutes and 16 Seconds.
Saving 377069 (New=1450) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For J. Soltero (127342812)                            	True
Searching For Artist Info For Hooli Bally (148894002)                           	True
Searching For Artist Info For Robert Feelgood and MC Pryme (2817401)            	True
Searching For Artist Info For The Seventh Sea (8216298)                         	True
Searching For Artist Info For Ali Kulture (4026726)                             	True
Searching For Artist Info For Anthony Velarde (465597)                          	True
Searching For Artist Info For The Watermelon Complex (14284129)                 	True
Searching For Artist Info For Abandon Theory (805798)                           	True
Searching For Artist Info For Mothers Nature Music Academy (7560800)            	True
Searching For Artist Info For NickaliVocals (14372615)                          	True
Searching For Artist Info For José Van Dam-Angela Gheorghiu-Roberto Alagna-London Symphony Orchestra-Antonio Pappano (1483697)	True
Searching For Artist Info For Zane Smith (10512429)                             	True
Searching For Artist Info For Scott Giri (49540022)                             	True
Searching For Artist Info For Loot Manteca (12383000)                           	True
Searching For Artist Info For Chris Santiago (1444491)                          	True
Searching For Artist Info For Asd (155451302)                                   	True
Searching For Artist Info For Tigerlily (145795512)                             	True
Searching For Artist Info For Jim Krow (14080887)                               	True
Searching For Artist Info For Trauma Particle (12994391)                        	True
Searching For Artist Info For Dead for Decades (8127015)                        	True
Searching For Artist Info For Sgt Folker (50089782)                             	True
Searching For Artist Info For Firestone-Band (366192)                           	True
Searching For Artist Info For Pete Willis (1276029)                             	True
Searching For Artist Info For Mark Laurenz (279303)                             	True
Searching For Artist Info For Black Satellite (7255718)                         	True
Searching For Artist Info For DJ Skream (4835385)                               	True
Searching For Artist Info For The Wonderland House Band (14580597)              	True
Searching For Artist Info For Gotham Viele (10989796)                           	True
Searching For Artist Info For Alvin Whitte (80539502)                           	True
Searching For Artist Info For Bavarian State Opera Orchestra (4131190)          	True
Searching For Artist Info For Our Waking Hour (5895216)                         	True
Searching For Artist Info For Domination through Impurity (564209)              	True
Searching For Artist Info For Adriana López "La Pimienta" (66221712)           	True
Searching For Artist Info For AFSHeeN (64148712)                                	True
Searching For Artist Info For Sofia Symphony Orchestra (117219)                 	True
Searching For Artist Info For Midi Mafia (638293)                               	True
Searching For Artist Info For Pavel Sorokin & Moscow Radio and TV Symphony Orchestra (8764516)	True
Searching For Artist Info For Johanna Keith & the Paradigm Crushers (15204203)  	True
Searching For Artist Info For System 3 (310987)                                 	True
Searching For Artist Info For Mind Frequency (81778192)                         	True
Searching For Artist Info For Francis el Wao (14422321)                         	True
Searching For Artist Info For Kaspar Tosin (106395212)                          	True
Searching For Artist Info For Ultimate Tribute Stars (1645416)                  	True
Searching For Artist Info For Atypic (2279721)                                  	True
Searching For Artist Info For Walt's Strings (145613422)                        	True
Searching For Artist Info For Ernesto Palerini (4627710)                        	True
Searching For Artist Info For Smit-O (54959622)                                 	True
Searching For Artist Info For Rainer Granzin (4681106)                          	True
Searching For Artist Info For Sick ALFA (79964012)                              	True
Searching For Artist Info For Enrique Rodriguez cantan Armando Moreno y Chato Flores (898310)	True
======================================================================================================================================================
1500/?     : Process [Getting Deezer ArtistIDs] Has Run For 54 Minutes and 2 Seconds.
Saving 377119 (New=1500) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For J2K (106123322)                                   	True
Searching For Artist Info For The Earl Hines Trio (2524791)                     	True
Searching For Artist Info For Chumba Lama, Anil Shahi (4518906)                 	True
Searching For Artist Info For Dean Decosta (316010)                             	True
Searching For Artist Info For Château Forte (77403122)                         	True
Searching For Artist Info For Pierce Brothers (1124821)                         	True
Searching For Artist Info For Steve Whale (8489300)                             	True
Searching For Artist Info For Nunzi (494593)                                    	True
Searching For Artist Info For 小林幸子 (10024391)                                   	True
Searching For Artist Info For DJ Favorite feat. Paula P'Cay (1600815)           	True
Searching For Artist Info For Tasneem Elaidy (116096592)                        	True
Searching For Artist Info For Alternative 4 (1473402)                           	True
Searching For Artist Info For Dive Deep (7183830)                               	True
Searching For Artist Info For JimmyBeam (12774915)                              	True
Searching For Artist Info For Joaosos (126072402)                               	True
Searching For Artist Info For Haiku Hands (10911384)                            	True
Searching For Artist Info For Homeland Security (1151686)                       	True
Searching For Artist Info For Roy Henderson (4379488)                           	True
Searching For Artist Info For Capture (97595)                                   	True
Searching For Artist Info For Li'l Millet And His Creoles (1344193)             	True
Searching For Artist Info For Halil Necipoğlu (1589197)                        	True
Searching For Artist Info For Black Traxx (4558606)                             	True
Searching For Artist Info For Declan Nerney (4096410)                           	True
Searching For Artist Info For Von Klutch (92251822)                             	True
Searching For Artist Info For Alex Sauer (2550391)                              	True
Searching For Artist Info For AMC Art Means Creation (3788291)                  	True
Searching For Artist Info For Armando Acosta y Grupo Rancho (57121922)          	True

Searching For Artist Info For Lyne Fortin, Orchestre Symphonique de Quebec (4180803)	True
Searching For Artist Info For Fredro Blue (100882982)                           	True
Searching For Artist Info For Noetic Navigator (51539912)                       	True
Searching For Artist Info For QT-Pie (57150502)                                 	True
Searching For Artist Info For Conflicted Interest (119822)                      	True
Searching For Artist Info For Matt Wonjoon Lee (5567193)                        	True
Searching For Artist Info For Clear Mind Raining (93281622)                     	True
Searching For Artist Info For Antonius (1582909)                                	True
Searching For Artist Info For Tonio Company (1360300)                           	True
Searching For Artist Info For 張為智 (82201202)                                    	True
Searching For Artist Info For The Sound Traffic Light (9578488)                 	True
Searching For Artist Info For Abdullah Salim And Mohamed Al Amer (78899092)     	True
Searching For Artist Info For Ingeborg Dalheim (6337410)                        	True
Searching For Artist Info For RC Moin (132727012)                               	True
Searching For Artist Info For Vyacheslav Guyvoronsky (4596009)                  	True
Searching For Artist Info For J Calf (77002922)                                 	True
Searching For Artist Info For Cubensis (484130)                                 	True
Searching For Artist Info For Tages Titthål (8772496)                          	True
Searching For Artist Info For Dj Khalid Music (86764392)                        	True
Searching For Artist Info For The Arcturus Light (128353622)                    	True
Searching For Artist Info For El Carbonerillo feat. Miguel Borrull (4952093)    	True
Searching For Artist Info For $hmokey Lá Puff (133433202)                      	True
Searching For Artist Info For Tune Dealer (8271006)                             	True
======================================================================================================================================================
1550/?     : Process [Getting Deezer ArtistIDs] Has Run For 55 Minutes and 54 Seconds.
Saving 377169 (New=1550) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For David Bruehwiler Quintet (8936722)                	True
Searching For Artist Info For Remembering January (8470288)                     	True
Searching For Artist Info For Tweak Tink (4955510)                              	True
Searching For Artist Info For Ars Ephemera (3649791)                            	True
Searching For Artist Info For Hillary Hahn (397915)                             	True
Searching For Artist Info For Hirtenfellner (1897921)                           	True
Searching For Artist Info For Taz & Damo (1460698)                              	True
Searching For Artist Info For Wake Up and Smell the Sun (113124822)             	True
Searching For Artist Info For Marathi DJs (147418882)                           	True
Searching For Artist Info For Jennifer McQuaid (4384987)                        	True
Searching For Artist Info For Mafe Romay (120363802)                            	True
Searching For Artist Info For Nazzy Nazz (57867122)                             	True
Searching For Artist Info For Patrick Boyd & Katherine Hill (13132603)          	True
Searching For Artist Info For Henrique Portugal (7665806)                       	True
Searching For Artist Info For If The Kids (1581191)                             	True
Searching For Artist Info For A1 Super Group (6834699)                          	True
Searching For Artist Info For SW-MM-NG (5181530)                                	True
Searching For Artist Info For Crying Freemen & Lamat (2467691)                  	True
Searching For Artist Info For Masaoka-Nunn-Robair (1281386)                     	True
Searching For Artist Info For Staatskapelle Halle (415015)                      	True
Searching For Artist Info For Network (200430)                                  	True
Searching For Artist Info For Guglielmo Brunelli, Matthew Fisher (364401)       	True
Searching For Artist Info For Frank Shipway & Philharmonia Orchestra (13794121) 	True
Searching For Artist Info For Andrew Wight (5543315)                            	True
Searching For Artist Info For Deborah Kerr (273430)                             	True
Searching For Artist Info For Reka (116080002)                                  	True
Searching For Artist Info For Marc van Der & Massai (145715)                    	True
Searching For Artist Info For R. S. Thomas (9953196)                            	True
Searching For Artist Info For Prime Creation (8974488)                          	True
Searching For Artist Info For Paul Bley Trio (94715)                            	True
Searching For Artist Info For EVO+ (5422502)                                    	True
Searching For Artist Info For Sam and the Hot Singles (68091522)                	True
Searching For Artist Info For The V.I.P.'s (108280622)                          	True
Searching For Artist Info For Kevin Di Serna (4639988)                          	True
Searching For Artist Info For Cowboy Joe West (90417992)                        	True
Searching For Artist Info For Sheco (5586019)                                   	True
Searching For Artist Info For Dj Mad (1290719)                                  	True
Searching For Artist Info For Sauerkraut. (80654222)                            	True
Searching For Artist Info For Sis. Ijeoma Arinze (1643621)                      	True
Searching For Artist Info For Safir Lamkhantar (8418188)                        	True
Searching For Artist Info For Mystro Exclusive (10388430)                       	True
Searching For Artist Info For Das Kleine Konzert (4822030)                      	True
Searching For Artist Info For Hirshee feat. Messinian (501506)                  	True
Searching For Artist Info For Guerilla Rips (6953291)                           	True
Searching For Artist Info For Falling Asleep White Noise (146509112)            	True
Searching For Artist Info For Casinonuski (67955502)                            	True
Searching For Artist Info For Het Zwols Koperensemble o.l.v. Jan Quintus Zwart - Martin Zonnenberg (54679292)	True
Searching For Artist Info For SPF 50 (90198492)                                 	True
Searching For Artist Info For Hair Dryer Soothing Noise for Relax (132068422)   	True
Searching For Artist Info For Candela Infiniti (133644082)                      	True
======================================================================================================================================================
1600/?     : Process [Getting Deezer ArtistIDs] Has Run For 57 Minutes and 48 Seconds.
Saving 377219 (New=1600) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Antti Sarpila & Opera Big Band (4472515)          	True
Searching For Artist Info For Ritual Necromancy (1544993)                       	True
Searching For Artist Info For LifeLike CO. (93838192)                           	True
Searching For Artist Info For Vicente Ferrer, T. Tommy & Victor Perez (6024896) 	True
Searching For Artist Info For No_vein_kane (100324992)                          	True
Searching For Artist Info For Les Penning (135959792)                           	True
Searching For Artist Info For Trac Lyfe (60194402)                              	True
Searching For Artist Info For The Clay Allison (92534502)                       	True
Searching For Artist Info For The New Year Project (9322030)                    	True
Searching For Artist Info For Thirsty Amigo (12845221)                          	True
Searching For Artist Info For Paul Lemos, Joe Papa (4412030)                    	True

Searching For Artist Info For Sam the Sentient (110564192)                      	True
Searching For Artist Info For Dead Peasant Society (9251610)                    	True
Searching For Artist Info For C Bass (6213006)                                  	True
Searching For Artist Info For Lølek (143333722)                                 	True
Searching For Artist Info For Evol (432615)                                     	True
Searching For Artist Info For Brahms, Pavel Egorov, Piano (4225403)             	True
Searching For Artist Info For Erotic Sexual Chill out Lounge Music Café, Chilled Club Del Mar, Celtic Harp Soundscapes (12828503)	True
Searching For Artist Info For Loverboy Ty (57362992)                            	True
Searching For Artist Info For Chris Odium (7609410)                             	True
Searching For Artist Info For Gebo Gold (14098693)                              	True
Searching For Artist Info For FLiPKiCK (72685622)                               	True
Searching For Artist Info For Second Stint (5407096)                            	True
Searching For Artist Info For Mason Maywood (126817222)                         	True
Searching For Artist Info For Naji (83125102)                                   	True
Searching For Artist Info For Bionic Monks (4727896)                            	True
Searching For Artist Info For Francisco Cirillo (71835402)                      	True
Searching For Artist Info For Tatu Kaihua & The Violent Mood Swings (58836792)  	True
Searching For Artist Info For Rizwan Wasi (5833721)                             	True
Searching For Artist Info For King Dandy Krazy (140797392)                      	True
Searching For Artist Info For Eileen Lane (5439410)                             	True
Searching For Artist Info For Successful (9927406)                              	True
Searching For Artist Info For Kaneki Djace (13294515)                           	True
Searching For Artist Info For Zazleen dan The A Street Band (8584096)           	True
Searching For Artist Info For Eve Jariya (13153997)                             	True
Searching For Artist Info For Rodica Sprinceana (1015009)                       	True
Searching For Artist Info For Icewind Tales (14605799)                          	True
Searching For Artist Info For Raymond Lauchengco (1190710)                      	True
Searching For Artist Info For The Thrillseekers Pres. Hydra (535187)            	True
Searching For Artist Info For Steve Hall & MIke Sydnor (117986322)              	True
Searching For Artist Info For Coleman Itzkoff (5519000)                         	True
Searching For Artist Info For Some Are Lonely (13477115)                        	True
Searching For Artist Info For Al Cohn, Hank Jones, Mat Mathews, Milt Hinton, Oscar Pettiford, Zoot Sims (4124186)	True
Searching For Artist Info For Reaper (350388)                                   	True
Searching For Artist Info For Pupillo (4602210)                                 	True
Searching For Artist Info For La Chapelle Royale, Les Sacqueboutiers de Toulouse, Collegium Vocale Gent and Philippe Herreweghe (4695203)	True
Searching For Artist Info For Jim Scott (1096030)                               	True
Searching For Artist Info For Ronaldo (184022)                                  	True
Searching For Artist Info For Artento Divini featuring Duvall (4479202)         	True
Searching For Artist Info For Javi Del Campo (4343915)                          	True
======================================================================================================================================================
1650/?     : Process [Getting Deezer ArtistIDs] Has Run For 59 Minutes and 50 Seconds.
Saving 377269 (New=1650) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Kid Thomas Dixieland Band (6698815)               	True
Searching For Artist Info For Timothy Richard Gilbert (10714891)                	True
Searching For Artist Info For Quantize (aka Bratz) (502491)                     	True
Searching For Artist Info For #SteezyBaby (75758582)                            	True
Searching For Artist Info For Edd Doble D (98950022)                            	True
Searching For Artist Info For Campo De Almas (4774795)                          	True
Searching For Artist Info For System-X (66615192)                               	True
Searching For Artist Info For House of Wallenberg + Polyphonics (5016310)       	True
Searching For Artist Info For ReneEx Cocodrilo (62231702)                       	True
Searching For Artist Info For Vivek Rao (49471692)                              	True
Searching For Artist Info For David Weiss & A. Caoguael Rosario (1066015)       	True
Searching For Artist Info For Le Chiard du Pêcheur (155210892)                 	True
Searching For Artist Info For Rola (478486)                                     	True
Searching For Artist Info For Franco Ambrosetti & Don Sebesky (4552526)         	True
Searching For Artist Info For Ha$e (15133801)                                   	True
Searching For Artist Info For Junior Rush (10520521)                            	True
Searching For Artist Info For Neko Savvy, pathfinder (11965091)                 	True
Searching For Artist Info For Atma Jaya Elena Vershinina (93900212)             	True
Searching For Artist Info For Jon Binnie (63936322)                             	True
Searching For Artist Info For Andy Hope (1652830)                               	True
Searching For Artist Info For Dadimeh (58542322)                                	True
Searching For Artist Info For Soldado The Emperor (147613612)                   	True
Searching For Artist Info For Introspective Ensembling (137883912)              	True
Searching For Artist Info For DJ Protein (49588292)                             	True
Searching For Artist Info For Live Tropical Fish (130619)                       	True
Searching For Artist Info For Michael Link (5428190)                            	True
Searching For Artist Info For Rick Wakeman-Fraser Thorneycroft-Smith-Phil Williams-Simon Hanson-London Symphony Orchestra-David Snell-English Chamber Choir-Guy Protheroe (1475719)	True
Searching For Artist Info For Fabio Armiliato (111319)                          	True
Searching For Artist Info For Jack Gordon-Brown (5969388)                       	True
Searching For Artist Info For Kon Sweetie (13569921)                            	True
Searching For Artist Info For Marcelo Paladini (1768821)                        	True
Searching For Artist Info For Illixium (98182292)                               	True
Searching For Artist Info For Little Rich (4224895)                             	True
Searching For Artist Info For Andrew Sixty (1634200)                            	True
Searching For Artist Info For David Steel (4076086)                             	True
Searching For Artist Info For Jeff Wilson & Ian Hudson (11814515)               	True
Searching For Artist Info For Klaus Göbel Group (48758321)                     	True
Searching For Artist Info For James Day (476384)                                	True
Searching For Artist Info For Hair Dryer Sleep Baby (62824392)                  	True
Searching For Artist Info For Starrah & Diplo (12931587)                        	True
Searching For Artist Info For Dream State Project (65648592)                    	True
Searching For Artist Info For Sore Teeth (13247315)                             	True
Searching For Artist Info For The Battles (1255015)                             	True
Searching For Artist Info For Walter Grimm + Kaspar Muther - Klarinette-Saxophon - Hanspeter Müller - Akkordeon - Armin Bruhin - Piano - Carlo Brunner - Kontrabass (1568310)	True
Searching For Artist Info For Kriya Yoga (13009203)                             	True
Searching For Artist Info For Guinga,Gabriele Mirabassi (50722992)              	True
Searching For Artist Info For Dj Dado, Light (176692)                           	True

Searching For Artist Info For Tony Fisher (1076010)                             	True
Searching For Artist Info For Orchestra e Coro del Teatro alla Scala di Milano, Raina Kabaivanska (4164306)	True
Searching For Artist Info For Dan Berglund Band (9222000)                       	True
======================================================================================================================================================
1700/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 1 Minute.
Saving 377319 (New=1700) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Green Velvet & Carl Craig (9386092)               	True
Searching For Artist Info For Marius Christiansen (287102)                      	True
Searching For Artist Info For DJ Daveed (10755386)                              	True
Searching For Artist Info For Remission (1181186)                               	True
Searching For Artist Info For Krum Osahar Disco (8801888)                       	True
Searching For Artist Info For Sara Dishart and Filthy Rich (94611022)           	True
Searching For Artist Info For Lee Anne King (4699715)                           	True
Searching For Artist Info For Anxious Club (15360015)                           	True
Searching For Artist Info For D-Cuzz Dr. Frankenstein (109643822)               	True
Searching For Artist Info For Dj Melinki (3840201)                              	True
Searching For Artist Info For Light Star (10286698)                             	True
Searching For Artist Info For SMF envolvido no Rap (60698512)                   	True
Searching For Artist Info For Carl Meeks (126502)                               	True
Searching For Artist Info For Cherry Dream (106580512)                          	True
Searching For Artist Info For Mad Grinder (5627915)                             	True
Searching For Artist Info For LIL SOC (1123499)                                 	True
Searching For Artist Info For Eloise Freud (103225992)                          	True
Searching For Artist Info For Rahul Dev Burman (183210)                         	True
Searching For Artist Info For Engage At Will (1430322)                          	True
Searching For Artist Info For DJ Charly Le Boss (7507030)                       	True
Searching For Artist Info For Afrojuice 195 & Fyahbwoy (49593892)               	True
Searching For Artist Info For Rx Hector (79621102)                              	True
Searching For Artist Info For Pandemic Records (13913015)                       	True
Searching For Artist Info For Kharma (1074084)                                  	True
Searching For Artist Info For Omara Portuondo Y Orquesta Todos Estrellas (992191)	True
Searching For Artist Info For Elke Sommer (176809)                              	True
Searching For Artist Info For Urple (51921292)                                  	True
Searching For Artist Info For Ral Donner (363300)                               	True
Searching For Artist Info For Rick Restanques (200615)                          	True
Searching For Artist Info For Gail Randolph-Williams (79381312)                 	True
Searching For Artist Info For Chœur des XVI (6509903)                           	True
Searching For Artist Info For Aggressive Perfector (13216491)                   	True
Searching For Artist Info For Mardi Lumsden and the Rising Seas (69422202)      	True
Searching For Artist Info For Protect This City (63773992)                      	True
Searching For Artist Info For Pavel Kudinov (5549122)                           	True
Searching For Artist Info For Trioxin and the Zombies (15151703)                	True
Searching For Artist Info For The Eric Bell Band (133734292)                    	True
Searching For Artist Info For Bad Move (61430602)                               	True
Searching For Artist Info For Jeffrey Dahmer (12552822)                         	True
Searching For Artist Info For BLK OPS (150636492)                               	True
Searching For Artist Info For Kendell Linh Healy (1133710)                      	True
Searching For Artist Info For M.A.M.F (4526197)                                 	True
Searching For Artist Info For Arizona Duce (12899515)                           	True
Searching For Artist Info For Tidal Waves (82066502)                            	True
Searching For Artist Info For Hood Milk Overdose (62476222)                     	True
Searching For Artist Info For Abstinent Dazzle (14170415)                       	True
Searching For Artist Info For Wrong Destiny (7040991)                           	True
Searching For Artist Info For Topi Jerami (8145188)                             	True
Searching For Artist Info For L5 Project (5430797)                              	True
Searching For Artist Info For O.L.D.E.R (11372906)                              	True
======================================================================================================================================================
1750/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 3 Minutes.
Saving 377369 (New=1750) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Of Fact and Fiction (8433088)                     	True
Searching For Artist Info For Tim Whitehead (1045595)                           	True
Searching For Artist Info For Teddy Davis (4134190)                             	True
Searching For Artist Info For Lars Juling (13407493)                            	True
Searching For Artist Info For Darnell Da'Bachelor (60717682)                    	True
Searching For Artist Info For The Mose Allison Trio (453510)                    	True
Searching For Artist Info For Alan Peterson (4548484)                           	True
Searching For Artist Info For Djoko Doncev (4163197)                            	True
Searching For Artist Info For Ego Mondo (77006312)                              	True
Searching For Artist Info For Joe Rock Orchestra (4238009)                      	True
Searching For Artist Info For Circ Money (8862330)                              	True
Searching For Artist Info For 회사AUTO (5549119)                                	True
Searching For Artist Info For JL Ortega (12201906)                              	True
Searching For Artist Info For Amon & Audra (6788491)                            	True
Searching For Artist Info For Zubi (127931622)                                  	True
Searching For Artist Info For Scott Larson (7735396)                            	True
Searching For Artist Info For Wow and Flutter (2343191)                         	True
Searching For Artist Info For Nandy Rosario (5026615)                           	True
Searching For Artist Info For J Kenzo (4379322)                                 	True
Searching For Artist Info For DJ QUYET BIM (95301102)                           	True
Searching For Artist Info For Jon Eberson (362810)                              	True
Searching For Artist Info For GUT (121451002)                                   	True
Searching For Artist Info For No Turning Back Music (101736222)                 	True
Searching For Artist Info For Douglas Takeuchi (71725722)                       	True
Searching For Artist Info For Sgt. Friday (118279592)                           	True
Searching For Artist Info For Declan James (10383900)                           	True
Searching For Artist Info For WorldbyTray (73037402)                            	True
Searching For Artist Info For John W. Stevenson and Christ Emmanuel Christian Fellowship (1112422)	True
Searching For Artist Info For Sgt Wumbo (106884192)                             	True
Searching For Artist Info For Dan I Locks (4657797)                             	True
Searching For Artist Info For Moudry, the Wise, storyteller (1115503)           	True

Searching For Artist Info For Patrik Jean (7462884)                             	True
Searching For Artist Info For Ants Soots (10500093)                             	True
Searching For Artist Info For Supa Fly Nice (10524515)                          	True
Searching For Artist Info For Roger Horton & Slippy Beats (10322098)            	True
Searching For Artist Info For Urban DJ Massacre (1526491)                       	True
Searching For Artist Info For boNObo-trio (1669019)                             	True
Searching For Artist Info For Tsukasa Yatoki (1413615)                          	True
Searching For Artist Info For Chaar Yaar (13073815)                             	True
Searching For Artist Info For X'cuse Me (9870288)                               	True
Searching For Artist Info For Mr Gil,Marcelo Adami, Vinny Andrade (13046815)    	True
Searching For Artist Info For Nathan McNinch (63709)                            	True
Searching For Artist Info For Flying Pooh (55084)                               	True
Searching For Artist Info For Craig Bannon & Alex Bannon (5674188)              	True
Searching For Artist Info For Illi V (57563292)                                 	True
Searching For Artist Info For LinBit & Miss Monique (12488030)                  	True
Searching For Artist Info For Maggot Casket (15124115)                          	True
Searching For Artist Info For Uncle Dezza (96660112)                            	True
Searching For Artist Info For Paolo Donnarumma (4552696)                        	True
Searching For Artist Info For Por Fuera (61903622)                              	True
======================================================================================================================================================
1800/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 5 Minutes.
Saving 377419 (New=1800) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Altar of Flies (5808709)                          	True
Searching For Artist Info For Modo Banja (15276591)                             	True
Searching For Artist Info For Shit & Chalou (326115)                            	True
Searching For Artist Info For Grupo Fuera de Serie de Chino Ramirez (81758222)  	True
Searching For Artist Info For Hiu (12327486)                                    	True
Searching For Artist Info For Onirik (89682622)                                 	True
Searching For Artist Info For Rue Anarchy (12555386)                            	True
Searching For Artist Info For Música Baby Blue (13650021)                      	True
Searching For Artist Info For Peter Knight (1287619)                            	True
Searching For Artist Info For Babies Calming Driving Car (133778302)            	True
Searching For Artist Info For White Noise Project (9986392)                     	True
Searching For Artist Info For Tennessee Performing Arts Center Teaching Artists & Rachel Sumner (1434706)	True
Searching For Artist Info For THA-Flair (86833002)                              	True
Searching For Artist Info For Slim Birdie (60115282)                            	True
Searching For Artist Info For Alt 441 (76592622)                                	True
Searching For Artist Info For Avant Gardener (5291100)                          	True
Searching For Artist Info For Dmbq (Davidson Murley Braid Quintet) (11975695)   	True
Searching For Artist Info For Leo Seeger (341522)                               	True
Searching For Artist Info For Bombardier soldat (73358792)                      	True
Searching For Artist Info For Classy Prana Yoga (128811022)                     	True
Searching For Artist Info For Finn Savery (80519)                               	True
Searching For Artist Info For Angie Corine (77141422)                           	True
Searching For Artist Info For Ian the Calf (72690192)                           	True
Searching For Artist Info For Pepe G (5904091)                                  	True
Searching For Artist Info For Touching the Void (4105488)                       	True
Searching For Artist Info For Woogie Boogie (1703487)                           	True
Searching For Artist Info For Snoop (291721)                                    	True
Searching For Artist Info For Kapta (63218512)                                  	True
Searching For Artist Info For Jay Mauve (96477702)                              	True
Searching For Artist Info For Jimmy Moliere (109586)                            	True
Searching For Artist Info For Julius Aston (12742487)                           	True
Searching For Artist Info For Police Play Eggs (14029703)                       	True
Searching For Artist Info For 再循環 (Recycle) (4305488)                           	True
Searching For Artist Info For The Programme (13369621)                          	True
Searching For Artist Info For Ardi cor Mio Ensemble (7905130)                   	True
Searching For Artist Info For Wildcookie (1052903)                              	True
Searching For Artist Info For Valerie Errante (1345791)                         	True
Searching For Artist Info For Robert Pain (2271791)                             	True
Searching For Artist Info For Cal-A (10199730)                                  	True
Searching For Artist Info For Patrick Richmond (13003509)                       	True
Searching For Artist Info For Median Lafayette (49250392)                       	True
Searching For Artist Info For Joe Donnermann (80357592)                         	True
Searching For Artist Info For The Jazz Butcher Conspiracy (3935891)             	True
Searching For Artist Info For Tompall Glaser (4174122)                          	True
Searching For Artist Info For La Même Galère (88660092)                       	True
Searching For Artist Info For Nikander Khanayev (4360000)                       	True
Searching For Artist Info For Adrien Rux (9854406)                              	True
Searching For Artist Info For Abbi Press (7953930)                              	True
Searching For Artist Info For Philip Bader, Nicone & Sascha Braemer (5464615)   	True
Searching For Artist Info For Paige Elizabeth Powell (5586886)                  	True
======================================================================================================================================================
1850/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 6 Minutes.
Saving 377469 (New=1850) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For MC Martins da VR (67034022)                       	True
Searching For Artist Info For Lana Del Tigre & Marcus Schmahl (1869601)         	True
Searching For Artist Info For Bernard Lubat (400126)                            	True
Searching For Artist Info For R-D-V (14115615)                                  	True
Searching For Artist Info For Santo Clã (8424986)                              	True
Searching For Artist Info For Angiee (5468386)                                  	True
Searching For Artist Info For Affkt (801616)                                    	True
Searching For Artist Info For Peter Rauhofer (98530)                            	True
Searching For Artist Info For Thomas Dill (5949022)                             	True
Searching For Artist Info For Rontray (7991510)                                 	True
Searching For Artist Info For Forme! (13802191)                                 	True
Searching For Artist Info For Johnnie Walker (424701)                           	True
Searching For Artist Info For Sir Thomas Allen-Patricia Payne-Maria Bovino-Gillian Webster-Stuart Kale-Stafford Dean-Sarah Walker-Neil Jenkins-Simon Keenlyside-Chorus of the Royal Opera House, Covent Garden-Orchestra of the Royal Opera House, Covent Garden-Bernard Haiti (5283519)	True

Searching For Artist Info For Ewa Poblocka (3020191)                            	True
Searching For Artist Info For Pollyanna Prosser (149118602)                     	True
Searching For Artist Info For John Hunter, Jr. (54281502)                       	True
Searching For Artist Info For Horizonte 011 (85362002)                          	True
Searching For Artist Info For Richard E. Carpenter (4610206)                    	True
Searching For Artist Info For The Learning Station (1501198)                    	True
Searching For Artist Info For Marathon Men (328110)                             	True
Searching For Artist Info For Quartette Tres Bien (192930)                      	True
Searching For Artist Info For David del Puerto (4644130)                        	True
Searching For Artist Info For Hidden Technique (98313322)                       	True
Searching For Artist Info For Nigger Kojak (4912903)                            	True
Searching For Artist Info For Lyle Stutzman (71708322)                          	True
Searching For Artist Info For Apex Sound (13631809)                             	True
Searching For Artist Info For Cris Strife (91163622)                            	True
Searching For Artist Info For Huthaifa Al Safir (90893382)                      	True
Searching For Artist Info For Soli (147345122)                                  	True
Searching For Artist Info For Shishani (6742999)                                	True
Searching For Artist Info For The Knickerbockers (154510)                       	True
Searching For Artist Info For Bruce The Third (126171022)                       	True
Searching For Artist Info For Soprano Sax Jazz Groove (129052282)               	True
Searching For Artist Info For Raydaroadrunna (124025222)                        	True
Searching For Artist Info For Exodus Obadiah (141260392)                        	True
Searching For Artist Info For Mathias Heise (7143703)                           	True
Searching For Artist Info For Peter Presta & Little Carlos (1125093)            	True
Searching For Artist Info For Rashad B (12490930)                               	True
Searching For Artist Info For Vile Kings (1715621)                              	True
Searching For Artist Info For Shikisha Vibe (56779482)                          	True
Searching For Artist Info For The Lurid Yellow Mist (713126)                    	True
Searching For Artist Info For Queen Meme (52530592)                             	True
Searching For Artist Info For Spread Eagle Sound System (15059601)              	True
Searching For Artist Info For Jonas Wolf (8136910)                              	True
Searching For Artist Info For J SNELL (9196690)                                 	True
Searching For Artist Info For Stefano Battaglia Standards Quartet (146351002)   	True
Searching For Artist Info For Jet Black Camaro (4335988)                        	True
Searching For Artist Info For Cat Music Dreams (53809222)                       	True
Searching For Artist Info For Mango Idem (68665192)                             	True
Searching For Artist Info For C'buda M (11105486)                               	True
======================================================================================================================================================
1900/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 8 Minutes.
Saving 377519 (New=1900) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Melvin M. Miller (8343586)                        	True
Searching For Artist Info For Wallingford Riegger (3313121)                     	True
Searching For Artist Info For Dj Duro featuring The Prophet (4095203)           	True
Searching For Artist Info For Five Beans In The Wheel (143238322)               	True
Searching For Artist Info For Octopus Rise (156877692)                          	True
Searching For Artist Info For Starchild. (74241422)                             	True
Searching For Artist Info For Alex Rap (138269582)                              	True
Searching For Artist Info For Azuma Madoka (9139400)                            	True
Searching For Artist Info For LIL WIZO ᴼᴿᴵᴳᴵᴻᴬᴸ (142143902)                     	True
Searching For Artist Info For Sub Wookie (114890322)                            	True
Searching For Artist Info For Jackie Estick (1696991)                           	True
Searching For Artist Info For M.t.c. (1705196)                                  	True
Searching For Artist Info For Sharaton (11260916)                               	True
Searching For Artist Info For Trap Starz Clik (1703910)                         	True
Searching For Artist Info For Sweet 6teen (13807219)                            	True
Searching For Artist Info For Ma'alot Quintet (1668615)                         	True
Searching For Artist Info For Dennis Yost & The Classics IV (438226)            	True
Searching For Artist Info For Back in 83 (8349230)                              	True
Searching For Artist Info For Aramis 83 (7626330)                               	True
Searching For Artist Info For Naomi (10836916)                                  	True
Searching For Artist Info For Electric Monolith (14844115)                      	True
Searching For Artist Info For ManMachine (541586)                               	True
Searching For Artist Info For Hannu Kause (244086)                              	True
Searching For Artist Info For Jaws Unhinged (90254702)                          	True
Searching For Artist Info For Wayne Marshall-Lars Vogt-Georg Faust-Wolfram Christ-Berliner Philharmoniker-Claudio Abbado (1476486)	True
Searching For Artist Info For Dj Seroff (2914191)                               	True
Searching For Artist Info For Nelson Siboza & The Montanas Brothers (6709109)   	True
Searching For Artist Info For Home Workouts Music Zone (7724206)                	True
Searching For Artist Info For The Funky T (53252122)                            	True
Searching For Artist Info For Nouthong Phimvilayphone: Music From Laos, Nouthong Phimvilayphone, Nouphiene Mahavong, Khampa Intisane, Tem Mahavong, Sengphet Souryavongxai (4483591)	True
Searching For Artist Info For Enzo Faleiro (4460387)                            	True
Searching For Artist Info For Adnan Sanni (5453021)                             	True
Searching For Artist Info For Anton Shelepov (8093793)                          	True
Searching For Artist Info For Andrea Toschi, Roberto Noferini (4450892)         	True
Searching For Artist Info For Lourdes Liss (9155898)                            	True
Searching For Artist Info For 108 Torrey (139934322)                            	True
Searching For Artist Info For Slide Hampton Quintet, Cedar Walton, David Williams, Billy Higgens (1240295)	True
Searching For Artist Info For Paula Robison & Samuel Sanders (5951430)          	True
Searching For Artist Info For Mind Blown (150752922)                            	True
Searching For Artist Info For Alberto Fracasso (141610)                         	True
Searching For Artist Info For Les Héritiers de Dieu (89163692)                 	True
Searching For Artist Info For Laura Black and Daybreak (1130192)                	True
Searching For Artist Info For Roshan Jamrock (4993296)                          	True
Searching For Artist Info For Brain Donor (Julian Cope) (2361891)               	True
Searching For Artist Info For Trace Sphere (7545230)                            	True
Searching For Artist Info For Rizzo (72393192)                                  	True
Searching For Artist Info For Luis el Siervo Calix (7184706)                    	True
Searching For Artist Info For Bleek & Sputnik (4554015)                         	True
Searching For Artist Info For Hellfish Metal (52740702)                         	True
Searching For Artist Info For Eli... (101922282)                                	True
======================================================================================================================================================
1950/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 10 Minutes.
Saving 377569 (New=1950) Deezer Searched For Artist (Info) IDs

======================================================================================================================================================
Searching For Artist Info For James Snowdon Harris (1139486)                    	True
Searching For Artist Info For John Lanigan (4533386)                            	True
Searching For Artist Info For Frank Schiller (4461395)                          	True
Searching For Artist Info For Torsten Scholz (4424422)                          	True
Searching For Artist Info For Ditterich von Euler-Donnersperg (131277602)       	True
Searching For Artist Info For Hava (94821602)                                   	True
Searching For Artist Info For Zeu Dee (152401122)                               	True
Searching For Artist Info For Jungle Weed (10615015)                            	True
Searching For Artist Info For Debonaire and Darxid (4847603)                    	True
Searching For Artist Info For Shira Wtf (51403922)                              	True
Searching For Artist Info For Jerry Douglas, V. M. Bhatt and Edgar Mayer (2455491)	True
Searching For Artist Info For Zoux, Luca Ricci (816215)                         	True
Searching For Artist Info For Asthro (4554186)                                  	True
Searching For Artist Info For Kicking Fences (114170692)                        	True
Searching For Artist Info For Jochen Wiegandt und Lars Linek (4069891)          	True
Searching For Artist Info For Cassy Lou (119271712)                             	True
Searching For Artist Info For The Newman & Oltman Guitar Duo with Turtle Island String Quartet (1111415)	True
Searching For Artist Info For DJ Fede B (49708922)                              	True
Searching For Artist Info For Modern Machines (1152815)                         	True
Searching For Artist Info For Clark Bentley (5200987)                           	True
Searching For Artist Info For Soupir Hate (11513093)                            	True
Searching For Artist Info For DR. DRTY (91341822)                               	True
Searching For Artist Info For Benny Braham (125140822)                          	True
Searching For Artist Info For Colder Months (97018112)                          	True
Searching For Artist Info For Walton Green (84870422)                           	True
Searching For Artist Info For En-Vitro (109799702)                              	True
Searching For Artist Info For Jamie Carpenter featuring Ciaran Warren (3513201) 	True
Searching For Artist Info For Dumb Instrument (1332315)                         	True
Searching For Artist Info For Cold_da_Beats (118936912)                         	True
Searching For Artist Info For Marc Jay (4015991)                                	True
Searching For Artist Info For Ömer Dut (139055092)                             	True
Searching For Artist Info For Karrnnel Sawitsky (7670310)                       	True
Searching For Artist Info For Andy Compton's Sowetan Onesteps (7798790)         	True
Searching For Artist Info For Marc Reason & Tom Belmond Ft. (10363988)          	True
Searching For Artist Info For Bias Tees (4031188)                               	True
Searching For Artist Info For Isidore (1494387)                                 	True
Searching For Artist Info For While (492997)                                    	True
Searching For Artist Info For Start a Revolution (4262299)                      	True
Searching For Artist Info For Mr. Ice Ed Robinson (8645884)                     	True
Searching For Artist Info For PS DJz (8622422)                                  	True
Searching For Artist Info For Tolerance Tierre (8072091)                        	True
Searching For Artist Info For Johnny Lee Starkey (134925412)                    	True
Searching For Artist Info For Loalwa Braz (85103)                               	True
Searching For Artist Info For Kaleb James (2288)                                	True
Searching For Artist Info For MBS Reese (79700002)                              	True
Searching For Artist Info For The Sword City (56768812)                         	True
Searching For Artist Info For M.B.$ (91459902)                                  	True
Searching For Artist Info For redrose the breed (54830312)                      	True
Searching For Artist Info For Elena Gruschka (63807822)                         	True
Searching For Artist Info For Aleksey Styopin (6363988)                         	True
======================================================================================================================================================
2000/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 12 Minutes.
Saving 377619 (New=2000) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For DJ VinS (5479206)                                 	True
Searching For Artist Info For A.Zangheri (vla), G.Zoffoli (cello), E.Francioni (db) (1169515)	True
Searching For Artist Info For Sidney Dominici (5426619)                         	True
Searching For Artist Info For Tix Maniquin (9469906)                            	True
Searching For Artist Info For Crysto Martyr (68185192)                          	True
Searching For Artist Info For Jeremy Marcell V (81471582)                       	True
Searching For Artist Info For Our Neighbour the King (10127226)                 	True
Searching For Artist Info For Lazarus Kane (74122022)                           	True
Searching For Artist Info For My Favorite Demons (132246022)                    	True
Searching For Artist Info For Ittai Shapira-Charles Hazlewood-English Chamber Orchestra (1499993)	True
Searching For Artist Info For Sleep Friendly Music (152553002)                  	True
Searching For Artist Info For Carlos Felipe Martell (127978682)                 	True
Searching For Artist Info For Niko Tsonev (1518015)                             	True
Searching For Artist Info For KJ Denhert (647701)                               	True
Searching For Artist Info For Wach (1460701)                                    	True
Searching For Artist Info For Lig Music (13105215)                              	True
Searching For Artist Info For Bert Lucarelli, Susan Jolles, Paul Posnak, Er'ella Talmi, Malcolm Frager, A. Vardi, Prague Symphony Orchestra, Israel Chamber Orchestra, J. Belohlavek, Dalia Atlas (489387)	True
Searching For Artist Info For Mr. Low-D (10460597)                              	True
Searching For Artist Info For C. Tangana & Sticky M.A. (11283286)               	True
Searching For Artist Info For Ajad Laddla (147560492)                           	True
Searching For Artist Info For Hail, Mary (14750899)                             	True
Searching For Artist Info For MisterSiCc (14828521)                             	True
Searching For Artist Info For Phil Lesh & Friends (79795)                       	True
Searching For Artist Info For Chelsea Lawson (154003022)                        	True
Searching For Artist Info For Shalu Kanchan (14364599)                          	True
Searching For Artist Info For There are no more four seasons (5794796)          	True
Searching For Artist Info For Tin Tin Out (215095)                              	True
Searching For Artist Info For Bob Scott (489786)                                	True
Searching For Artist Info For DJ Johnny Jonajwa (6416498)                       	True
Searching For Artist Info For Young & Company (1405615)                         	True
Searching For Artist Info For Blue Giant (535130)                               	True
Searching For Artist Info For Dave Wright (108026)                              	True
Searching For Artist Info For Prana Yoga Moments (128795192)                    	True
Searching For Artist Info For The Vertex (1444595)                              	True
Searching For Artist Info For Millionaire Louie (54766622)                      	True
Searching For Artist Info For Phil Reynolds and the Indigo Children (8677126)   	True

Searching For Artist Info For nico gomez de prana (104347892)                   	True
Searching For Artist Info For Orchestra Sinfonica di San Remo (12364226)        	True
Searching For Artist Info For The last night's late show (92763012)             	True
Searching For Artist Info For Sacha Robotti (1368190)                           	True
Searching For Artist Info For Halim Talahari (534522)                           	True
Searching For Artist Info For Relative Claws (15003391)                         	True
Searching For Artist Info For Jaye Jackson (81971102)                           	True
Searching For Artist Info For Verbo Capital (14002909)                          	True
Searching For Artist Info For Fiammetta Poidomani (121624222)                   	True
Searching For Artist Info For Genius of the Ignition (9774812)                  	True
Searching For Artist Info For Copycat (173015)                                  	True
Searching For Artist Info For Vazco (12882915)                                  	True
Searching For Artist Info For Eddy Wata (13115)                                 	True
Searching For Artist Info For Takeshi Asai (5469595)                            	True
======================================================================================================================================================
2050/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 14 Minutes.
Saving 377669 (New=2050) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For AX `N SEX-IVORY TOWER (1551701)                   	True
Searching For Artist Info For Takers (1335210)                                  	True
Searching For Artist Info For Sally Mosher, Anthony Brazier (1097700)           	True
Searching For Artist Info For Iowa (113561422)                                  	True
Searching For Artist Info For Fya Skeptic (1049006)                             	True
Searching For Artist Info For Dhsu (6861219)                                    	True
Searching For Artist Info For John Davidson (305100)                            	True
Searching For Artist Info For Leo Holmgren Trio (990115)                        	True
Searching For Artist Info For NDA Music (112159522)                             	True
Searching For Artist Info For Joan Pedroso SKB (116629512)                      	True
Searching For Artist Info For Crispy Newspaper (14771419)                       	True
Searching For Artist Info For Pomme Bleu (14840415)                             	True
Searching For Artist Info For ヒゲドライバー Hige Driver (3510921)                  	True
Searching For Artist Info For Heinrich Koebberling Quartet (5011230)            	True
Searching For Artist Info For BTOB-BLUE (11059330)                              	True
Searching For Artist Info For Dim Spirit (97681912)                             	True
Searching For Artist Info For Spacer (452686)                                   	True
Searching For Artist Info For Mama Butane (12306802)                            	True
Searching For Artist Info For Doug Sahm Tex Mex Trip (253415)                   	True
Searching For Artist Info For Roland Justice (5478898)                          	True
Searching For Artist Info For Timothy Bogart Carmine Appice (13213791)          	True
Searching For Artist Info For Remnants of Winter (7623210)                      	True
Searching For Artist Info For Primordial Jazz Funktet (1321610)                 	True
Searching For Artist Info For Rick James (85045122)                             	True
Searching For Artist Info For Mitchy Katawazi (15226409)                        	True
Searching For Artist Info For Harris Tweed (1376621)                            	True
Searching For Artist Info For Raíssa Durand (55929482)                         	True
Searching For Artist Info For Adri SZ (51202512)                                	True
Searching For Artist Info For Toshizo Shiraishi (4030996)                       	True
Searching For Artist Info For Richard Allen McGee (60461202)                    	True
Searching For Artist Info For Ravindra Akela (48973091)                         	True
Searching For Artist Info For Yannic Geerts (7262110)                           	True
Searching For Artist Info For Hoje Pode Amor (61313912)                         	True
Searching For Artist Info For Abdo Rajna (108082322)                            	True
Searching For Artist Info For Mike Waldron (10663803)                           	True
Searching For Artist Info For Dorinda Clark Cole (393184)                       	True
Searching For Artist Info For Tushar Dutta (93584)                              	True
Searching For Artist Info For Omnerod (66728402)                                	True
Searching For Artist Info For Ewing sima (12557610)                             	True
Searching For Artist Info For Solo_Fre (15348599)                               	True
Searching For Artist Info For Jesus Leon (1278488)                              	True
Searching For Artist Info For Swen Van Der Endt (4545130)                       	True
Searching For Artist Info For A$P (78278492)                                    	True
Searching For Artist Info For Josman TB (110165202)                             	True
Searching For Artist Info For Jesper Lundgaard (1625730)                        	True
Searching For Artist Info For Moulay Noureddine (10857200)                      	True
Searching For Artist Info For Husk Oscillations (119489422)                     	True
Searching For Artist Info For Krmoni (138457192)                                	True
Searching For Artist Info For P.S. 211 (11946591)                               	True
Searching For Artist Info For Roberto Ávila (13192601)                         	True
======================================================================================================================================================
2100/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 15 Minutes.
Saving 377719 (New=2100) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Ryuzo (452701)                                    	True
Searching For Artist Info For T-jin (6297830)                                   	True
Searching For Artist Info For Yousa (91213592)                                  	True
Searching For Artist Info For Chihiro Yamazaki+Route14Band (7564730)            	True
Searching For Artist Info For Socalled feat. Fred Wesley, Subtitle, and David Krakauer (4314310)	True
Searching For Artist Info For Madam Trauma (13913899)                           	True
Searching For Artist Info For D. Ray McClellan (4627630)                        	True
Searching For Artist Info For Formal Process (111253822)                        	True
Searching For Artist Info For Morgen Jazz Romantik (125088802)                  	True
Searching For Artist Info For Indigo Husk (7694306)                             	True
Searching For Artist Info For Jeff Spooner (1753891)                            	True
Searching For Artist Info For Abe Lincoln (1038410)                             	True
Searching For Artist Info For Bobby Joe King & The Foxxetts (4379000)           	True
Searching For Artist Info For Gangster lov' (1642102)                           	True
Searching For Artist Info For Jo Mannish (59618992)                             	True
Searching For Artist Info For Paul Hardy & McKai (4438488)                      	True
Searching For Artist Info For JV-1 (113361722)                                  	True
Searching For Artist Info For Adam Pultz Melbye (5226296)                       	True
Searching For Artist Info For FP+ (6712791)                                     	True
Searching For Artist Info For The Miniature Vannigans (124775292)               	True

Searching For Artist Info For John Fanny Adams (58376492)                       	True
Searching For Artist Info For Mike O'Donnell (5159902)                          	True
Searching For Artist Info For G-Nomo (5108130)                                  	True
Searching For Artist Info For Lenny Larusso (13309301)                          	True
Searching For Artist Info For Mermelada Squad (81229982)                        	True
Searching For Artist Info For Jungle Wonz (172291)                              	True
Searching For Artist Info For McQueen Adams (74954282)                          	True
Searching For Artist Info For Greek Folk Children's Choir (1314884)             	True
Searching For Artist Info For Smalltown Collective (STC) (4267403)              	True
Searching For Artist Info For Jeebz (5486602)                                   	True
Searching For Artist Info For Gu e Offbeat (8508102)                            	True
Searching For Artist Info For Broad Run Mutiny (63398292)                       	True
Searching For Artist Info For The Maureen Ponderosa Wedding Massacre (152239982)	True
Searching For Artist Info For R&E (1192726)                                     	True
Searching For Artist Info For Morgen Jazz Klassiker (122498402)                 	True
Searching For Artist Info For Lito Fontana - Fausto Quintabà - Hans Gansch (5005406)	True
Searching For Artist Info For Golden Fleece (5003003)                           	True
Searching For Artist Info For Alan Peet (11542391)                              	True
Searching For Artist Info For David Moliner (96166902)                          	True
Searching For Artist Info For Trail of Lies (11063986)                          	True
Searching For Artist Info For Stylus & Anipsal (12191526)                       	True
Searching For Artist Info For Young HOSS (5016915)                              	True
Searching For Artist Info For Meck Check (106422002)                            	True
Searching For Artist Info For Détendu Royale (61822522)                        	True
Searching For Artist Info For Sudeshna Bhattacharya (1927701)                   	True
Searching For Artist Info For DJ Fede Sevi (5818906)                            	True
Searching For Artist Info For Mr Manyao (3090521)                               	True
Searching For Artist Info For David & Lisa Loden (5569195)                      	True
Searching For Artist Info For Silence in Machine (14639829)                     	True
Searching For Artist Info For Gerd Schmidt (4503027)                            	True
======================================================================================================================================================
2150/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 17 Minutes.
Saving 377769 (New=2150) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Chris Niers (5642425)                             	True
Searching For Artist Info For Symbolic Representation (12784513)                	True
Searching For Artist Info For Intimate Voices (4697488)                         	True
Searching For Artist Info For Ingram Washington (386211)                        	True
Searching For Artist Info For Wonky Kong (103407012)                            	True
Searching For Artist Info For Blisargon Demogorgon (377697)                     	True
Searching For Artist Info For P Supreme Aka Jay Epps (14727011)                 	True
Searching For Artist Info For Dunny Kamakazi (49882902)                         	True
Searching For Artist Info For Colin Ruel (5024285)                              	True
Searching For Artist Info For Moscow State College of Frederic Chopin and Moscow Polytechnic University Choir (12412090)	True
Searching For Artist Info For Zenith DJ (1271514)                               	True
Searching For Artist Info For Blackout JA & Timbali (14777913)                  	True
Searching For Artist Info For Entropía 11.7.10 (13227489)                      	True
Searching For Artist Info For Nerve Agent (568921)                              	True
Searching For Artist Info For Z'R'R (74212282)                                  	True
Searching For Artist Info For Rey Three Latino (9988222)                        	True
Searching For Artist Info For Dúmbala Canalla (1441414)                        	True
Searching For Artist Info For Lung's poetry (149118912)                         	True
Searching For Artist Info For The Missing Pieces (146344902)                    	True
Searching For Artist Info For Ryan Leigh Patterson (13759093)                   	True
Searching For Artist Info For José Carlos Escobar Becerra (65649292)           	True
Searching For Artist Info For Joseph Hill (258194)                              	True
Searching For Artist Info For Fred Blak (57796022)                              	True
Searching For Artist Info For Royal Philharmonic Orchestra-Alfredo Kraus-Renato Bruson-Nicola Rescigno-Edita Gruberova-Robert Lloyd-Bonaventura Bottone-Kathleen Kuhlmann-Ambrosian Opera Chorus-John McCarthy (1481988)	True
Searching For Artist Info For Mos Generator (1115625)                           	True
Searching For Artist Info For Plato's Republic (1176216)                        	True
Searching For Artist Info For Detroit People Mover (164026)                     	True
Searching For Artist Info For V REWIND (67565492)                               	True
Searching For Artist Info For Toya Ohako (127495012)                            	True
Searching For Artist Info For Ironwood Chamber Ensemble (10393218)              	True
Searching For Artist Info For Your Symptom of Illusion (93604592)               	True
Searching For Artist Info For Red Hourglass (122720102)                         	True
Searching For Artist Info For Dan Lomax (6358094)                               	True
Searching For Artist Info For Stephen Reck (5036698)                            	True
Searching For Artist Info For Original Rap Staff (1239689)                      	True
Searching For Artist Info For Omar Tesla (103623222)                            	True
Searching For Artist Info For Buyuchek (8590798)                                	True
Searching For Artist Info For DJ Cor Fijneman (1577314)                         	True
Searching For Artist Info For Hiroe Yonekawa (4252726)                          	True
Searching For Artist Info For L.A White (7883318)                               	True
Searching For Artist Info For Feest DJ Barry & Feest DJ Maarten (10751802)      	True
Searching For Artist Info For Mika Ella (59578222)                              	True
Searching For Artist Info For Morgan Thomaso (14370485)                         	True
Searching For Artist Info For Choker (61121022)                                 	True
Searching For Artist Info For Tyra Lee (12189592)                               	True
Searching For Artist Info For Mc Guto Zk (107092202)                            	True
Searching For Artist Info For Dominic Saunders (4360806)                        	True
Searching For Artist Info For Oliver Amaya (127233892)                          	True
Searching For Artist Info For Jeshi (86529392)                                  	True
Searching For Artist Info For SHOULD BE BAPTIZED (150408722)                    	True
======================================================================================================================================================
2200/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 19 Minutes.
Saving 377819 (New=2200) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Lalo Medina Y Sus Chavaloz (110815202)            	True
Searching For Artist Info For There should be clans (145240822)                 	True
Searching For Artist Info For EmanMane (64152512)                               	True

Searching For Artist Info For Dextro Amphetamines (157505722)                   	True
Searching For Artist Info For D Young (5640118)                                 	True
Searching For Artist Info For Renegade Twelve (7349606)                         	True
Searching For Artist Info For Dronny Darko & Erico Wakamatsu (84657222)         	True
Searching For Artist Info For Torqux & Twist (1432803)                          	True
Searching For Artist Info For Fred Everything & Shur-I-Kan (4075929)            	True
Searching For Artist Info For Gob Patrol (99648322)                             	True
Searching For Artist Info For August Jaresch (2151711)                          	True
Searching For Artist Info For Γρηγόρης Μπιθικώτσης (5424503)                  	True
Searching For Artist Info For God Invert Hero (105100602)                       	True
Searching For Artist Info For Mai Tuyết (68951392)                            	True
Searching For Artist Info For Cheb Kader Wahrani (84656902)                     	True
Searching For Artist Info For i'103 (66886582)                                  	True
Searching For Artist Info For Iron Pessary (156609192)                          	True
Searching For Artist Info For Eva B (111880902)                                 	True
Searching For Artist Info For La Jaula de Faraday (72492922)                    	True
Searching For Artist Info For Lem Fowler with Helen Baxter (4119525)            	True
Searching For Artist Info For Kay D (6749329)                                   	True
Searching For Artist Info For Kansas City Prophets (1182721)                    	True
Searching For Artist Info For Jardo SK (148321802)                              	True
Searching For Artist Info For D-Spawn (54436192)                                	True
Searching For Artist Info For Clarence James (52632202)                         	True
Searching For Artist Info For Xbusta (12370914)                                 	True
Searching For Artist Info For Dario Moreno (68414)                              	True
Searching For Artist Info For Gummy Bear Squad (53294302)                       	True
Searching For Artist Info For Da Real Big Tony (142863322)                      	True
Searching For Artist Info For Teethgrynder (71661822)                           	True
Searching For Artist Info For Runfunk-Sinfonie-Orchester (5906989)              	True
Searching For Artist Info For Wolfire (8781804)                                 	True
Searching For Artist Info For TAB Collective (121293692)                        	True
Searching For Artist Info For Vontay Galaxy (12887287)                          	True
Searching For Artist Info For Ocean Waves (1194416)                             	True
Searching For Artist Info For Angels of Trance (1155304)                        	True
Searching For Artist Info For Bastian Harper, Kevin Iszard (4941613)            	True
Searching For Artist Info For TELEPATHIC LOVE (140344682)                       	True
Searching For Artist Info For Unity 5tet (7228304)                              	True
Searching For Artist Info For House Heart Attack (134540192)                    	True
Searching For Artist Info For Fluxion A-D (52824002)                            	True
Searching For Artist Info For Wartime Bloom (71992912)                          	True
Searching For Artist Info For Martin Prokeš (51325512)                         	True
Searching For Artist Info For Lobo Y Melon (97088)                              	True
Searching For Artist Info For Los Polkeros de Ben Tavera King (302421)          	True
Searching For Artist Info For Failure of Lunacy (113838092)                     	True
Searching For Artist Info For Winnie martin (4455816)                           	True
Searching For Artist Info For Josh Osho (864526)                                	True
Searching For Artist Info For Roesy (261014)                                    	True
Searching For Artist Info For Mira Zakai (4633009)                              	True
======================================================================================================================================================
2250/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 21 Minutes.
Saving 377869 (New=2250) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Unholy Alliance (6665116)                         	True
Searching For Artist Info For Andreas Vau (80934782)                            	True
Searching For Artist Info For Hiten Bachani (100558322)                         	True
Searching For Artist Info For JFK (251304)                                      	True
Searching For Artist Info For George Sanders And The Parallels (129302502)      	True
Searching For Artist Info For Choco Yoyo (13945395)                             	True
Searching For Artist Info For TGE I$E (50441222)                                	True
Searching For Artist Info For El Salvage (87617322)                             	True
Searching For Artist Info For Dieselle May (10462911)                           	True
Searching For Artist Info For Only Vantage (50519712)                           	True
Searching For Artist Info For Mr Big (317198)                                   	True
Searching For Artist Info For Donkey (838594)                                   	True
Searching For Artist Info For Lovelyz (7163922)                                 	True
Searching For Artist Info For Dj Caltrop (385383)                               	True
Searching For Artist Info For The New York City Boyz (11309798)                 	True
Searching For Artist Info For luciano lima show (151736612)                     	True
Searching For Artist Info For Exis Perellis (66363102)                          	True
Searching For Artist Info For Expo Beach (83912592)                             	True
Searching For Artist Info For Geoffroy Colson (777516)                          	True
Searching For Artist Info For Replica X (122003692)                             	True
Searching For Artist Info For Malik-B (5229402)                                 	True
Searching For Artist Info For Starman Jones (5543314)                           	True
Searching For Artist Info For Andy Cohen & Jack Radcliffe (6375492)             	True
Searching For Artist Info For LVCK SWAG (81619822)                              	True
Searching For Artist Info For Morgan Powers (12732519)                          	True
Searching For Artist Info For Abandon (214921)                                  	True
Searching For Artist Info For Erphun (377296)                                   	True
Searching For Artist Info For EXAUDI (4680923)                                  	True
Searching For Artist Info For D Bo (5541485)                                    	True
Searching For Artist Info For Jeremy J-Bob Porter (155781902)                   	True
Searching For Artist Info For Frankye Lova & Luigi Gori (52638392)              	True
Searching For Artist Info For Frisky K (11711725)                               	True
Searching For Artist Info For Yasin Oruç (64657892)                            	True
Searching For Artist Info For Pino Minafra Quintet (4340321)                    	True
Searching For Artist Info For Fudge in the Fridge (49963602)                    	True
Searching For Artist Info For LaTheGoat (92720092)                              	True
Searching For Artist Info For Dennis "Shango Trex" Llewellyn (1589326)          	True
Searching For Artist Info For Erif Yob (154943411)                              	True
Searching For Artist Info For Nick Cooper (451303)                              	True
Searching For Artist Info For Steve Sanx (4164891)                              	True
Searching For Artist Info For Aleya Dao and Barry Goldstein (4736518)           	True
Searching For Artist Info For Chicco Green (1191186)                            	True
Searching For Artist Info For M.A.C. (1123204)                                  	True

Searching For Artist Info For Luces Ahí (141541022)                            	True
Searching For Artist Info For Sorry, no sympathy (7414704)                      	True
Searching For Artist Info For Ethereal (72399)                                  	True
Searching For Artist Info For Buckle Bunny (103486092)                          	True
Searching For Artist Info For AmaIia Rodriguez (48952191)                       	True
Searching For Artist Info For Mussilini (494012)                                	True
Searching For Artist Info For A.A.A (5892516)                                   	True
======================================================================================================================================================
2300/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 22 Minutes.
Saving 377919 (New=2300) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Rajindra Kosik (13303323)                         	True
Searching For Artist Info For DJ Ino & Jesus Gonsev (311113)                    	True
Searching For Artist Info For Just Another Lie (55812102)                       	True
Searching For Artist Info For Joey P. (8090425)                                 	True
Searching For Artist Info For Kurt Rydl-Claire Powell-Staatskapelle Dresden-Bernard Haitink (1496494)	True
Searching For Artist Info For Filippo Trecca (5802126)                          	True
Searching For Artist Info For Savina Giannatou (79985)                          	True
Searching For Artist Info For Paul Markas (73682322)                            	True
Searching For Artist Info For J-Ha (13634513)                                   	True
Searching For Artist Info For Elika Mahony, Fiona Doomun (1169791)              	True
Searching For Artist Info For Mohammed Azram and Liaqat Ali Sadiq (7027385)     	True
Searching For Artist Info For Patrick Warren (7083389)                          	True
Searching For Artist Info For Black Rain II (6901285)                           	True
Searching For Artist Info For DO, the Outcast (51027702)                        	True
Searching For Artist Info For Dreem Teem (1983791)                              	True
Searching For Artist Info For M.A.C.J (83899022)                                	True
Searching For Artist Info For Brothers Bellamy (11534119)                       	True
Searching For Artist Info For Murat Sancak (89989482)                           	True
Searching For Artist Info For The Ayoub Sisters (11517029)                      	True
Searching For Artist Info For Dantiez Saunderson and Van Czar (10808602)        	True
Searching For Artist Info For Toxic Carnage (11642283)                          	True
Searching For Artist Info For Asmr Sleep Sounds (11118600)                      	True
Searching For Artist Info For FP Dibala (13357993)                              	True
Searching For Artist Info For Big Joe Williams (5429)                           	True
Searching For Artist Info For Karla Vosmanská-Bajerová (8934114)              	True
Searching For Artist Info For Steve Frank, Prince Of Thieves , Uberjak'd (3680621)	True
Searching For Artist Info For Scott Morgan (2334611)                            	True
Searching For Artist Info For Trenier (4630987)                                 	True
Searching For Artist Info For FSA: Freakshow Assassins (73179902)               	True
Searching For Artist Info For Howie B. Baldwin (8647698)                        	True
Searching For Artist Info For Da' $leepers Elite (125326422)                    	True
Searching For Artist Info For Bad Boy Bill (7611)                               	True
Searching For Artist Info For Death Injected Black Metal (11704089)             	True
Searching For Artist Info For Kamil Hála & Czechoslovak Radio Jazz Orchestra (4921906)	True
Searching For Artist Info For JMP Da ProBeat (123613412)                        	True
Searching For Artist Info For Vogler Quartett (713212)                          	True
Searching For Artist Info For East West Connection (11629)                      	True
Searching For Artist Info For Los Primos de la Baja (14979599)                  	True
Searching For Artist Info For DJ Dyce Gambeanz (79688602)                       	True
Searching For Artist Info For Chris Da Funk & Nastik (1207911)                  	True
Searching For Artist Info For Black Bob (1644700)                               	True
Searching For Artist Info For Martin and Scott (152507292)                      	True
Searching For Artist Info For Humantronic (131102)                              	True
Searching For Artist Info For Fiction Framework (1165904)                       	True
Searching For Artist Info For Punjab Singh Manila (56596722)                    	True
Searching For Artist Info For George Mraz Trio (8443114)                        	True
Searching For Artist Info For Rooler & Sefa (13725329)                          	True
Searching For Artist Info For Manolo Caracol (113998)                           	True
Searching For Artist Info For Daniel Carter, Morgan Craft, Eric Eigner (1170419)	True
Searching For Artist Info For Anthony Griffith (795006)                         	True
======================================================================================================================================================
2350/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 24 Minutes.
Saving 377969 (New=2350) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Worp (5403321)                                    	True
Searching For Artist Info For Careless 061 (153911302)                          	True
Searching For Artist Info For Brian, Tony Gold (4191322)                        	True
Searching For Artist Info For Harrison Katz-James (102179902)                   	True
Searching For Artist Info For Kwame Bediako (1131713)                           	True
Searching For Artist Info For Rev. Emmett Dickinson (125792)                    	True
Searching For Artist Info For Indoor Cats (51214792)                            	True
Searching For Artist Info For Deantoni Parks (3551291)                          	True
Searching For Artist Info For Jango Rut (1327594)                               	True
Searching For Artist Info For Kidd Havok (1927921)                              	True
Searching For Artist Info For Elly Ameling-Toyohiko Satoh (1594489)             	True
Searching For Artist Info For Tonka Boy Dre (4674426)                           	True
Searching For Artist Info For Jab Vix (13238987)                                	True
Searching For Artist Info For Le Materie Prime (149125122)                      	True
Searching For Artist Info For Taeyang Kim (12001826)                            	True
Searching For Artist Info For Kim Sjøgren & Lars Hannibal (15165013)            	True
Searching For Artist Info For O.N.E. Bad Luck (74613622)                        	True
Searching For Artist Info For Goddess Dorthea (119410302)                       	True
Searching For Artist Info For Ecos de Siboney (434390)                          	True
Searching For Artist Info For Felicity Lott & Graham Johnson (4219495)          	True
Searching For Artist Info For Outphase (47284812)                               	True
Searching For Artist Info For Suomi Laulaa (78167592)                           	True
Searching For Artist Info For Rachel Porter (1298485)                           	True
Searching For Artist Info For The Ninth Departure (97186222)                    	True
Searching For Artist Info For Bleeder Resistor (7321704)                        	True
Searching For Artist Info For Ronald Vanhuffel (4611521)                        	True
Searching For Artist Info For DC Suggs (73110012)                               	True

Searching For Artist Info For Science From Svn (4687918)                        	True
Searching For Artist Info For Howling North (10818892)                          	True
Searching For Artist Info For Homer Rodeheaver & Wiseman Sextet (7845802)       	True
Searching For Artist Info For José Antonio Méndez Garcia (1220883)            	True
Searching For Artist Info For G Lock (4833122)                                  	True
Searching For Artist Info For Me & The Heat (8738002)                           	True
Searching For Artist Info For Lil Bot (14460309)                                	True
Searching For Artist Info For Pegboard Nerds & Tristam (4736118)                	True
Searching For Artist Info For DJ DMD featuring Pimp C of UGK (4945304)          	True
Searching For Artist Info For Johnny Bernero And Thurman Enlow (4150814)        	True
Searching For Artist Info For Orchestre National de Lorraine (426288)           	True
Searching For Artist Info For Mukesh Pushkar (70146982)                         	True
Searching For Artist Info For Flexx Gotti (14208197)                            	True
Searching For Artist Info For Paul Mars (80722292)                              	True
Searching For Artist Info For ZXZ Ghost (72456022)                              	True
Searching For Artist Info For Leonid (286516)                                   	True
Searching For Artist Info For Zack Taylor (6517889)                             	True
Searching For Artist Info For Syna vs Ayleon (1379203)                          	True
Searching For Artist Info For Alexia Bosch (9830098)                            	True
Searching For Artist Info For Miguel Martinez Villatoro (11116122)              	True
Searching For Artist Info For The Deli Boys (82836722)                          	True
Searching For Artist Info For Christopher Roppolo (66180602)                    	True
Searching For Artist Info For B-Side Bob (11671389)                             	True
======================================================================================================================================================
2400/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 26 Minutes.
Saving 378019 (New=2400) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Louis on the run (94449192)                       	True
Searching For Artist Info For Eddy Smets & Letty Lanca (8629726)                	True
Searching For Artist Info For Alexu$ (102468992)                                	True
Searching For Artist Info For Belle Haven (6691421)                             	True
Searching For Artist Info For Dennis Pugsley (5482414)                          	True
Searching For Artist Info For Rio Clemente (99585)                              	True
Searching For Artist Info For Burial Ground for Butterflies (124444282)         	True
Searching For Artist Info For Tom Edward Douglas Johnson (14059123)             	True
Searching For Artist Info For Los Coyotes de Cañada Honda (9963890)            	True
Searching For Artist Info For Public Policy (9931594)                           	True
Searching For Artist Info For The Alan Williams Project (56631192)              	True
Searching For Artist Info For Tiger Charmer (13874285)                          	True
Searching For Artist Info For White Noise Radiance (67304522)                   	True
Searching For Artist Info For Arek Gulbenkoglu (97532392)                       	True
Searching For Artist Info For Jan "Trana" Svensson (4328222)                    	True
Searching For Artist Info For Heartbreak Remedy (6474293)                       	True
Searching For Artist Info For Lord Have Mercy On Us (12097814)                  	True
Searching For Artist Info For Noel McGhie Afro-Caribbean Project (50841092)     	True
Searching For Artist Info For Tommy Duncan & Bill Woods' Orchestra (5679003)    	True
Searching For Artist Info For G Blizzy (138599422)                              	True
Searching For Artist Info For Lys, Francesco Banchini, Louisa John-krol (4483698)	True
Searching For Artist Info For The Irish Rebels (3778411)                        	True
Searching For Artist Info For Safire Musiq (157470622)                          	True
Searching For Artist Info For Space Vision Inc (102406322)                      	True
Searching For Artist Info For Azz Izz Band (108492)                             	True
Searching For Artist Info For Daso & Franklin de Costa (275216)                 	True
Searching For Artist Info For The Paparazzi Kids (5914399)                      	True
Searching For Artist Info For NDM Zay (115744522)                               	True
Searching For Artist Info For Chris Decay & Re-lay (4046101)                    	True
Searching For Artist Info For Vivabiancaluna Biffi (5271686)                    	True
Searching For Artist Info For Fausto Papetti Vol 6 (337021)                     	True
Searching For Artist Info For Tilly (144829412)                                 	True
Searching For Artist Info For Stream_error (13834103)                           	True
Searching For Artist Info For Samuel Blaser (393223)                            	True
Searching For Artist Info For MakeFlame (12110594)                              	True
Searching For Artist Info For SxSxCxBx (81351222)                               	True
Searching For Artist Info For Morgsch (91326022)                                	True
Searching For Artist Info For Jackie Edwards & Judy Mowatt (1388314)            	True
Searching For Artist Info For Emirhan Er (106469802)                            	True
Searching For Artist Info For Duderstadt feat. Hannah Ray (4158213)             	True
Searching For Artist Info For Monty Adkins (206386)                             	True
Searching For Artist Info For Nasihat (10489919)                                	True
Searching For Artist Info For Honor of Kings (145745612)                        	True
Searching For Artist Info For Yb. (59980492)                                    	True
Searching For Artist Info For Manna De (106104)                                 	True
Searching For Artist Info For Trash Poll (120724092)                            	True
Searching For Artist Info For Václav Snítil (3337411)                         	True
Searching For Artist Info For Eddie James & Colourblind (5269321)               	True
Searching For Artist Info For The Dream Frontier (80384712)                     	True
Searching For Artist Info For Amzbeat, Mike Rüsche (1588007)                   	True
======================================================================================================================================================
2450/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 28 Minutes.
Saving 378069 (New=2450) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Botzy (809490)                                    	True
Searching For Artist Info For J A Z Z Y B A R E (83507192)                      	True
Searching For Artist Info For Purple Witch of Culver (105558982)                	True
Searching For Artist Info For Thierry Ollé (6972485)                           	True
Searching For Artist Info For Gabriel Slow (5049613)                            	True
Searching For Artist Info For Not Interested. Not Available (146565492)         	True
Searching For Artist Info For Luis Conde (75829922)                             	True
Searching For Artist Info For Maur 2x (154265692)                               	True
Searching For Artist Info For Haakon Stotijn (4797996)                          	True
Searching For Artist Info For Shofu tha BeatDown (11290912)                     	True
Searching For Artist Info For Lowercase G (146630222)                           	True

Searching For Artist Info For Winston Wright (361614)                           	True
Searching For Artist Info For Houses With Wisteria (138937822)                  	True
Searching For Artist Info For Diane Barger (5637711)                            	True
Searching For Artist Info For Love Jones 86 (81940922)                          	True
Searching For Artist Info For Neuqua Valley High School Chamber Strings (4759396)	True
Searching For Artist Info For O.G Spanish Fly (1246903)                         	True
Searching For Artist Info For Mane Tane (7171318)                               	True
Searching For Artist Info For Juan Morales y los Garcia (79139822)              	True
Searching For Artist Info For Icky Rogers (13471711)                            	True
Searching For Artist Info For Pendofsky (5852292)                               	True
Searching For Artist Info For Thomas Swieringa (5490521)                        	True
Searching For Artist Info For Indianraga (7670714)                              	True
Searching For Artist Info For Franck Further (177112)                           	True
Searching For Artist Info For Usurp The Throne (12257206)                       	True
Searching For Artist Info For Ibarra Zound$ (119635922)                         	True
Searching For Artist Info For Jhony Kei (104763322)                             	True
Searching For Artist Info For Lex French Quartet with James Muller (12521612)   	True
Searching For Artist Info For Clark Gable Ent (104812902)                       	True
Searching For Artist Info For Survival (306311)                                 	True
Searching For Artist Info For Toshi Amonita (64604222)                          	True
Searching For Artist Info For Sleep Hairdryer & Fan & Airplane Baby Sounds (62751512)	True
Searching For Artist Info For HipHop Norway (5121894)                           	True
Searching For Artist Info For Clouded Chris (13079511)                          	True
Searching For Artist Info For Firmino Mendes (141270312)                        	True
Searching For Artist Info For Emph N Treats (58822812)                          	True
Searching For Artist Info For Ryan Dragon (8125329)                             	True
Searching For Artist Info For Australian Blonde feat. Steve Wynn (5040221)      	True
Searching For Artist Info For Sylvester Effiong (8892806)                       	True
Searching For Artist Info For Ulf & Flu Anagram Band (157751122)                	True
Searching For Artist Info For Baddiel (4974890)                                 	True
Searching For Artist Info For Asg Boyz (140235622)                              	True
Searching For Artist Info For Misguided Aggression (4895713)                    	True
Searching For Artist Info For Daniel Levin Quartet (4383607)                    	True
Searching For Artist Info For CODEINE CHRI$ (150050322)                         	True
Searching For Artist Info For Viggo Larsson (110098022)                         	True
Searching For Artist Info For Dmitry Evgrafov (8624214)                         	True
Searching For Artist Info For Frans Vester (1374786)                            	True
Searching For Artist Info For Low the Great (12335992)                          	True
Searching For Artist Info For Dillon McCartney (4713114)                        	True
======================================================================================================================================================
2500/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 30 Minutes.
Saving 378119 (New=2500) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Kingfish (85861602)                               	True
Searching For Artist Info For Alexander Hernandez Mares (69732522)              	True
Searching For Artist Info For Apostle J.L. Cash & Praise (7643718)              	True
Searching For Artist Info For When Harry Tries To Marry & Sarah Sharp (1214804) 	True
Searching For Artist Info For Maurice Sawin (13992607)                          	True
Searching For Artist Info For Paul Lee (2272411)                                	True
Searching For Artist Info For Ace Boogie (998429)                               	True
Searching For Artist Info For Lola Rhodes (9223586)                             	True
Searching For Artist Info For Tiara Nicole (1032493)                            	True
Searching For Artist Info For Illy Baze (11846529)                              	True
Searching For Artist Info For Marjorie Mange (5810592)                          	True
Searching For Artist Info For L-Duke (4852604)                                  	True
Searching For Artist Info For Kateřina Zezulová (15313183)                    	True
Searching For Artist Info For Lemur Voice (1266712)                             	True
Searching For Artist Info For Yuno Barz (76140092)                              	True
Searching For Artist Info For Prong & Earth (110406702)                         	True
Searching For Artist Info For Simone Anés (993729)                             	True
Searching For Artist Info For Emma Platais (15004497)                           	True
Searching For Artist Info For Mi Nemesis (9246086)                              	True
Searching For Artist Info For Handsome Jimmy Jr (7173314)                       	True
Searching For Artist Info For Exceptional Movers (95288902)                     	True
Searching For Artist Info For Audio Abuse (62833022)                            	True
Searching For Artist Info For Herman D. Koppel (1245921)                        	True
Searching For Artist Info For VooDooSon (5837902)                               	True
Searching For Artist Info For Kara Lodger (109795592)                           	True
Searching For Artist Info For Child of Animus (103524812)                       	True
Searching For Artist Info For Pandit Shivkumar Sharma - Santur, Ustad Shafaat Ahmed Khan - Tabla (4185200)	True
Searching For Artist Info For Dorotea Dumenčić (60123992)                     	True
Searching For Artist Info For Dmitri Kitaenko (447318)                          	True
Searching For Artist Info For L'blend (153459482)                               	True
Searching For Artist Info For JME (79950722)                                    	True
Searching For Artist Info For Difarina Adella (148055682)                       	True
Searching For Artist Info For Smart Metal Hornets (8441602)                     	True
Searching For Artist Info For Yurie Sampaio (73306402)                          	True
Searching For Artist Info For Ignacio Herbojo (8467306)                         	True
Searching For Artist Info For Cardo King (15167229)                             	True
Searching For Artist Info For Citizens of Nowhere (73779212)                    	True
Searching For Artist Info For High Velocity (8057013)                           	True
Searching For Artist Info For Wonderboy! (127848312)                            	True
Searching For Artist Info For Ben Zimmermann (60860302)                         	True
Searching For Artist Info For Rishi Karunesh (100749722)                        	True
Searching For Artist Info For Barbara Bonney-Anne Sofie von Otter-Kurt Streit-Olaf Bär-Bengt Forsberg-Helmut Deutsch (242601)	True
Searching For Artist Info For Eiji Kitamura (1380185)                           	True
Searching For Artist Info For DJ Rane (1600790)                                 	True
Searching For Artist Info For Grave Harlequin (148870402)                       	True
Searching For Artist Info For Peter Neumann, Christoph Pregardien, Christoph Prégardien, Diana Montague, Michael Chance, Collegium Cartusianum Köln & Kölner Kammerchor (62982502)	True
Searching For Artist Info For The Rebel Pebbles (1348229)                       	True
Searching For Artist Info For J. Willie Walker III (7818988)                    	True
Searching For Artist Info For Minion Craig (144875792)                          	True

Searching For Artist Info For Da Le (Havana) (108737402)                        	True
======================================================================================================================================================
2550/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 31 Minutes.
Saving 378169 (New=2550) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Jukka Heino (5286309)                             	True
Searching For Artist Info For Hippy Swizzy (14212497)                           	True
Searching For Artist Info For Cyclic Bounce Theorem (1606426)                   	True
Searching For Artist Info For Electromagnetic Impulses (464392)                 	True
Searching For Artist Info For Chinatown House (10578999)                        	True
Searching For Artist Info For Marzz (89312992)                                  	True
Searching For Artist Info For Afaar (1337911)                                   	True
Searching For Artist Info For Made famous by Edward Maya (4185593)              	True
Searching For Artist Info For Stuart Harling (4568904)                          	True
Searching For Artist Info For Фактор Давления (99270682)                        	True
Searching For Artist Info For Gustavo Marques & Pororocas (1235902)             	True
Searching For Artist Info For Hydra Music Orchestra (12160788)                  	True
Searching For Artist Info For Diego y La Uni-K (5412012)                        	True
Searching For Artist Info For Eugene Zuta (10428004)                            	True
Searching For Artist Info For Pterrordactyl - Death from Above (13298829)       	True
Searching For Artist Info For D.K. Jayaraman (4527600)                          	True
Searching For Artist Info For OTM Champ (89808822)                              	True
Searching For Artist Info For Iraj Lashkary (5272016)                           	True
Searching For Artist Info For Akhil Kalidasan (57892822)                        	True
Searching For Artist Info For Cade Ellis (11602903)                             	True
Searching For Artist Info For Chico Holiday (4210700)                           	True
Searching For Artist Info For Lantz (5651085)                                   	True
Searching For Artist Info For Kate Ashby (4692992)                              	True
Searching For Artist Info For Frenkie Schinkels + Marlena Martinelli (5356696)  	True
Searching For Artist Info For SAWED OFF PERIOD (7004121)                        	True
Searching For Artist Info For Smoov G (9558414)                                 	True
Searching For Artist Info For Isiah Whatley (8788702)                           	True
Searching For Artist Info For Pharaoh Overlord (2571821)                        	True
Searching For Artist Info For Emilie Mathilde (113450892)                       	True
Searching For Artist Info For Caprice the New Youngin' (99534792)               	True
Searching For Artist Info For Brothers Of The Mind, Pal Joey (654306)           	True
Searching For Artist Info For Cry My Name (4950685)                             	True
Searching For Artist Info For Nod Ensemble (7998418)                            	True
Searching For Artist Info For Cokie the Clown (59069902)                        	True
Searching For Artist Info For A.C.R.E. (2544011)                                	True
Searching For Artist Info For Kumar Shankar (8339286)                           	True
Searching For Artist Info For Shoji Yoshioka (94039792)                         	True
Searching For Artist Info For The Winds Of Genocide (7449688)                   	True
Searching For Artist Info For Ella Klis (1532729)                               	True
Searching For Artist Info For No Plan B (557202)                                	True
Searching For Artist Info For Møster-Parker-Abrams-Herndon (13535207)           	True
Searching For Artist Info For Yoshihide Beppu (128484582)                       	True
Searching For Artist Info For Popper & DJ Styla (3152511)                       	True
Searching For Artist Info For Najee The 1 (2065421)                             	True
Searching For Artist Info For The Tile (76091212)                               	True
Searching For Artist Info For A Jangi Reddy (12121894)                          	True
Searching For Artist Info For Black Parrot (58965922)                           	True
Searching For Artist Info For Sauce Gaad (103412902)                            	True
Searching For Artist Info For Becky Dellow (14811513)                           	True
Searching For Artist Info For El Che (254804)                                   	True
======================================================================================================================================================
2600/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 33 Minutes.
Saving 378219 (New=2600) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For White Doze Noise Looped (158680112)               	True
Searching For Artist Info For MMM Henrxck (117181192)                           	True
Searching For Artist Info For Philharmonia Slavonica, Eugen Duvier and Soloists and Choir of the Bratislava State Opera (1970791)	True
Searching For Artist Info For Vicky Tatu (156405392)                            	True
Searching For Artist Info For K-KUMA (58771492)                                 	True
Searching For Artist Info For Pedro Teixeira Silva (13561321)                   	True
Searching For Artist Info For Grim Reaper Players (1444529)                     	True
Searching For Artist Info For Tonio Tamarel (150014)                            	True
Searching For Artist Info For Paul B ThaMartian (100770122)                     	True
Searching For Artist Info For Gibin (67627792)                                  	True
Searching For Artist Info For GtBeatz (92461992)                                	True
Searching For Artist Info For Temptation Within Reach (7892118)                 	True
Searching For Artist Info For Boog The Bandit (94488812)                        	True
Searching For Artist Info For Cheeky Doll (102149292)                           	True
Searching For Artist Info For A Rocket's Intensity (4803126)                    	True
Searching For Artist Info For T.k. Soul (1076882)                               	True
Searching For Artist Info For Torro Lee (85559102)                              	True
Searching For Artist Info For Brown Boy White Boy (4730598)                     	True
Searching For Artist Info For Art Club (9758604)                                	True
Searching For Artist Info For Pablo Calamari, Navajo (10361592)                 	True
Searching For Artist Info For Papy Pengo (3722091)                              	True
Searching For Artist Info For Twisted Reaction (268021)                         	True
Searching For Artist Info For Visão Noturna (113164922)                        	True
Searching For Artist Info For Martin Larsson (3023521)                          	True
Searching For Artist Info For Andrea Echeverri and Hector Buitrago (5285614)    	True
Searching For Artist Info For DJ Izzy (15233097)                                	True
Searching For Artist Info For yarn. (118034992)                                 	True
Searching For Artist Info For Kee BenJi (155030792)                             	True
Searching For Artist Info For Aran Angmar (115994502)                           	True
Searching For Artist Info For Recycled Loops (1565913)                          	True
Searching For Artist Info For Alex Arenas (5216085)                             	True
Searching For Artist Info For Robe el Arsenal (74861092)                        	True
Searching For Artist Info For Mayfly Entrusts (116136302)                       	True

Searching For Artist Info For Duo Chalber Strick (1567316)                      	True
Searching For Artist Info For Sr. Janai (8146004)                               	True
Searching For Artist Info For Nigel Kennedy-Tomasz Grzegorski-Adam Kowalewski-Krzysztof Dziedzic-Xantoné Blacq (1485885)	True
Searching For Artist Info For Simon Shaheen and Vishwa Mohan Bhatt (2456311)    	True
Searching For Artist Info For GRL CHAT (57719022)                               	True
Searching For Artist Info For Bruno Motta,Zonatto, Di Morais (59060792)         	True
Searching For Artist Info For David Bennett Thomas (3407611)                    	True
Searching For Artist Info For Osvaldo Requena y Leopoldo Federico (118229)      	True
Searching For Artist Info For Rebecca Martin (81411)                            	True
Searching For Artist Info For Gary Jones Jr (102841122)                         	True
Searching For Artist Info For Roc Hunter (1182519)                              	True
Searching For Artist Info For Senzo C. (13824203)                               	True
Searching For Artist Info For Chopper aka "Young City" (5535222)                	True
Searching For Artist Info For Caper John (146548322)                            	True
Searching For Artist Info For Albion Country Band (272216)                      	True
Searching For Artist Info For Carl B pres. Khensu (468600)                      	True
Searching For Artist Info For Re_Al Living Legends (68562622)                   	True
======================================================================================================================================================
2650/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 35 Minutes.
Saving 378269 (New=2650) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Lil Djp (119743192)                               	True
Searching For Artist Info For lucas m!ller (149779002)                          	True
Searching For Artist Info For Young CED (4124009)                               	True
Searching For Artist Info For Navvi Upside (13423385)                           	True
Searching For Artist Info For Danni el Poeta (11081094)                         	True
Searching For Artist Info For Freddy Fader (6629)                               	True
Searching For Artist Info For Just Four Men (4193704)                           	True
Searching For Artist Info For Lost Soul (CH) (15087829)                         	True
Searching For Artist Info For Mz. Moxy (5786919)                                	True
Searching For Artist Info For Sir Malcolm Sargent, Eric Chadwick, James Milligan, Alan Stringer & Royal Liverpool Philharmonic Orchestra (13434187)	True
Searching For Artist Info For Double-O Brazy (131658622)                        	True
Searching For Artist Info For Biggy See (86231492)                              	True
Searching For Artist Info For Davina (148806)                                   	True
Searching For Artist Info For Slim Linton (4221929)                             	True
Searching For Artist Info For Gunnar Nyborg-Jensen piger og drenge (14822813)   	True
Searching For Artist Info For Franko Donatello (11492214)                       	True
Searching For Artist Info For GewandhausChor Leipzig (5565326)                  	True
Searching For Artist Info For Banda Guadalajara Express (98009)                 	True
Searching For Artist Info For KM (68763892)                                     	True
Searching For Artist Info For Aidan Brennan (11679821)                          	True
Searching For Artist Info For Richard Barrett & The Chantels (4192416)          	True
Searching For Artist Info For The City of Rome Contemporary Music Ensemble (11580325)	True
Searching For Artist Info For Medicina Moksha (13229913)                        	True
Searching For Artist Info For Darksynth (70167822)                              	True
Searching For Artist Info For Zone (74093102)                                   	True
Searching For Artist Info For Kiave (69809)                                     	True
Searching For Artist Info For Beat Funktion (5760214)                           	True
Searching For Artist Info For Death Snail (93899292)                            	True
Searching For Artist Info For Cyclops (4377309)                                 	True
Searching For Artist Info For AshesSucks (143339892)                            	True
Searching For Artist Info For The Royal Philharmonic Chamber Ensemble (4079798) 	True
Searching For Artist Info For Chopper beatz. (140185922)                        	True
Searching For Artist Info For Guido Mazzon Sextet (4504794)                     	True
Searching For Artist Info For Enigma (2402)                                     	True
Searching For Artist Info For Suzie LeBlanc-Teatro Lirico-Stephen Stubbs (1485029)	True
Searching For Artist Info For a_social_engineer (136103292)                     	True
Searching For Artist Info For Joshua Serrao (117795912)                         	True
Searching For Artist Info For Big Loco (5165811)                                	True
Searching For Artist Info For Mark Gray Band (10009906)                         	True
Searching For Artist Info For FELA! Original Broadway Cast (7470712)            	True
Searching For Artist Info For Sean Thomas and the Ha-Ha's (4259309)             	True
Searching For Artist Info For Stard Ova (5334014)                               	True
Searching For Artist Info For Bread and Water, Inc. (128805922)                 	True
Searching For Artist Info For Markino Latino D.J. (5649287)                     	True
Searching For Artist Info For Béné (137771402)                                	True
Searching For Artist Info For Abraham Burton (983629)                           	True
Searching For Artist Info For Et (131852222)                                    	True
Searching For Artist Info For Ultra Stylus (5805409)                            	True
Searching For Artist Info For Ya Hiness (55989722)                              	True
Searching For Artist Info For The Spanish Salsa Connection (4473286)            	True
======================================================================================================================================================
2700/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 37 Minutes.
Saving 378319 (New=2700) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For The Millenium (4248085)                           	True
Searching For Artist Info For Saturnia (152365192)                              	True
Searching For Artist Info For Soft Noises for Being Calm (157313192)            	True
Searching For Artist Info For Stanny Abram (650214)                             	True
Searching For Artist Info For Simon Heist (7901614)                             	True
Searching For Artist Info For Soulja-Cona Takin' Ova's (8499522)                	True
Searching For Artist Info For Aki ja Turo (9644596)                             	True
Searching For Artist Info For Orfeon Donostiarra (459026)                       	True
Searching For Artist Info For Chewy Division (51613392)                         	True
Searching For Artist Info For Goon Moon (275714)                                	True
Searching For Artist Info For Chocho Maldito (10741304)                         	True
Searching For Artist Info For The Trees (408112)                                	True
Searching For Artist Info For Elizabeth Plunk and Ovanir Buosi (7956926)        	True
Searching For Artist Info For Barzek (5469529)                                  	True
Searching For Artist Info For Mario Carrara (191116)                            	True
Searching For Artist Info For Hildegard Behrens (4550992)                       	True
Searching For Artist Info For Ken Bruce (1225406)                               	True

Searching For Artist Info For Pete Mazell (3561311)                             	True
Searching For Artist Info For Nico Stojan & David Dorad (2514401)               	True
Searching For Artist Info For Nothing More Precious (124792222)                 	True
Searching For Artist Info For Tieum and Neophyte (4447009)                      	True
Searching For Artist Info For 50 Man Machine (5344202)                          	True
Searching For Artist Info For KIING CHAZBO (126271292)                          	True
Searching For Artist Info For Mister Leen (14293687)                            	True
Searching For Artist Info For Magic Hour Forest (123266202)                     	True
Searching For Artist Info For Sofia Madrigal &amp; Orchestral Ensemble (4175611)	True
Searching For Artist Info For Beny Ramirez (7574888)                            	True
Searching For Artist Info For Chyi Chin (131692)                                	True
Searching For Artist Info For Foolish And Sly (1282699)                         	True
Searching For Artist Info For Crifiu (256889)                                   	True
Searching For Artist Info For Fred Dogg (14640723)                              	True
Searching For Artist Info For Port Mortuary (72547222)                          	True
Searching For Artist Info For Secound Boyfriend (8561394)                       	True
Searching For Artist Info For Dj P'tit Ben (2245711)                            	True
Searching For Artist Info For Mélanie Laurent (210400)                         	True
Searching For Artist Info For Walter Gieseking (56796)                          	True
Searching For Artist Info For Lost Soulz (1088022)                              	True
Searching For Artist Info For Dadda Bellwether (58600902)                       	True
Searching For Artist Info For Maitreya (94314)                                  	True
Searching For Artist Info For Pata (4831490)                                    	True
Searching For Artist Info For Subway Terror (140725692)                         	True
Searching For Artist Info For Chris Rawles (864218)                             	True
Searching For Artist Info For Collegium Pro Musica de Paris (5612118)           	True
Searching For Artist Info For Jo Roland, Arth Paul und sein Orchester (1353192) 	True
Searching For Artist Info For The Soulsavers (1634525)                          	True
Searching For Artist Info For Chris Finster (7669516)                           	True
Searching For Artist Info For Big Pond (52912522)                               	True
Searching For Artist Info For Elias & Etienne (4188829)                         	True
Searching For Artist Info For Blacktop Audio (51889792)                         	True
Searching For Artist Info For Discolog (2004521)                                	True
======================================================================================================================================================
2750/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 38 Minutes.
Saving 378369 (New=2750) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For D O K T O R (92928802)                            	True
Searching For Artist Info For Mr. Bones And The Boneyard Circus (8478694)       	True
Searching For Artist Info For Deux Saisons (147312782)                          	True
Searching For Artist Info For TrapStarMula (13995021)                           	True
Searching For Artist Info For Rafael Falla Nieto (108801522)                    	True
Searching For Artist Info For The Soul Men (1506785)                            	True
Searching For Artist Info For DJ Khaikhan (4341204)                             	True
Searching For Artist Info For Toke Lars Bjarke (2558611)                        	True
Searching For Artist Info For Mark Howard, Stuart Duncan (1261188)              	True
Searching For Artist Info For Nia Rene (12991087)                               	True
Searching For Artist Info For Luxx Phobia (8927900)                             	True
Searching For Artist Info For Kee Rhymez (118498802)                            	True
Searching For Artist Info For Mizael gdv (128834992)                            	True
Searching For Artist Info For Ela Manô (9254382)                               	True
Searching For Artist Info For Chynna Jey (130149212)                            	True
Searching For Artist Info For Pastor Edson Cordeiro (110047282)                 	True
Searching For Artist Info For Shawn Greys (136523902)                           	True
Searching For Artist Info For H.E.L. (350025)                                   	True
Searching For Artist Info For Eric Chris Ward (5456113)                         	True
Searching For Artist Info For Willie Mabon, Hubert Sumlin, Eddie Taylor, Robert Stroger, Odie Payne (200709)	True
Searching For Artist Info For Mambo Greeen (62217002)                           	True
Searching For Artist Info For Animus Volt (9637206)                             	True
Searching For Artist Info For Mabele Elisi, Groupe Super 8-8 (4460223)          	True
Searching For Artist Info For Retriever (407929)                                	True
Searching For Artist Info For Jett Everill (63782402)                           	True
Searching For Artist Info For Anneliese Ninen-Zsigmondy (5241521)               	True
Searching For Artist Info For Jose Beat (5420713)                               	True
Searching For Artist Info For Child Of The Ancestors (143061522)                	True
Searching For Artist Info For MDEEZAY THA DUN (115255882)                       	True
Searching For Artist Info For Mysterious ML (74213022)                          	True
Searching For Artist Info For Rico Masro (3140521)                              	True
Searching For Artist Info For Olga Valkiria (8764826)                           	True
Searching For Artist Info For Ex-Trim (5822304)                                 	True
Searching For Artist Info For Richard F. Limouze (65016322)                     	True
Searching For Artist Info For Royal Army Ordnance Corps (328525)                	True
Searching For Artist Info For Nature Sounds 3D (154470702)                      	True
Searching For Artist Info For Fletch Towell Band (6016598)                      	True
Searching For Artist Info For Bodhi Rivers (87314202)                           	True
Searching For Artist Info For Robert Amis El Hage (4874598)                     	True
Searching For Artist Info For Spit Syndicate (154484)                           	True
Searching For Artist Info For Saona (4936521)                                   	True
Searching For Artist Info For Aldeburgh Festival Ensemble-Oliver Knussen-Susan Gritton-Ian Bostridge (4265719)	True
Searching For Artist Info For Kid Smitty (12104398)                             	True
Searching For Artist Info For Joyful Gospel (1071400)                           	True
Searching For Artist Info For Twitchin Skratch & Sickboy (1597683)              	True
Searching For Artist Info For Wiener Philharmoniker, Josef Krips and Gottlob Frick (11202214)	True
Searching For Artist Info For Bill Jennings Quintet (4654193)                   	True
Searching For Artist Info For VM18 & Negative Headphone (13509423)              	True
Searching For Artist Info For Merc City Music Archives (125404622)              	True
Searching For Artist Info For Apache 246 Music (122201692)                      	True
======================================================================================================================================================
2800/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 40 Minutes.
Saving 378419 (New=2800) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Simplex D.S.N. (1895311)                          	True

Searching For Artist Info For Rundfunk-Sinfonieorchester Berlin, Stefan Soltesz, Heidrun Holtmann (4960898)	True
Searching For Artist Info For Emg Thump (119091582)                             	True
Searching For Artist Info For Chrysalis Totem (135369002)                       	True
Searching For Artist Info For Offbeat Foundation (4439021)                      	True
Searching For Artist Info For Judge Minos (103182102)                           	True
Searching For Artist Info For Andrew Music Williams (5763706)                   	True
Searching For Artist Info For Watermelon Girls (139281722)                      	True
Searching For Artist Info For Les Petits Chanteurs de Saint Marc (4832184)      	True
Searching For Artist Info For Guilherme Rodrigues (148702212)                   	True
Searching For Artist Info For Downrocks (1612523)                               	True
Searching For Artist Info For Rafael Gutiérrez Moreno (141346322)              	True
Searching For Artist Info For Blakmajik (9435492)                               	True
Searching For Artist Info For Sahara Rock Band (13208985)                       	True
Searching For Artist Info For Tagma Magia Disharmony (91270222)                 	True
Searching For Artist Info For Rara Savage (82574102)                            	True
Searching For Artist Info For Kudo & Fish (7875816)                             	True
Searching For Artist Info For Nancy Whang (4468706)                             	True
Searching For Artist Info For Gone Dogs (13703529)                              	True
Searching For Artist Info For Alex Oliverio's Sunshine Ensemble (83406392)      	True
Searching For Artist Info For Ray Abrams (296589)                               	True
Searching For Artist Info For Louis Antoine Dornel (1637288)                    	True
Searching For Artist Info For Skeewiff vs. Shawn Lee (7169898)                  	True
Searching For Artist Info For Jesiel Candeia (63607622)                         	True
Searching For Artist Info For Lord Funk (3616)                                  	True
Searching For Artist Info For Γεωργία Κορώνη (5547419)                        	True
Searching For Artist Info For Project .44 (103600)                              	True
Searching For Artist Info For Kendra Shank (433409)                             	True
Searching For Artist Info For Taylor Jaye (9133802)                             	True
Searching For Artist Info For Vajra Voices (614296)                             	True
Searching For Artist Info For Harry Owens (1667307)                             	True
Searching For Artist Info For Tahiti Here (3331621)                             	True
Searching For Artist Info For Matriarch Inclusive (152079702)                   	True
Searching For Artist Info For SuchA BARF (143766002)                            	True
Searching For Artist Info For The Big Payback (5318216)                         	True
Searching For Artist Info For dj carlos msc (115855482)                         	True
Searching For Artist Info For Joe Barr (390392)                                 	True
Searching For Artist Info For Midnight Daydream (91630022)                      	True
Searching For Artist Info For Mystific (3039811)                                	True
Searching For Artist Info For Karan med varan (5406229)                         	True
Searching For Artist Info For Raku (117788502)                                  	True
Searching For Artist Info For Anaé & The Petrichor (146128522)                 	True
Searching For Artist Info For Bob Thiele (3328711)                              	True
Searching For Artist Info For Midnight Ambulance (121600792)                    	True
Searching For Artist Info For D'prince (2281221)                                	True
Searching For Artist Info For Yu Long (69270302)                                	True
Searching For Artist Info For Louie FMG (67722792)                              	True
Searching For Artist Info For The Areola Treat (1284797)                        	True
Searching For Artist Info For Wehbba & Ryo Peres (289104)                       	True
Searching For Artist Info For Jazzgroove Mothership Orchestra (252929)          	True
======================================================================================================================================================
2850/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 42 Minutes.
Saving 378469 (New=2850) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Marco D'andrea (5688392)                          	True
Searching For Artist Info For StaySleep Loso (55200202)                         	True
Searching For Artist Info For Ghastly Menace (1019307)                          	True
Searching For Artist Info For Niemelän Jalle (12986221)                        	True
Searching For Artist Info For Larry Thomas Lee (9166722)                        	True
Searching For Artist Info For Achim Kaufmann - Olie Brice (12083116)            	True
Searching For Artist Info For Cake Fart Prolapse (12422914)                     	True
Searching For Artist Info For eel rodeo (142410022)                             	True
Searching For Artist Info For Esteban Monge (13165107)                          	True
Searching For Artist Info For Rehab On The Track (9515014)                      	True
Searching For Artist Info For The Bokor (5159002)                               	True
Searching For Artist Info For Pray83 (113341412)                                	True
Searching For Artist Info For Rock e' Forte (75839822)                          	True
Searching For Artist Info For Badshah Bulbul (4053611)                          	True
Searching For Artist Info For Nikless (9818390)                                 	True
Searching For Artist Info For Stadtsingechor Halle (1518783)                    	True
Searching For Artist Info For The Absinthe Project (4761225)                    	True
Searching For Artist Info For Strawberry Jellyfish (101927612)                  	True
Searching For Artist Info For Damone (10821)                                    	True
Searching For Artist Info For Gse Mookie (91802322)                             	True
Searching For Artist Info For Orquesta Porteña Juan De Dios Filiberto (9791894)	True
Searching For Artist Info For eng8 (82783492)                                   	True
Searching For Artist Info For Декабрь (6461085)                                 	True
Searching For Artist Info For Heiko streicher (5116186)                         	True
Searching For Artist Info For Carmine Caputo (4664716)                          	True
Searching For Artist Info For William Alas (4965283)                            	True
Searching For Artist Info For Curtis Mechanuck (66350802)                       	True
Searching For Artist Info For Oscify (5094693)                                  	True
Searching For Artist Info For LL Kids Kinderliedjes (14101529)                  	True
Searching For Artist Info For Neva (84318492)                                   	True
Searching For Artist Info For Popo Ninja (119884882)                            	True
Searching For Artist Info For Saru Ban (11889013)                               	True
Searching For Artist Info For Kani Sidibé (80747722)                           	True
Searching For Artist Info For 2000 Lbs of Blues (4924929)                       	True
Searching For Artist Info For Philip Oakey (4421585)                            	True
Searching For Artist Info For Ending Heartfelt (86450192)                       	True
Searching For Artist Info For DJ Aspect (441483)                                	True
Searching For Artist Info For Aphrodelics (8025)                                	True
Searching For Artist Info For Reedjyne (109801102)                              	True
Searching For Artist Info For Gerry & The Holograms (9787404)                   	True

Searching For Artist Info For Mashup (410322)                                   	True
Searching For Artist Info For Ian Wallace-Glyndebourne Chorus-Glyndebourne Festival Orchestra-Bryan Balkwill-Vittorio Gui (1484004)	True
Searching For Artist Info For Leticia Gore (5690221)                            	True
Searching For Artist Info For Other Aspect (283483)                             	True
Searching For Artist Info For The Boomtang Boys (231116)                        	True
Searching For Artist Info For Uffe Steen (4112216)                              	True
Searching For Artist Info For Vindahl (777604)                                  	True
Searching For Artist Info For Nuol (9793490)                                    	True
Searching For Artist Info For B.Z.A (77375202)                                  	True
Searching For Artist Info For Tribe Dive & Rivo (10716623)                      	True
======================================================================================================================================================
2900/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 44 Minutes.
Saving 378519 (New=2900) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Genevieve Pitot, Robert Armbruster (4117718)      	True
Searching For Artist Info For Keysha Beats (156299402)                          	True
Searching For Artist Info For Symphonieorchester des Bayerischen Rundfunks, Kiri Te Kanawa, Siegfried Jerusalem and Bernard Haitink (11871487)	True
Searching For Artist Info For Lehar & Musumeci (8101629)                        	True
Searching For Artist Info For House Music 2015 (8928492)                        	True
Searching For Artist Info For Pandemic Protocol (63164682)                      	True
Searching For Artist Info For Yunis Hasan (13926525)                            	True
Searching For Artist Info For Blue Reverie (117092222)                          	True
Searching For Artist Info For Mandy Jones (4129423)                             	True
Searching For Artist Info For Khorophon (98798002)                              	True
Searching For Artist Info For Rootsman Fyah (131002222)                         	True
Searching For Artist Info For Macexface (63921612)                              	True
Searching For Artist Info For Hans Haider Group (13154329)                      	True
Searching For Artist Info For Soulman Snipes & KingPin da Composer (5631529)    	True
Searching For Artist Info For Outty Cas (6406722)                               	True
Searching For Artist Info For Mitcry (5604416)                                  	True
Searching For Artist Info For Paranoia (118679712)                              	True
Searching For Artist Info For Voochie P (13471329)                              	True
Searching For Artist Info For Hilly Eye (1000023)                               	True
Searching For Artist Info For YG Porky (4085713)                                	True
Searching For Artist Info For Ronald Stevenson (1712021)                        	True
Searching For Artist Info For Banda Paranoia (100224612)                        	True
Searching For Artist Info For The Last Pandemic (81355282)                      	True
Searching For Artist Info For Trancemission (140316)                            	True
Searching For Artist Info For Robert Soares (88599722)                          	True
Searching For Artist Info For Groove Killah (13262029)                          	True
Searching For Artist Info For Wiener Biedermeier Solisten (11953029)            	True
Searching For Artist Info For Taco Bambú (10108698)                            	True
Searching For Artist Info For The Dopeness (1174800)                            	True
Searching For Artist Info For Akane Matsumoto, Koji Yamashita, Gaku Hasegawa, Hironobu Saito & Kei Uemura (1391421)	True
Searching For Artist Info For Vigo Qinan (4550129)                              	True
Searching For Artist Info For Vital Techtones (9077222)                         	True
Searching For Artist Info For Unwelcome Visitors (64665392)                     	True
Searching For Artist Info For Grigory Karassev (4545092)                        	True
Searching For Artist Info For Lithium Fix (1126593)                             	True
Searching For Artist Info For Francesco Lotoro (57818)                          	True
Searching For Artist Info For Marco Ambrosini - Michael Posch - Thomas Wimmer - Riccardo Delfino - Augusta Campagne (1556904)	True
Searching For Artist Info For Warehouse Rats (76041792)                         	True
Searching For Artist Info For Reginald S. Stuckey (13496307)                    	True
Searching For Artist Info For Lily (Riho Sayashi) (122871112)                   	True
Searching For Artist Info For Chill After Dark Club (7818604)                   	True
Searching For Artist Info For TMS. Selva Kumar (85047122)                       	True
Searching For Artist Info For Gabry Ponte Feat. Little Tony (65019)             	True
Searching For Artist Info For MUNEYBAG BAE (135859722)                          	True
Searching For Artist Info For Princeton Dunne (68985122)                        	True
Searching For Artist Info For El Pastiche (10613503)                            	True
Searching For Artist Info For Aurus (51957822)                                  	True
Searching For Artist Info For Dirk Heinrich (6436804)                           	True
Searching For Artist Info For The Walt Wagner Trio (87811092)                   	True
Searching For Artist Info For Glues (110596792)                                 	True
======================================================================================================================================================
2950/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 45 Minutes.
Saving 378569 (New=2950) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Kieran Apter (12846325)                           	True
Searching For Artist Info For Fulton Sheen (70393622)                           	True
Searching For Artist Info For The Denim Rips (95939012)                         	True
Searching For Artist Info For Philipp Ray & Viktoriya Benasi (1623616)          	True
Searching For Artist Info For Felony Raheem (7557006)                           	True
Searching For Artist Info For Twisted Groove (1684889)                          	True
Searching For Artist Info For Luke Woodman (92827722)                           	True
Searching For Artist Info For Othar Turner & The Rising Star Fife And Drum Band (168629)	True
Searching For Artist Info For Freddy Be (10345188)                              	True
Searching For Artist Info For Ciro Riccardi (6754203)                           	True
Searching For Artist Info For De$mond Taylormade (49237722)                     	True
Searching For Artist Info For Far Out Sounds (7864516)                          	True
Searching For Artist Info For Honeymoon Production (12890295)                   	True
Searching For Artist Info For Martynas Auglys (9847916)                         	True
Searching For Artist Info For Mia & Summer Steadman (1081785)                   	True
Searching For Artist Info For Akwesasne Big Bear Singers (5623916)              	True
Searching For Artist Info For Precise Difference (14339907)                     	True
Searching For Artist Info For Patrizio Attampato (5348085)                      	True
Searching For Artist Info For Yunalesca (124733122)                             	True
Searching For Artist Info For Hangman's VooDoo (5552287)                        	True
Searching For Artist Info For The Prime Minister (4195299)                      	True
Searching For Artist Info For Hilo Hawaiian Orchestra (4098006)                 	True

Searching For Artist Info For Pav Purewal (1358426)                             	True
Searching For Artist Info For Real People Not Actors (56104382)                 	True
Searching For Artist Info For Sup-Zer0 (65527912)                               	True
Searching For Artist Info For Cala Coves (15361529)                             	True
Searching For Artist Info For Orchestra of the National Gugak Centre of Korea (6979719)	True
Searching For Artist Info For Min O Taur (7363594)                              	True
Searching For Artist Info For Green Sky Accident (357809)                       	True
Searching For Artist Info For Shit Body Painting (158257112)                    	True
Searching For Artist Info For Micky Torpedo (81086592)                          	True
Searching For Artist Info For Imon and the Snails (157501792)                   	True
Searching For Artist Info For Tight Reigns (101942212)                          	True
Searching For Artist Info For Mike Daily (9378588)                              	True
Searching For Artist Info For Jim McGee (5353988)                               	True
Searching For Artist Info For BRON-K (4871009)                                  	True
Searching For Artist Info For Sorority Fallout (150966092)                      	True
Searching For Artist Info For Girija Devi (103207)                              	True
Searching For Artist Info For Los Piratas Sabaneros (1313421)                   	True
Searching For Artist Info For Thomas Crawford (3003101)                         	True
Searching For Artist Info For Alberto Pizzigoni y sus Guitarras (70690112)      	True
Searching For Artist Info For Cry of condemned (138216202)                      	True
Searching For Artist Info For Phil Fearon (1505118)                             	True
Searching For Artist Info For AtomicPulse VS Mindstorm (647191)                 	True
Searching For Artist Info For Pandemic Wave (145971182)                         	True
Searching For Artist Info For The Good Soldiers (5057229)                       	True
Searching For Artist Info For Ed Woods (8075689)                                	True
Searching For Artist Info For The New Breed Band (6029116)                      	True
Searching For Artist Info For Mental Remedy (1263507)                           	True
Searching For Artist Info For The Four Vandals (4113814)                        	True
======================================================================================================================================================
3000/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 47 Minutes.
Saving 378619 (New=3000) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Blame Me! (13046011)                              	True
Searching For Artist Info For Sofia Cardoso (5586904)                           	True
Searching For Artist Info For The New Brood (52340212)                          	True
Searching For Artist Info For Polaroid Liquide (334086)                         	True
Searching For Artist Info For Anicet Akimoto (118399392)                        	True
Searching For Artist Info For Sinan Kurtulus (4423416)                          	True
Searching For Artist Info For Babii (5822885)                                   	True
Searching For Artist Info For Daniel Kehlmann (80700)                           	True
Searching For Artist Info For Kai-Lani (129466302)                              	True
Searching For Artist Info For City of Prague Phiharmonic Orchestra, James Fitzpatrick and Charlotte Kinder (2059921)	True
Searching For Artist Info For Kingikeem (11125388)                              	True
Searching For Artist Info For The Conservatory Experiment (8746616)             	True
Searching For Artist Info For Smiley Hobbs, Pete Kuykendall, and Mike Seeger (4202704)	True
Searching For Artist Info For Nathan Kousol (90429412)                          	True
Searching For Artist Info For Kallen (CV: Ami Koshimizu ) (100633922)           	True
Searching For Artist Info For Janney Gleb (113090702)                           	True
Searching For Artist Info For Zakhar Bron Chamber (4882998)                     	True
Searching For Artist Info For DJ Bakar (9855098)                                	True
Searching For Artist Info For Satori (feat. Masakazu Yoshizawa, Jim Brandmeier, Daniel May, Doug Livingston, Penny Watson, Richard Hardy, Michael Hamilton and Chris Wabisch) (4204829)	True
Searching For Artist Info For Unit 406 (11120116)                               	True
Searching For Artist Info For Emily Soon (6877783)                              	True
Searching For Artist Info For Aya Nakano y CENTRAL (70066702)                   	True
Searching For Artist Info For Trevor Exter (981125)                             	True
Searching For Artist Info For Anders Gunnarsson (9211404)                       	True
Searching For Artist Info For Sharon Den Adel (1662021)                         	True
Searching For Artist Info For Dinosaurtegning (136959712)                       	True
Searching For Artist Info For Paco Jarana feat. Manuel Salado (4375029)         	True
Searching For Artist Info For Loko D Mente (144184322)                          	True
Searching For Artist Info For Georgio Weis (5491426)                            	True
Searching For Artist Info For Kaden Frost (51742982)                            	True
Searching For Artist Info For Musty Banging (92858422)                          	True
Searching For Artist Info For Toni C. (4564111)                                 	True
Searching For Artist Info For Osmond Collins (1048786)                          	True
Searching For Artist Info For Face The Bass (12735723)                          	True
Searching For Artist Info For Antoine Landowski (8355916)                       	True
Searching For Artist Info For De Legende (365207)                               	True
Searching For Artist Info For Dbn Kai (130575822)                               	True
Searching For Artist Info For Württemberg Chamber Orchestra, Jörg Faerber & Felicja Blumental (4116101)	True
Searching For Artist Info For Sr. Piraña (78276522)                            	True
Searching For Artist Info For Tim Welsh (65103112)                              	True
Searching For Artist Info For Giuseppe Bruno Eight (2812691)                    	True
Searching For Artist Info For Setrak (1469804)                                  	True
Searching For Artist Info For Antonella Ciccozzi (1328725)                      	True
Searching For Artist Info For Nimrod Pitso (48940021)                           	True
Searching For Artist Info For Nuage & Das Bassorchester (10594613)              	True
Searching For Artist Info For Fis Duo (13730621)                                	True
Searching For Artist Info For Nico Huijbregts (5926823)                         	True
Searching For Artist Info For Sounds of Noah (73809522)                         	True
Searching For Artist Info For Ariel Electron (10381884)                         	True
Searching For Artist Info For Jac Ross (82373192)                               	True
======================================================================================================================================================
3050/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 49 Minutes.
Saving 378669 (New=3050) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For The Red Nuns (146837012)                          	True
Searching For Artist Info For Nke Akia Voicer (8777826)                         	True
Searching For Artist Info For Joee Calii (74704092)                             	True
Searching For Artist Info For Criatura y Fabula (54616202)                      	True

Searching For Artist Info For Mano de Mono (5897403)                            	True
Searching For Artist Info For Lone Wolf and Kub (50128922)                      	True
Searching For Artist Info For Rosi Golan (470916)                               	True
Searching For Artist Info For Blackmail the Emperor (79618602)                  	True
Searching For Artist Info For Venditti Bros (1207785)                           	True
Searching For Artist Info For Michael McNabb, Seth Vogt (1040213)               	True
Searching For Artist Info For Moodie and Blackslate (5775897)                   	True
Searching For Artist Info For East Nasa (11903723)                              	True
Searching For Artist Info For C-Note Hunneth Dollaz (13260701)                  	True
Searching For Artist Info For Akemi OST (136523922)                             	True
Searching For Artist Info For Ray Parker Jr. & Raydio (179522)                  	True
Searching For Artist Info For Green George, JimiJ (48908811)                    	True
Searching For Artist Info For D a n 1 e l (117791722)                           	True
Searching For Artist Info For Elusive Elevation (54026902)                      	True
Searching For Artist Info For Hide The False (13739285)                         	True
Searching For Artist Info For The Ambitions (4212396)                           	True
Searching For Artist Info For 6-AMC (74052822)                                  	True
Searching For Artist Info For Miz Bezzy (83241602)                              	True
Searching For Artist Info For S.M.K Zay (145140592)                             	True
Searching For Artist Info For Iku Hase (7179696)                                	True
Searching For Artist Info For Hank Snow (114716)                                	True
Searching For Artist Info For David Dorn (8158214)                              	True
Searching For Artist Info For Solid 6ix (140953212)                             	True
Searching For Artist Info For Ángeles López Artiga & José Madrid (4400613)   	True
Searching For Artist Info For David Leisner, Benny Kim, Robert Rinehart & Felix Fan (10332204)	True
Searching For Artist Info For Venetian Snares + Speedranch (1330903)            	True
Searching For Artist Info For Pivio, Aldo de Scalzi (373590)                    	True
Searching For Artist Info For Furious Monkey House (8999000)                    	True
Searching For Artist Info For Ivar Andrésen - Gunnar Graarud - Nelly Larsen-Todsen - Anny Helm - Hanns Beer - Gustaf Rodin - Chor und Orchester der Bayreuther Festspiele 1928 - Rudolf Bockelmann - Joachim Sattler (1557316)	True
Searching For Artist Info For NU4M & Kije (9986218)                             	True
Searching For Artist Info For The Corduroy Suit (5206514)                       	True
Searching For Artist Info For DJ Pupo Beats (10656689)                          	True
Searching For Artist Info For Trytobecool (66264192)                            	True
Searching For Artist Info For The Never Ending Fall (9705596)                   	True
Searching For Artist Info For Donel (5551288)                                   	True
Searching For Artist Info For Demian Destino (102411492)                        	True
Searching For Artist Info For Dmarx (11626611)                                  	True
Searching For Artist Info For Big Buff Beetles (94764412)                       	True
Searching For Artist Info For Kostas Mountakis (1041390)                        	True
Searching For Artist Info For L'Éloquent (62959802)                            	True
Searching For Artist Info For Space Music Inc (141407222)                       	True
Searching For Artist Info For Nakano Masaki (1466502)                           	True
Searching For Artist Info For Jamm'n James aka DJ Freaky Ray (131377892)        	True
Searching For Artist Info For DJ Diego James (146442292)                        	True
Searching For Artist Info For Cheba Zahia (4957821)                             	True
Searching For Artist Info For Boris Christoff - Orch De L'Association Des Concerts Lamoureux - Alexandre Tcherepnine - Maud Tortelier - Georges Tzipine (4348518)	True
======================================================================================================================================================
3100/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 51 Minutes.
Saving 378719 (New=3100) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Joe Belmont (5121516)                             	True
Searching For Artist Info For Steve Nelson Quartet, Steve Nelson, Mulgrew Miller, Ray Drummond, Tony Reedus (1240309)	True
Searching For Artist Info For 5yeed (86005022)                                  	True
Searching For Artist Info For Tatanka & Zany feat. Mc DV8 (1467107)             	True
Searching For Artist Info For Burgenland Duo mit Verena (1569026)               	True
Searching For Artist Info For Chris Daniel (1440319)                            	True
Searching For Artist Info For Skeez Young (95478292)                            	True
Searching For Artist Info For INTHENAME7 (69822512)                             	True
Searching For Artist Info For Edmondo Romano (4085611)                          	True
Searching For Artist Info For tonal y nagual (502785)                           	True
Searching For Artist Info For Echa Dewi (87236722)                              	True
Searching For Artist Info For Formatt (2665311)                                 	True
Searching For Artist Info For The Men Behind The Sun (5396229)                  	True
Searching For Artist Info For MC Rive (4217201)                                 	True
Searching For Artist Info For Helena Bonham Carter (194919)                     	True
Searching For Artist Info For Sudha Naimpally (13530809)                        	True
Searching For Artist Info For someday tricycle (5714698)                        	True
Searching For Artist Info For Roberto Casalino (4421523)                        	True
Searching For Artist Info For Hint of Blue (101503012)                          	True
Searching For Artist Info For Jan Van Hammer (5648993)                          	True
Searching For Artist Info For C.M.C (68692122)                                  	True
Searching For Artist Info For La Kuadra (14272429)                              	True
Searching For Artist Info For Party Xox (10483319)                              	True
Searching For Artist Info For Daegeon Chamber Choir (109678812)                 	True
Searching For Artist Info For Chilled Aqua (6557985)                            	True
Searching For Artist Info For Saigon Would Be Seoul (62185512)                  	True
Searching For Artist Info For Fallen Angel (89797)                              	True
Searching For Artist Info For Łukasz Długosz (6516585)                          	True
Searching For Artist Info For Alexander Stephen Gray,Tarquin Boyesen (10717091) 	True
Searching For Artist Info For Papillon Rising (12557804)                        	True
Searching For Artist Info For Dousk & Andree Eskay (5157314)                    	True
Searching For Artist Info For Secrets of the third Planet (7045525)             	True
Searching For Artist Info For Smallman (489095)                                 	True
Searching For Artist Info For Modular Master (7945618)                          	True
Searching For Artist Info For Clive Carroll (391411)                            	True
Searching For Artist Info For 3D White Noise Machine (91478692)                 	True
Searching For Artist Info For Queen of Darts (9940414)                          	True
Searching For Artist Info For Anna Hashimoto (5058116)                          	True
Searching For Artist Info For Soko Terz (11037512)                              	True
Searching For Artist Info For Lyen Roza (12535716)                              	True

Searching For Artist Info For GG Stenz (55165212)                               	True
Searching For Artist Info For The Holy Mess (405629)                            	True
Searching For Artist Info For Switchblade 3 (6949325)                           	True
Searching For Artist Info For Jake Beenplottin (132894412)                      	True
Searching For Artist Info For Kathleen MacInnes (982906)                        	True
Searching For Artist Info For Rimpa Siva (116198)                               	True
Searching For Artist Info For 0%Mercury (11484190)                              	True
Searching For Artist Info For Barbara Joyce (4339685)                           	True
Searching For Artist Info For La Banda De Fiesta (323218)                       	True
Searching For Artist Info For Agnieszka Lopacka (4468423)                       	True
======================================================================================================================================================
3150/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 52 Minutes.
Saving 378769 (New=3150) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Little White Mice (10437900)                      	True
Searching For Artist Info For Sylvia Smit & John Do (5815712)                   	True
Searching For Artist Info For Tim Rogers & The Twin Set (788723)                	True
Searching For Artist Info For Auri Mina (92511522)                              	True
Searching For Artist Info For Intellect (1217206)                               	True
Searching For Artist Info For C-M Carlsson (110821)                             	True
Searching For Artist Info For Mister K (352703)                                 	True
Searching For Artist Info For Blank & Jones with Laid Back (1685404)            	True
Searching For Artist Info For Xyrex (1402126)                                   	True
Searching For Artist Info For Herv (149313)                                     	True
Searching For Artist Info For Christina Sikora (51928102)                       	True
Searching For Artist Info For Pistol Star (49126721)                            	True
Searching For Artist Info For This Is for Real (5677793)                        	True
Searching For Artist Info For Young Desperado (5106399)                         	True
Searching For Artist Info For Allen Wadlo Williams (5611011)                    	True
Searching For Artist Info For Maria Cristina Kiehr (2037611)                    	True
Searching For Artist Info For Tesla (14078597)                                  	True
Searching For Artist Info For Yves Eaux & Melvin Spix (5822325)                 	True
Searching For Artist Info For Malte Schiller (6697229)                          	True
Searching For Artist Info For Ill Vene (146334222)                              	True
Searching For Artist Info For Russell Smith and the Amazing Rhythm Aces (1100829)	True
Searching For Artist Info For Highway 211 Band (5361900)                        	True
Searching For Artist Info For Chpre (71035802)                                  	True
Searching For Artist Info For P-Shantel (90051712)                              	True
Searching For Artist Info For The Film Band (310090)                            	True
Searching For Artist Info For Stereo Mutants feat. Jannae Jordan (1600203)      	True
Searching For Artist Info For Mel-o-maniacs (6840309)                           	True
Searching For Artist Info For DJ Patto (76497002)                               	True
Searching For Artist Info For Math Haan (6747389)                               	True
Searching For Artist Info For Gunnar de Frumerie (1603506)                      	True
Searching For Artist Info For Sheychan (14415123)                               	True
Searching For Artist Info For Operation Code Black (101267422)                  	True
Searching For Artist Info For Bra Bryte (142894092)                             	True
Searching For Artist Info For Bhargov Deka (73140692)                           	True
Searching For Artist Info For DJ Nita (492929)                                  	True
Searching For Artist Info For Zev Katz (6291300)                                	True
Searching For Artist Info For Jean Jacques Burnel (244506)                      	True
Searching For Artist Info For Lexy And Paul (9671718)                           	True
Searching For Artist Info For Marshall Zuniga (13937009)                        	True
Searching For Artist Info For ADR Music Studio (124005322)                      	True
Searching For Artist Info For DJ Sleep EZ (12623085)                            	True
Searching For Artist Info For NOIZ É TOP (90819402)                            	True
Searching For Artist Info For Tudor Davies (2311411)                            	True
Searching For Artist Info For Faltl - Kemmeter - Schrammeln - Erich Kunz (1556994)	True
Searching For Artist Info For Nagisa No Beethovens (94784792)                   	True
Searching For Artist Info For The Love Buckets (12280996)                       	True
Searching For Artist Info For Peter Power & Powerkryner (13003213)              	True
Searching For Artist Info For Mikel Molina, John Jacobsen (4373988)             	True
Searching For Artist Info For Gregory Aigersson (13710707)                      	True
Searching For Artist Info For Hangzoo (6947529)                                 	True
======================================================================================================================================================
3200/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 54 Minutes.
Saving 378819 (New=3200) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Alan 'The Elf' Davey (823411)                     	True
Searching For Artist Info For Faceless Orphans (13668419)                       	True
Searching For Artist Info For Patric La Funk feat. Jeremy Crowle (4093313)      	True
Searching For Artist Info For Mona Lisa Acelerada (13030513)                    	True
Searching For Artist Info For Ion Kid Seychelles (125841992)                    	True
Searching For Artist Info For East River Pipe (1658589)                         	True
Searching For Artist Info For S.D.I. Chuck stevenson (125154402)                	True
Searching For Artist Info For Griff Tyler (57267922)                            	True
Searching For Artist Info For IRIA M (142840392)                                	True
Searching For Artist Info For Catch The Cat (802925)                            	True
Searching For Artist Info For Les Chambristes de Ville-Marie, Karina Gauvin (128409)	True
Searching For Artist Info For ORK FAKULTETA (56024892)                          	True
Searching For Artist Info For Speed Limit Trio (4732398)                        	True
Searching For Artist Info For Ekow Anthem (129879302)                           	True
Searching For Artist Info For Sunny Rocket (2232711)                            	True
Searching For Artist Info For Vidsyn (196286)                                   	True
Searching For Artist Info For Osso. (146572992)                                 	True
Searching For Artist Info For KoQa Beatbox (7143513)                            	True
Searching For Artist Info For Don Pedro & Ses Dromadaires (110485)              	True
Searching For Artist Info For Atnarko & Jevne (490695)                          	True
Searching For Artist Info For The Night Of Dreams (135019402)                   	True
Searching For Artist Info For Linky (55719)                                     	True
Searching For Artist Info For M.E.G. (7605718)                                  	True
Searching For Artist Info For Prairie Dawn (4244104)                            	True

Searching For Artist Info For King Quad (49766992)                              	True
Searching For Artist Info For Hrvatski (8023)                                   	True
Searching For Artist Info For New Idea (65766792)                               	True
Searching For Artist Info For Lid Greyhound (6979721)                           	True
Searching For Artist Info For Servants To The Tide (129631122)                  	True
Searching For Artist Info For JK the Sage (89639812)                            	True
Searching For Artist Info For Laika Come Home (97676192)                        	True
Searching For Artist Info For RAM (REVOLT) (81362312)                           	True
Searching For Artist Info For a & e sounds (7996802)                            	True
Searching For Artist Info For Rimas Clandestinas (116221402)                    	True
Searching For Artist Info For Devon Jay Scott (12889609)                        	True
Searching For Artist Info For Floral Cemetery (14763719)                        	True
Searching For Artist Info For Nacho Peñalva (51718792)                         	True
Searching For Artist Info For Jimmy Gallagher (432513)                          	True
Searching For Artist Info For Claudio Piastra (185395)                          	True
Searching For Artist Info For Subsonica Orquestra (8058097)                     	True
Searching For Artist Info For Badoxa Pro (1091422)                              	True
Searching For Artist Info For DJ Pierre Presents PJ (4339129)                   	True
Searching For Artist Info For Adel Chaoui (10060106)                            	True
Searching For Artist Info For Sissy Zhou (5383182)                              	True
Searching For Artist Info For Mike Miller Quintet (2199611)                     	True
Searching For Artist Info For KissGang Truly (9646404)                          	True
Searching For Artist Info For Todd Terry & DJ S.K.T (12092198)                  	True
Searching For Artist Info For Kevlar Soul (14957703)                            	True
Searching For Artist Info For Fractal Sound Vs Mindstorm (650229)               	True
Searching For Artist Info For Max Sabatini (357904)                             	True
======================================================================================================================================================
3250/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 56 Minutes.
Saving 378869 (New=3250) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Starkillers vs Get Far (4339800)                  	True
Searching For Artist Info For Taylor John Williams (7851402)                    	True
Searching For Artist Info For D'vo (10386722)                                   	True
Searching For Artist Info For Dânti Amofinado (140595412)                      	True
Searching For Artist Info For Kumari Gunjan (12993321)                          	True
Searching For Artist Info For Global Don (66934802)                             	True
Searching For Artist Info For Humant Blod (90465322)                            	True
Searching For Artist Info For Alina Izquierdo (1321400)                         	True
Searching For Artist Info For Tina Says (10821116)                              	True
Searching For Artist Info For Klara & Jag (12074904)                            	True
Searching For Artist Info For DJ Wada (330816)                                  	True
Searching For Artist Info For Steve Hill, Rob Tissera & Klubfiller (7161206)    	True
Searching For Artist Info For Raymond Scott, Arnold Eidus, Carlo Bussotti (4071588)	True
Searching For Artist Info For Tin Zar Maw (12015916)                            	True
Searching For Artist Info For Nix'xon (12611199)                                	True
Searching For Artist Info For Wil Akogu (9903716)                               	True
Searching For Artist Info For Mike LeDonne Quintet, Tom Harrell, Gary Smulyan, Dennis Irwin, Kenny Washington (1240307)	True
Searching For Artist Info For WOOD SNIPES (74512682)                            	True
Searching For Artist Info For NSFG Jackboy (83526622)                           	True
Searching For Artist Info For Una Más PunkRock (115981302)                     	True
Searching For Artist Info For Christoph Eschenbach-Justus Frantz-Helmut Schmidt-London Philharmonic Orchestra (243018)	True
Searching For Artist Info For YUNG XANAX (98750822)                             	True
Searching For Artist Info For Pancake Drawer (88756412)                         	True
Searching For Artist Info For J.D V (51060702)                                  	True
Searching For Artist Info For Scott R. Looney, Oliver Lake, Paul Smoker & Lisle Ellis (1069914)	True
Searching For Artist Info For East Coast Offense (123502712)                    	True
Searching For Artist Info For AbsentMinded (81282792)                           	True
Searching For Artist Info For The Mole Rats (76978412)                          	True
Searching For Artist Info For Tayo O. (58923392)                                	True
Searching For Artist Info For Kemo Kante (110534182)                            	True
Searching For Artist Info For Karlie Lapeyrette (59846392)                      	True
Searching For Artist Info For Sune Wagner (312013)                              	True
Searching For Artist Info For Mitch Miller (73514)                              	True
Searching For Artist Info For Carrie Hennessey (109205822)                      	True
Searching For Artist Info For HM Surf (116762022)                               	True
Searching For Artist Info For KlubKidz (1250204)                                	True
Searching For Artist Info For Antonio Ocasio (545211)                           	True
Searching For Artist Info For No! Not the Bees! (6764419)                       	True
Searching For Artist Info For DJ Aleks Energy (1707216)                         	True
Searching For Artist Info For Ritta Tristany (10867390)                         	True
Searching For Artist Info For Superbanda (12537398)                             	True
Searching For Artist Info For Hoot Hester (2295301)                             	True
Searching For Artist Info For Jeff Katz (5807421)                               	True
Searching For Artist Info For Emma Jonson (69914482)                            	True
Searching For Artist Info For Czech Symphony Orchestra & John Landor (4192816)  	True
Searching For Artist Info For Makiesse Dub Club (124955692)                     	True
Searching For Artist Info For Orchestra of Jesus Christ Superstar Live in Concert (14442995)	True
Searching For Artist Info For Naked Muffin (1651519)                            	True
Searching For Artist Info For Ona Jane (9113616)                                	True
Searching For Artist Info For Ancient Current (100320822)                       	True
======================================================================================================================================================
3300/?     : Process [Getting Deezer ArtistIDs] Has Run For 1 Hour and 58 Minutes.
Saving 378919 (New=3300) Deezer Searched For Artist (Info) IDs
======================================================================================================================================================
Searching For Artist Info For Dark Ban Tes (91343312)                           	True
Searching For Artist Info For THE DEADLINER (154351012)                         	True
Searching For Artist Info For ashortstory (81016502)                            	True
Searching For Artist Info For Cyril Ornadel And The Starlight Symphony (2319621)	True
Searching For Artist Info For Sun Yi (1303287)                                  	True
Searching For Artist Info For Atrocity (78530892)                               	True
Searching For Artist Info For Original Uglyman (128510702)                      	True

Searching For Artist Info For NaYan DeKa (100911622)                            	True
Searching For Artist Info For Bruce Anderson IV (12106394)                      	True
Searching For Artist Info For AMM III (146004)                                  	True
Searching For Artist Info For One Word Story (13251919)                         	True
Searching For Artist Info For Marco T y Los Gatos (121539092)                   	True
Searching For Artist Info For Bubu Bambu (72235992)                             	True
Searching For Artist Info For The Jumper Cables (89428722)                      	True
Searching For Artist Info For Hadi28 (8987204)                                  	True
Searching For Artist Info For Orchestra of the German Opera Berlin (6385596)    	True
Searching For Artist Info For Natural Mystery Museum (66567222)                 	True
Searching For Artist Info For Zaz (6674104)                                     	True
Searching For Artist Info For The Higher Burning Fire (159988)                  	True
Searching For Artist Info For Deap Vally (2898911)                              	True
Searching For Artist Info For Gaz DB (89274992)                                 	True
Searching For Artist Info For Howl Baby Howl (815893)                           	True
Searching For Artist Info For Jay Campbell (8634482)                            	True
Searching For Artist Info For Fracture Trio (13136195)                          	True
Searching For Artist Info For 2 Paddies (12801787)                              	True
Searching For Artist Info For Corona Guitar Kvartet - Duo Lapoli (1345397)      	True
Searching For Artist Info For Marc-Uwe Kling (335225)                           	True
Searching For Artist Info For Soul_purpose (101276412)                          	True
Searching For Artist Info For The Thought (13927003)                            	True
Searching For Artist Info For Someday June (12661483)                           	True
Searching For Artist Info For Jeb Bush Orchestra (13844207)                     	True
Searching For Artist Info For Sam Preston (4431219)                             	True
Searching For Artist Info For Polyester Pimpstrap (5801219)                     	True
Searching For Artist Info For Unit 4 Plus 2 (1487309)                           	True
Searching For Artist Info For Berit Margrethe Oskal (5658929)                   	True
Searching For Artist Info For Decatur Dosh (13797587)                           	True
Searching For Artist Info For Lorenzo Terminelli (13444211)                     	True

## Save Results

In [48]:
from pandas import DataFrame, Series, concat
from listUtils import getFlatList

def getArtistNamesDataFrame(laid):
    df = None
    if isinstance(laid,dict) and len(laid) > 0:
        df = DataFrame(laid.values())
    return df
        
def getResponseDataFrame(laid):
    df = getArtistNamesDataFrame(laid)
    if not isinstance(df,DataFrame):
        return None
    df.index = df['id']
    df.drop(['id'], axis=1, inplace=True)
    return df

In [49]:
from pandas import concat
laid = localArtistsInfoData.get()
df  = getResponseDataFrame(laid)
if isinstance(df,DataFrame):
    print("Found {0} New Artists".format(df.shape[0]))
    searchDF = mio.data.getArtistsInfoData()    
    if isinstance(searchDF,DataFrame):
        print("Found {0} Previous Artists".format(searchDF.shape[0]))
        searchDF = concat([searchDF,df])
    else:
        print("Found 0 Previous Artists")
        searchDF = df
    print("Found {0} Total Artists".format(searchDF.shape[0]))
    searchDF = searchDF[~searchDF.index.duplicated(keep='first')]
    print("Found {0} Unique Artists".format(searchDF.shape[0]))
    searchDF['fans'] = searchDF['fans'].fillna(0).astype(int)
    searchDF = searchDF.sort_values(by='fans', ascending=False)
    print("Found {0} Unique + Sorted Artists".format(searchDF.shape[0]))
    print("  ==> {0} Old Artists".format(len(searchDF[searchDF.index.isin(knownArtists.index)])))
    print("  ==> {0} New Artists".format(len(searchDF[~searchDF.index.isin(knownArtists.index)])))
    print("Saving Data")
    mio.data.saveArtistsInfoData(data=searchDF)
else:
    print("No new artists")

Found 20500 New Artists
Found 355102 Previous Artists
Found 375602 Total Artists
Found 375602 Unique Artists
Found 375602 Unique + Sorted Artists
  ==> 345640 Old Artists
  ==> 29962 New Artists
Saving Data

In [50]:
localArtistsInfoData.save(data={})

In [37]:
searchDF = mio.data.getArtistsInfoData()
print("Found {0} Unique + Sorted Artists".format(searchDF.shape[0]))
print("  ==> {0} Old Artists".format(len(searchDF[searchDF.index.isin(knownArtists.index)])))
print("  ==> {0} New Artists".format(len(searchDF[~searchDF.index.isin(knownArtists.index)])))

Found 355102 Unique + Sorted Artists
  ==> 345640 Old Artists
  ==> 9462 New Artists

In [30]:
searchDF = searchDF[~searchDF.index.isna()]

In [35]:
mio.data.saveArtistsInfoData(data=searchDF)

# Download Related Artist Search Data

In [ ]:
mio   = deezer.MusicDBIO(verbose=False)
apiio = deezer.RawAPIData(debug=True)

## Find Related Artists

In [ ]:
useBasicData       = False
useSelfRelatedData = True
useMasterIDs       = False

if useBasicData is True:
    knownRelatedArtists = localRelated.get()
    basicData = DataFrame(mio.data.getSummaryNameData()).join(mio.data.getSummaryNumAlbumsData()).sort_values(by="NumAlbums", ascending=False)
    basicData.columns = ["ArtistName", "NumAlbums"]
    artistRelatedToGet = basicData["ArtistName"][~basicData["ArtistName"].index.isin(knownRelatedArtists.keys())]

    print("{0} Search Results".format(db))
    print("   Known Master Basic Data:     {0}".format(basicData.shape[0]))
    print("   Known Local Related Names:   {0}".format(len(knownRelatedArtists)))
    print("   Artist Names To Get:         {0}".format(len(artistRelatedToGet)))
elif useSelfRelatedData is True:
    artistRelatedToGet  = {}
    knownRelatedArtists = localRelated.get()
    masterRelatedArtistData = mio.data.getRelatedArtistsData()
    for artistID,artistIDData in masterRelatedArtistData.iteritems():
        artistRelatedToGet.update({str(k): v for k,v in artistIDData.items() if knownRelatedArtists.get(str(k)) is None})
    artistRelatedToGet = Series(artistRelatedToGet)

    print("{0} Search Results".format(db))
    print("   Known Master Related Data:   {0}".format(len(masterRelatedArtistData)))
    print("   Known Local Related Names:   {0}".format(len(knownRelatedArtists)))
    print("   Artist Names To Get:         {0}".format(len(artistRelatedToGet)))
elif useMasterIDs is True:
    meu = MusicDBIO()
    mmeDF = meu.getData()
    deezerMatchedArtistsData = mmeDF[mmeDF["Deezer"].notna()][["ArtistName", "Deezer"]]
    deezerMatchedArtists = deezerMatchedArtistsData["ArtistName"].copy(deep=True)
    deezerMatchedArtists.index = deezerMatchedArtistsData["Deezer"]
    artistRelatedToGet = Series({artistID: artistName for artistID,artistName in deezerMatchedArtists.iteritems() if knownRelatedArtists.get(artistID) is None})
    print("{0} Search Results".format(db))
    print("   Known Master Related Data:   {0}".format(len(deezerMatchedArtists)))
    print("   Known Local Related Names:   {0}".format(len(knownRelatedArtists)))
    print("   Artist Names To Get:         {0}".format(len(artistRelatedToGet)))

In [ ]:
from timeutils import Timestat, TermTime

ts = Timestat("Getting {0} ArtistIDs".format(db))
#tt = TermTime("tomorrow", "7:00am")
#tt = TermTime("tomorrow", "11:00am")
#tt = TermTime("today", "7:36pm")
tt = TermTime("today", "10:15pm")
maxN = 50000000

n  = 0
searchedForLocalRelated         = localRelated.get()
searchedForLocalRelatedData     = localRelatedData.get()
searchedForLocalArtistsInfo     = localArtistsInfo.get()
searchedForLocalArtistsInfoData = localArtistsInfoData.get()
searchedForErrors               = errors.get()
for i,(artistID,artistName) in enumerate(artistRelatedToGet.iteritems()):
    if searchedForLocalRelated.get(artistID) is not None:
        continue

    response = apiio.getArtistRelatedData(artistName=artistName, artistID=artistID)
    if response is None or len(response) == 0:
        if response is None:
            print("Error ==> {0}".format((artistID,artistName)))
            searchedForErrors[artistID] = artistName
            searchedForLocalRelated[artistID] = artistName
            apiio.sleep(3.5)
        else:
            searchedForLocalRelated[artistID] = artistName
            apiio.sleep(1.5)
        continue
    
    searchedForLocalRelated[artistID]     = artistName
    searchedForLocalRelatedData[artistID] = {str(rec['id']): rec['name'] for rec in response}
    for record in response:
        recID = str(record['id'])
        if searchedForLocalArtistsInfo.get(recID) is None:
            searchedForLocalArtistsInfo[recID]     = artistName
            searchedForLocalArtistsInfoData[recID] = record
    apiio.sleep(1.5)
    n += 1
        
    if n % 25 == 0:
        apiio.sleep(2.5)
        print("="*150)
        ts.update(n=n)
        print("Saving {0} {1} Searched For Artist (Related) IDs".format(len(searchedForLocalRelated), db))
        localRelated.save(data=searchedForLocalRelated)
        localRelatedData.save(data=searchedForLocalRelatedData)
        print("Saving {0} (New={1}) {2} Searched For Artist (Info) IDs".format(len(searchedForLocalArtistsInfo), len(searchedForLocalArtistsInfoData), db))
        localArtistsInfo.save(data=searchedForLocalArtistsInfo)
        localArtistsInfoData.save(data=searchedForLocalArtistsInfoData)
        if len(searchedForErrors) > 0:
            errors.save(data=searchedForErrors)
        print("="*150)
        apiio.sleep(2.5)
        if tt.isFinished():
            break
    
    if n >= maxN:
        print("Breaking after {0} downloads...".format(maxN))
        break
    
ts.stop()
print("Saving {0} {1} Searched For Artist (Related) IDs".format(len(searchedForLocalRelated), db))
localRelated.save(data=searchedForLocalRelated)
localRelatedData.save(data=searchedForLocalRelatedData)
print("Saving {0} {1} Searched For Artist (Info) IDs".format(len(searchedForLocalArtistsInfo), db))
localArtistsInfo.save(data=searchedForLocalArtistsInfo)
localArtistsInfoData.save(data=searchedForLocalArtistsInfoData)
if len(searchedForErrors) > 0:
    errors.save(data=searchedForErrors)

## Save Results

In [ ]:
from pandas import DataFrame, Series, concat
from listUtils import getFlatList

def getArtistNamesDataFrame(laid):
    df = None
    if isinstance(laid,dict) and len(laid) > 0:
        df = DataFrame(laid.values())
    return df
        
def getResponseDataFrame(laid):
    df = getArtistNamesDataFrame(laid)
    if not isinstance(df,DataFrame):
        return None
    df.index = df['id']
    df.drop(['id'], axis=1, inplace=True)
    return df

In [ ]:
laid = localArtistsInfoData.get()
df  = getResponseDataFrame(laid)
if isinstance(df,DataFrame):
    print("Found {0} New Artists".format(df.shape[0]))
    searchDF = mio.data.getArtistsInfoData()    
    if isinstance(searchDF,DataFrame):
        print("Found {0} Previous Artists".format(searchDF.shape[0]))
        searchDF = concat([searchDF,df])
    else:
        print("Found 0 Previous Artists")
        searchDF = df
    print("Found {0} Total Artists".format(searchDF.shape[0]))
    searchDF = searchDF[~searchDF.index.duplicated(keep='first')]
    print("Found {0} Unique Artists".format(searchDF.shape[0]))
    searchDF['fans'] = searchDF['fans'].astype(int)
    searchDF = searchDF.sort_values(by='fans', ascending=False)
    print("Found {0} Unique + Sorted Artists".format(searchDF.shape[0]))
    print("Saving Data")
    mio.data.saveArtistsInfoData(data=searchDF)
else:
    print("No new artists")

In [ ]:
df = localRelatedData.get()
if isinstance(df,dict):
    print("Found {0} New Artists".format(len(df)))
    searchDF = mio.data.getRelatedArtistsData()
    if isinstance(searchDF,Series):
        print("Found {0} Previous Artists".format(searchDF.shape[0]))
        searchDF = searchDF.append(Series(df))
    else:
        print("Found 0 Previous Artists")
        searchDF = df
    print("Found {0} Total Artists".format(searchDF.shape[0]))
    searchDF = searchDF[~searchDF.index.duplicated(keep='first')]
    print("Found {0} Unique Artists".format(searchDF.shape[0]))
    print("Saving Data")
    mio.data.saveRelatedArtistsData(data=searchDF)

In [ ]:
localRelatedData.save(data={})
localArtistsInfoData.save(data={})

# Combined Artist Info Data

In [41]:
artistRelatedData = mio.data.getRelatedArtistsData()
artistRelatedData.name = "RelatedArtists"
artistRelatedData = DataFrame(artistRelatedData)
artistInfoData    = mio.data.getArtistsInfoData()

In [39]:
artistInfoData

,name,link,tracks,type,picture,albums,fans
id,,,,,,,
246791,Drake,https://www.deezer.com/artist/246791,https://api.deezer.com/artist/246791/top?limit=50,artist,https://api.deezer.com/artist/246791/image,46.0,21698854
542,David Guetta,https://www.deezer.com/artist/542,https://api.deezer.com/artist/542/top?limit=50,artist,https://api.deezer.com/artist/542/image,208.0,17910780
384236,Ed Sheeran,https://www.deezer.com/artist/384236,https://api.deezer.com/artist/384236/top?limit=50,artist,https://api.deezer.com/artist/384236/image,86.0,17861429
13,Eminem,https://www.deezer.com/artist/13,https://api.deezer.com/artist/13/top?limit=50,artist,https://api.deezer.com/artist/13/image,50.0,15075739
892,Coldplay,https://www.deezer.com/artist/892,https://api.deezer.com/artist/892/top?limit=50,artist,https://api.deezer.com/artist/892/image,90.0,14995668
...,...,...,...,...,...,...,...
63749742,Enema SDO,https://www.deezer.com/artist/63749742,https://api.deezer.com/artist/63749742/top?lim...,artist,https://api.deezer.com/artist/63749742/image,5.0,0
127615382,Rude Boy Orcish Ops,https://www.deezer.com/artist/127615382,https://api.deezer.com/artist/127615382/top?li...,artist,https://api.deezer.com/artist/127615382/image,8.0,0
68442812,Sound Dampening Elimination,https://www.deezer.com/artist/68442812,https://api.deezer.com/artist/68442812/top?lim...,artist,https://api.deezer.com/artist/68442812/image,1.0,0
143611642,Doğu Bosphorus - Prof,https://www.deezer.com/artist/143611642,https://api.deezer.com/artist/143611642/top?li...,artist,https://api.deezer.com/artist/143611642/image,0.0,0
91315812,Yz JT,https://www.deezer.com/artist/91315812,https://api.deezer.com/artist/91315812/top?lim...,artist,https://api.deezer.com/artist/91315812/image,9.0,0

In [44]:
from pandas import merge
artistInfoData.join(artistRelatedData)

,name,link,tracks,type,picture,albums,fans,RelatedArtists
id,,,,,,,,
246791,Drake,https://www.deezer.com/artist/246791,https://api.deezer.com/artist/246791/top?limit=50,artist,https://api.deezer.com/artist/246791/image,46.0,21698854,"{339209: 'J. Cole', 165930: 'Future', 5828: 'D..."
542,David Guetta,https://www.deezer.com/artist/542,https://api.deezer.com/artist/542/top?limit=50,artist,https://api.deezer.com/artist/542/image,208.0,17910780,"{'1564992': 'MORTEN', '3968561': 'Martin Garri..."
384236,Ed Sheeran,https://www.deezer.com/artist/384236,https://api.deezer.com/artist/384236/top?limit=50,artist,https://api.deezer.com/artist/384236/image,86.0,17861429,"{'9956746': 'Tom Grennan', '6396188': 'Anne-Ma..."
13,Eminem,https://www.deezer.com/artist/13,https://api.deezer.com/artist/13/top?limit=50,artist,https://api.deezer.com/artist/13/image,50.0,15075739,"{417645: 'D12', 1352674: 'Skylar Grey', 66: '5..."
892,Coldplay,https://www.deezer.com/artist/892,https://api.deezer.com/artist/892/top?limit=50,artist,https://api.deezer.com/artist/892/image,90.0,14995668,"{'106': 'Keane', '163': 'U2', '1642': 'Snow Pa..."
...,...,...,...,...,...,...,...,...
63749742,Enema SDO,https://www.deezer.com/artist/63749742,https://api.deezer.com/artist/63749742/top?lim...,artist,https://api.deezer.com/artist/63749742/image,5.0,0,NaN
127615382,Rude Boy Orcish Ops,https://www.deezer.com/artist/127615382,https://api.deezer.com/artist/127615382/top?li...,artist,https://api.deezer.com/artist/127615382/image,8.0,0,NaN
68442812,Sound Dampening Elimination,https://www.deezer.com/artist/68442812,https://api.deezer.com/artist/68442812/top?lim...,artist,https://api.deezer.com/artist/68442812/image,1.0,0,NaN
143611642,Doğu Bosphorus - Prof,https://www.deezer.com/artist/143611642,https://api.deezer.com/artist/143611642/top?li...,artist,https://api.deezer.com/artist/143611642/image,0.0,0,NaN
91315812,Yz JT,https://www.deezer.com/artist/91315812,https://api.deezer.com/artist/91315812/top?lim...,artist,https://api.deezer.com/artist/91315812/image,9.0,0,NaN

In [45]:
knownArtists

4598500             Irish Traditional
7378600           Aase Nordmo-Løvberg
4624200           Aase Nordmo Lovberg
9834600                        Eh Vee
4037700     Adriano Dodici, Dj Renato
                      ...
13973299        Ese Nando & Dj Stigma
13560499               Katsuro Tajima
10503399                    Nunu Umay
7112399                   Dreamliners
1067699       Voice In The Wilderness
Length: 1069560, dtype: object